### ISSUE TITLE
HTTPS Support for docs.awssolutionsbuilder.com

### ISSUE THREAD

**Issue by rrrix** [awslabs/aws-solutions-constructs#1]
Please support HTTPS / TLS on the documentation site: https://docs.awssolutionsbuilder.com

### Use Case

HTTPS all the things, please :) 

https://d1.awsstatic.com/whitepapers/Security/AWS_Security_Best_Practices.pdf#page=39

### Proposed Solution

The site appears to be a public website-enabled S3 bucket: 
https://s3.us-east-1.amazonaws.com/docs.awssolutionsbuilder.com/aws-solutions-konstruk/latest/index.html 

```
~ $ dig +noall +answer docs.awssolutionsbuilder.com.
docs.awssolutionsbuilder.com. 4	IN	A	52.216.78.43
~ $ dig +noall +answer -x 52.216.25.251
251.25.216.52.in-addr.arpa. 894	IN	PTR	s3-website-us-east-1.amazonaws.com.
```

Perhaps a CloudFront Distribution + ACM certificate? 

Maybe dogfood the [@aws-solutions-konstruk/aws-cloudfront-s3](https://github.com/awslabs/aws-solutions-constructs/tree/master/source/patterns/%40aws-solutions-konstruk/aws-cloudfront-s3) package? That has the benefit of also apparently using some Security related HTTP Headers with a Lambda@Edge. 

### Other

The documentation site gets an `F` from Mozilla Observatory :( https://observatory.mozilla.org/analyze/docs.awssolutionsbuilder.com

* [X] :wave: I may be able to implement this feature request (if the docs site is open source?)
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hnishar** [comment]
We have successfully migrated Documentation to the official AWS Documentation home @ https://docs.aws.amazon.com/solutions/latest/constructs/welcome.html
