### ISSUE TITLE
aws-sqs-lambda & KMS

### ISSUE THREAD

**Issue by moltar** [awslabs/aws-solutions-constructs#10]
[Docs](https://docs.aws.amazon.com/solutions/latest/constructs/aws-sqs-lambda.html?did=cs_card&trk=cs_card) state:

> Enable server-side encryption for source SQS Queue using AWS managed KMS Key

But when I am looking at the [code](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/aws-sqs-lambda/lib/index.ts) I don't see any KMS constructs.

I am somewhat new to this, and maybe missing something.

This is :bug: Bug Report

**Comment by hnishar** [comment]
It does not create the KMS key but instead uses the AWS Managed KMS key, see [here](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/core/lib/sqs-defaults.ts#L18)

**Comment by moltar** [comment]
Ah, thanks, awesome! Learned something new about Customer Master Key. Had no idea it was available :)
