### ISSUE TITLE
aws-eventbridge-sns fails validation for long topic names

### ISSUE THREAD

**Issue by doublecompile** [awslabs/aws-solutions-constructs#1015]
When I use the `@aws-solutions-constructs/aws-eventbridge-sns` solution in conjunction with an SNS topic having a name longer than 64 characters, CloudFormation throws a validation error.

```
Error: The stack named ExampleLongStackName-Dev-Main failed to deploy: UPDATE_ROLLBACK_COMPLETE: 1 validation error detected: Value 'ExampleLongStackName-Dev-Main-LongExampleTopic2EDA8B02-DpDO44me9z' at 'targets.1.member.id' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: 2695f1db-7bf0-470d-a89a-fee880abb30a; Proxy: null)
```

- The [CloudFormation guide for AWS::EventBridge::Rule Target](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-target.html#cfn-events-rule-target-id) lists `Id` as having a maximum of 64 characters.
- The [CloudFormation guide for AWS::SNS::Topic](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html#cfn-sns-topic-topicname) lists `TopicName` as having a maximum of 256 characters.

One option to fix the problem is to add an additional property to `EventbridgeToSnsProps` (e.g. named `eventTargetId`) that overrides the value supplied on this line:

https://github.com/awslabs/aws-solutions-constructs/blob/035ea20d42f2491403d363f937e05e50bb0da6ef/source/patterns/%40aws-solutions-constructs/aws-eventbridge-sns/lib/index.ts#L113

...if the `eventTargetId` is `undefined` it could just use the topic name as it's currently doing now.

**Comment by biffgaut** [comment]
Sorry for the long delay in responding. I understand the issue. 

Allowing the client to specify the name would work, but a fixed could introduce issues with name collisions in the case of deploying 2 instances of the construct in one stack or two instances of the stack in one account. The client app would assume the responsibility of avoiding name collisions (currently we rely on CDK and CloudFormation to do that as much as possible).

Currently we have a topic name that is presumably unique, but too long. We could take a hash of the entire topic name, then append it to a truncated copy of the topic name to come up with a name that is <= 64 characters, reproducible and leverages the existing unique name.
