### ISSUE TITLE
aws-apigateway-sqs creates a path /message for the delete method, even when the DELETE method is not allowed in the API.

### ISSUE THREAD

**Issue by joe-king-sh** [awslabs/aws-solutions-constructs#1029]
Thank you for the excellent custom construct. I am considering using this construct but have noticed a concerning issue, hence this bug report.

In aws-apigateway-sqs, if the DELETE /message path is not used, it can be disabled by setting allowDeleteOperation to false in the properties.

However, in the current implementation, although setting it to false prevents the creation of the DELETE Method, the /message path, which is not supposed to be used, is still added to the API Gateway.

Having a path added to the API Gateway that is not intended to be used does not seem to be the expected behavior.

### Reproduction Steps

```typescript
  new ApiGatewayToSqs(stack, 'api-gateway-sqs', {
    allowDeleteOperation: true
  });
```

### Error Log

Generated template
```yaml
    "testapigatewaysqsdefaultRestApimessage41073D7F": {
      "Type": "AWS::ApiGateway::Resource",
      "Properties": {
        "ParentId": {
          "Fn::GetAtt": [
            "testapigatewaysqsdefaultRestApi554243C3",
            "RootResourceId"
          ]
        },
        "PathPart": "message",
        "RestApiId": {
          "Ref": "testapigatewaysqsdefaultRestApi554243C3"
        }
      }
    },
```

### Environment

  - **CDK CLI Version      :*2.105.0*
  - **CDK Framework Version:*2.105.0*
  - **AWS Solutions Constructs Version     :*2.46.0*
  - **OS                   :*macOS Ventura 13.2.1*
  - **Language             :*TypeScript*

### Other

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Thanks - I'm confused by your example, shouldn't the Reproduction Steps set the value to `false`?

**Comment by biffgaut** [comment]
Closed with PR1030

**Comment by joe-king-sh** [comment]
@biffgaut 
Sorry... you are correct. I have changed it to false. 
Thank you for your prompt review and the merge!
