### ISSUE TITLE
New Pattern: aws-cloudfront-mediastore

### ISSUE THREAD

**Issue by beomseoklee** [awslabs/aws-solutions-constructs#104]
As aws-solutions-constructs has `aws-cloudfront-X` patterns, it would be good to have `aws-cloudfront-mediastore` pattern to implement AWS Elemental MediaStore container as an Amazon CloudFront distribution origin.

### Use Case

An Amazon CloudFront distribution can have AWS Elemental MediaStore container as an origin, and this pattern would help to create an AWS CloudFormation template for live streaming solutions easily.

### Proposed Solution

1. Users can use the existing AWS Elemental MediaStore container.
1. The pattern creates a new AWS Elemental MediaStore container if not using the existing one.
   1. When creating a new container, it uses a user provided props. If no props are provided, it uses the default props.
   1. The default props used by the pattern would contain `aws:UserAgent` to only allow the specific user agent, and the CloudFront is going to have that in the custom header.
1. The pattern creates a new Amazon CloudFront distribution, and it uses user provided props if there is any. Otherwise, it uses the default props.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hnishar** [comment]
New pattern published in v1.77.0 release
