### ISSUE TITLE
Version: 2.49 Cannot Use  Custom cloudFrontLoggingBucketProps - 2.45 works though

### ISSUE THREAD

**Issue by anh-rivergon** [awslabs/aws-solutions-constructs#1056]
You cannot specify a custom "cloudFrontLoggingBucketProps" If you do, resulting CloudFormation template contains duplicate buckets and hence, the stack will fail.

### Reproduction Steps

Just specify a custom cloudFrontLoggingBucketProps rather than leaving it optional.

### Error Log

CREATE_FAILED        | AWS::S3::Bucket                      | CloudFrontToS3/CloudfrontLoggingBucket (CloudFrontToS3CloudfrontLoggingBucket59050E4A) abcxyz already exists in stack 

### Environment

  - **CDK CLI Version     2.122.0 (build 7e77e02) :**
  - **CDK Framework Version: 2
  - **AWS Solutions Constructs Version     2.49 
  - **OS                   :** Windows WSL2 / Ubuntu
  - **Language             :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Thanks, we'll check this out.

**Comment by biffgaut** [comment]
Can you provide an example of code that produces this error?

**Comment by biffgaut** [comment]
v2.59.0 completely overhauled the bucket property handling of this construct - allowing separate props objects for each of the four buckets that this construct can create. The docs on the web page have not been refreshed yet, look for the new interface in the [README](https://github.com/awslabs/aws-solutions-constructs/blob/main/source/patterns/%40aws-solutions-constructs/aws-cloudfront-s3/README.md) file. This clears up some odd functionality where we reused props for multiple buckets. and should address this issue.
