### ISSUE TITLE
Upgrade npmlog to higher version since npmlog: ^4.1.2 produce ReDoS vulnerabilties.

### ISSUE THREAD

**Issue by manju-eventbrite** [awslabs/aws-solutions-constructs#1074]
Description:
We ran a Synk scan on one of our repo and facing a vulnerability on "https://security.snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908"

On our research we identified that the root problem is aws-solutions-constructs -> core package is using npmlog version ^4.1.2
 [here](https://github.com/awslabs/aws-solutions-constructs/blob/5d5e0144c222ae9461ac9fc29fc983cb8953fea0/source/patterns/%40aws-solutions-constructs/core/package.json#L62) as dependencies which is causing the vulnerability.

We hit a similar issued earlier and we tried fixing it downstream by overriding the npmlog version to 7.0.1.  But this time we are not able to resolve the issue. Could you please help us to upgrade the npmlog and its dependencies to higher version ~7.0.1.

Thankyou!

**Error message from synk scan :** 
  Regular Expression Denial of Service (ReDoS) [High Severity][https://security.snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908] in ansi-regex@2.1.1
 introduced by @aws-solutions-constructs/core@2.46.0 > npmlog@4.1.2 > gauge@2.7.4 > string-width@1.0.2 > strip-ansi@3.0.1 > ansi-regex@2.1.1 and 1 other path(s)

**Comment by biffgaut** [comment]
Thanks for the heads up - we'll take a look and keep you posted.

**Comment by biffgaut** [comment]
This should be addressed in v2.52.0, available now.

**Comment by manju-eventbrite** [comment]
Thankyou :)
