### ISSUE TITLE
Version 2.53.0 - It is removing the permissions granted by other resources to StateMachines 

### ISSUE THREAD

**Issue by orekav** [awslabs/aws-solutions-constructs#1089]
Since I have updated the dependencies in my project to v2.53.0 I am having issues when I use grant permissions.

### Reproduction Steps

```typescript
const definition = new sfnTasks.CallAwsService(this, 'Copy S3 object', {
  service: 's3',
  action: 'copyObject',
  iamResources: [
    this.sourceBucket.bucketArn,
    this.destinationBucket.bucketArn,
  ],
  parameters: {
    CopySource: sfn.JsonPath.format(
      '{}/{}',
      sfn.JsonPath.stringAt('$.sourceBucketName'),
      sfn.JsonPath.stringAt('$.sourceObjectKey')
    ),
    Bucket: this.destinationBucket.bucketName,
    Key: sfn.JsonPath.format(
      '{}/{}',
      sfn.JsonPath.stringAt('$.destinationFolder'),
      sfn.JsonPath.stringAt('$.sourceObjectKey')
    ),
  },
  resultPath: sfn.JsonPath.DISCARD,
});

const { stateMachine } = new S3ToStepfunctions(this, 'MockedMediaPipeline', {
  deployCloudTrail: false,
  createCloudWatchAlarms: false,
  stateMachineProps: {
    definition,
  },
  existingBucketObj: this.sourceBucket,
});

this.sourceBucket.grantRead(stateMachine);
this.destinationBucket.grantWrite(stateMachine);
```

### Error Log

These are the differences, now my deployment is missing the policies on the right hand size of the screenshot

<img width="1315" alt="Screenshot 2024-02-23 at 11 35 30" src="https://github.com/awslabs/aws-solutions-constructs/assets/15952456/fe67e000-6e91-4355-8ac8-dc5fe4a004f4">

### Environment

  - **CDK CLI Version      :** v2.128.0
  - **CDK Framework Version:** v2.128.0
  - **AWS Solutions Constructs Version     :** v2.53.0
  - **OS                   :** MacOS
  - **Language             :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
We'll take a look. Can you tell me more about sourceBucket and originBucket? Are they created in this stack or imported?

**Comment by orekav** [comment]
Differences

<img width="1673" alt="Screenshot 2024-02-23 at 13 11 16" src="https://github.com/awslabs/aws-solutions-constructs/assets/15952456/7dcc4e15-2b35-4ad2-b037-a51ce7f3f923">

<img width="1675" alt="Screenshot 2024-02-23 at 13 11 45" src="https://github.com/awslabs/aws-solutions-constructs/assets/15952456/4f4ed4d3-e902-404d-8837-aec6d469f8ee">

<img width="1675" alt="Screenshot 2024-02-23 at 13 11 59" src="https://github.com/awslabs/aws-solutions-constructs/assets/15952456/e538559c-5670-4caa-b157-01d48910f95c">

**Comment by biffgaut** [comment]
Does the sample app perform correctly for Solutions Constructs 2.52.0? When I launch it, it doesn't appear to work. The eventBridgeEnabled property is not set on the source bucket, so the S3 events are not being sent to EventBridge which would prevent EventBridge from kicking off the state machine.

**Comment by biffgaut** [comment]
When I change the source bucket instantiation to this, the state machine executes:

```
    const sourceBucket = new s3.Bucket(this, 'SourceBucket', {
        eventBridgeEnabled: true
      });
```

(this is independent of the altered IAM policy, it's just something I found while digging deeply into the issue).

**Comment by biffgaut** [comment]
(sorry, shouldn't have closed - clicked the wrong button)

**Comment by biffgaut** [comment]
2.54.0 should fix the issue with the State Machine policy not accepting/retaining the bucket permissions.

**Comment by orekav** [comment]
> When I change the source bucket instantiation to this, the state machine executes:
> 
> ```
>     const sourceBucket = new s3.Bucket(this, 'SourceBucket', {
>         eventBridgeEnabled: true
>       });
> ```
> 
> (this is independent of the altered IAM policy, it's just something I found while digging deeply into the issue).

I haven't been looking at this, sorry for the late response.
The point of this issue is IAM policies, not the entire thing working. I could have used any X to StepFunction construct, the point was the missing IAM Policies for the StepFunction instance to invoke other services.

**Comment by orekav** [comment]
> 2.54.0 should fix the issue with the State Machine policy not accepting/retaining the bucket permissions.

I'll take a look, thanks 😄
