### ISSUE TITLE
Unable to use @aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3 with latest CDK versions

### ISSUE THREAD

**Issue by turacma** [awslabs/aws-solutions-constructs#1094]
Attempting to update dependencies in a project using `@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3` fails due to a pinned version of CDK in the package definition. this seems the opposite of the goals of the project.

> AWS Solutions Constructs and the AWS CDK are independent teams and have different release schedules. Each release of AWS Solutions Constructs is built against a specific version of the AWS CDK. The CHANGELOG.md file lists the CDK version associated with each AWS Solutions Constructs release. For instance, AWS Solutions Constructs v2.39.0 was built against AWS CDK v2.76.0. This means that to use AWS Solutions Constructs v2.39.0, your application must include AWS CDK v2.76.0 or later. You can continue to use the latest AWS CDK versions and upgrade the your AWS Solutions Constructs version when new releases become available.

### Reproduction Steps

```
npm install aws-cdk-lib
npm install @aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3
```

### Error Log

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @eight/cdk-constructs@0.3.37
npm ERR! Found: aws-cdk-lib@2.135.0
npm ERR! node_modules/aws-cdk-lib
npm ERR!   dev aws-cdk-lib@"^2.135.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer aws-cdk-lib@"2.130.0" from @aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3@2.54.0
npm ERR! node_modules/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3
npm ERR!   @aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3@"^2.54.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/turacma/.npm/_logs/2024-04-03T19_00_21_247Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/turacma/.npm/_logs/2024-04-03T19_00_21_247Z-debug-0.log
```

### Environment

  - **CDK CLI Version      :** `2.118.0 (build a40f2ec)`
  - **CDK Framework Version:** `aws-cdk-lib@2.135.0`
  - **AWS Solutions Constructs Version     :** `@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3@2.54.0`
  - **OS                   :** MacOS
  - **Language             :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Thanks for reaching out - we'll take a look. First impression is that we may be able to address this quickly.

**Comment by biffgaut** [comment]
We just dropped 2.54.1, I believe it will fix this issue. We updated the version of CDK underlying the constructs to the latest - so 2.54.1 will require CDK 2.135.0 _or later_ (the _or later_ aspect is what we fixed).

**Comment by biffgaut** [comment]
(Please reopen is the issue is not fully addressed, thanks)
