### ISSUE TITLE
SnsToSqs: There is already a Construct with name 'EncryptionKey'

### ISSUE THREAD

**Issue by fl0wo** [awslabs/aws-solutions-constructs#1101]
I'm using SnsToSqs two times _(more than one)_ with the same SNS (existingTopicObj) and a queueProps with visibilityTimeout 15min.

I also tried playing around with encryptionKeyProps but without luck.

### Reproduction Steps

   ```
const s3tosns = new S3ToSns(stack, `${id}s3-to-sns`, {
        existingBucketObj: bucket,  // <-- third part bucket
        topicProps: {
            topicName: `${id}sns`,
            displayName: `${id}sns`,
        },
        s3EventFilters: [
            {
                prefix: prefixS3Files,
                suffix: suffixS3Files,
            }
        ],
        s3EventTypes: [
            EventType.OBJECT_CREATED
        ],
    });

   const sns2sqs = new SnsToSqs(stack, id + '_sns_to_sqs', {
        existingTopicObj: s3tosns.snsTopic,  // <-- previously generated topic
        queueProps: {
            visibilityTimeout: Duration.minutes(15),
        },
    });
```

### Error Log

      throw new Error(`There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''}`);
            ^
Error: There is already a Construct with name 'EncryptionKey' in TradingResourcesStack [TradingResourcesTEST]
    at Node.addChild (/Users/xx/node_modules/constructs/src/construct.ts:447:13)
    at new Node (/Users/xx/node_modules/constructs/src/construct.ts:71:17)
    at new Construct (/Usersxx/node_modules/constructs/src/construct.ts:499:17)
    at new Resource (/Users/xx/node_modules/aws-cdk-lib/core/lib/resource.js:1:1309)
    at new KeyBase (/Users/xx/node_modules/aws-cdk-lib/aws-kms/lib/key.js:1:898)
    at new Key (/Users/flo/xx/node_modules/aws-cdk-lib/aws-kms/lib/key.js:1:7094)
    at Object.buildEncryptionKey (/Users/flo/xx/node_modules/@aws-solutions-constructs/aws-sns-sqs/node_modules/@aws-solutions-constructs/core/lib/kms-helper.ts:36:10)
    at new SnsToSqs (/Users/flo/xx/node_modules/@aws-solutions-constructs/aws-sns-sqs/lib/index.ts:137:32)

### Environment

  - **CDK CLI Version      :*2.99.0*
  - **CDK Framework Version:*2.99.0*
  - **AWS Solutions Constructs Version     :*2.54.0*
  - **OS                   :*MacOs*
  - **Language             :*TypeScript*

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Thanks for pointing this out - my first thought is this is on us and could be straightforward to fix. Let us dig into it, we'll have an hours/days/weeks level ETA shortly.

**Comment by biffgaut** [comment]
Can you doublecheck your CDK and Constructs versions? Solution Constructs v2.54.0 was built on CDK v2.130.0, so it requires CDK 2.130.0 or later and won't install on CDK 2.99.0 project.

**Comment by fl0wo** [comment]
Hi @biffgaut thanks for the quick reply.

cdk --version
2.124.0 (build 4b6724c)

// package.json
"aws-cdk-lib": "^2.99.0",
"@aws-solutions-constructs/aws-s3-sns": "^2.54.0",
"@aws-solutions-constructs/aws-s3-sqs": "^2.54.0",
"@aws-solutions-constructs/aws-sns-lambda": "^2.54.0",
"@aws-solutions-constructs/aws-sns-sqs": "^2.54.0",
"@aws-solutions-constructs/aws-sqs-lambda": "^2.54.0",

Not sure if that's the reason.

**Comment by biffgaut** [comment]
The caret (^) indicates that more recent versions are OK. I'm pretty sure if you look at:

_your-project_/node_modules/aws-cdk-lib/package.json

that you will find that it has installed 2.130.0 or later

**Comment by fl0wo** [comment]
Yeah, my bad forgot to include `^`

My aws-cdk-lib version is: 2.135.0

**Comment by biffgaut** [comment]
I believe v2.55.0 should address your issue.

**Comment by biffgaut** [comment]
(please reopen if the issue is not actually corrected)
