### ISSUE TITLE
@aws-solutions-constructs/aws-s3-lambda throws an error when CDK synth

### ISSUE THREAD

**Issue by vzverv** [awslabs/aws-solutions-constructs#113]
When run tests or do CDK synth an error is being thrown when I use an existing lambda and bucket

### Reproduction Steps
This is how I use the construct:
` 

new S3ToLambda(this, `${envNameUpperCase}S3ToLambda`, <S3ToLambdaProps>{

            existingBucketObj: myBucket,

            existingLambdaObj: processor,

            s3EventSourceProps: <S3EventSourceProps>{

                events: [EventType.OBJECT_CREATED, EventType.OBJECT_REMOVED],

                filters: [

                    <NotificationKeyFilter>{

                        prefix: 'path/in/bucket',

                    }

                ]

            },

        });`

### Error Log

`Test suite failed to run

    TypeError: this.bucket.addEventNotification is not a function

      66 | 
    > 67 |         new S3ToLambda(this, `${envNameUpperCase}S3ToLambda`, <S3ToLambdaProps>{
         |         ^
      68 |             existingBucketObj: existBucket,
      69 |             existingLambdaObj: existLambda,
      70 |             s3EventSourceProps: <S3EventSourceProps>{

      at S3EventSource.bind (node_modules/@aws-cdk/aws-lambda-event-sources/lib/s3.ts:31:19)
      at Function.addEventSource (node_modules/@aws-cdk/aws-lambda/lib/function-base.ts:344:12)
      at new S3ToLambda (node_modules/@aws-solutions-constructs/aws-s3-lambda/lib/index.ts:89:25)
      at new Processor (lib/processor/processor.ts:67:9)
      at new BeStack (lib/be-stack.ts:98:9)
      at Object.<anonymous> (test/awscdk/lambda-vpc.test.ts:8:15)
`

the **cdk synth** command results in this 
`
this.bucket.addEventNotification is not a function

Could not run version check - Directory (/Users/vitalii.dmytruk/.cdk/cache) is not writable.

Subprocess exited with error 1

Error: Subprocess exited with error 1

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/api/cxapp/exec.ts:122:23)

    at ChildProcess.emit (events.js:315:20)

    at ChildProcess.EventEmitter.emit (domain.js:482:12)

    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

`

### Environment

  - **CDK CLI Version      : 1.77**
  - **CDK Framework Version: 1.77**
  - **AWS Solutions Constructs Version     : 1.77**
  - **OS                   : Mac**
  - **Language             :TS**

### Other

--- 

This is :bug: Bug Report

**Comment by hnishar** [comment]
vzverv@ I could not replicate the issue you're facing, here's what I have, can you compare it with your code or share it here?

```
import * as s3 from '@aws-cdk/aws-s3';
import * as lambda from '@aws-cdk/aws-lambda';
import * as s3lambda from '@aws-solutions-constructs/aws-s3-lambda';
import * as cdk from '@aws-cdk/core';

export class CdkWorkshopStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const lambdaFunctionProps: lambda.FunctionProps = {
      runtime: lambda.Runtime.NODEJS_12_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(`${__dirname}/lambda`)
    };

    const processor = new lambda.Function(this, 'MyExistingFunction', lambdaFunctionProps);
  
    const myBucket = new s3.Bucket(this, 'my-bucket', {
      bucketName: 'my-bucket'
    });
  
    const constructProps: s3lambda.S3ToLambdaProps = {
      existingBucketObj: myBucket,
      existingLambdaObj: processor,
      s3EventSourceProps: {
        events: [s3.EventType.OBJECT_CREATED, s3.EventType.OBJECT_REMOVED],
        filters: [{
          prefix: 'path/in/bucket',
        }]
      }
    };
  
    new s3lambda.S3ToLambda(this, 'test-s3-lambda', constructProps);
  }
}
```

Both `npm run build` and `cdk synth` works successfully.

**Comment by vzverv** [comment]
@hnishar thanks for looking into the issue.
The difference is that you create your bucket in the very same script and you pass the Bucket object. In my case I create a bucket from ARN, thus I have an IBucket object, which doesn't have some methods that the Bucket object does. 

Off-topic:
I know about a similar issue when we try to add an existing bucket as a trigger to the lambda when we create the bucket from ARN. The same situation - Bucket vs IBucket. But for this case, I have a workaround, which I thought I could replace with the aws-solutions-construct. 
here is a [related issue](https://github.com/aws/aws-cdk/issues/2004)
and the [workaround](https://stackoverflow.com/questions/58087772/aws-cdk-how-to-add-an-event-notification-to-an-existing-s3-bucket/63062813#63062813)

Please let me know if you have any more questions. Thanks again!

**Comment by hnishar** [comment]
vzverv@ Thanks for the clarification. For the reasons noted in the referenced issue, the `aws-s3-lambda` construct is not designed to accept `existingBucketObj` of type `IBucket`, but instead requires type `Bucket`... that being said I'm curious how is it even allowing you to pass an instance of `IBucket`?

For instance, if I try to compile this:

```
    const myBucket = s3.Bucket.fromBucketName(this, "Bucket", "...");
  
    const constructProps: s3lambda.S3ToLambdaProps = {
      existingBucketObj: myBucket,
      existingLambdaObj: processor,
      s3EventSourceProps: {
        events: [s3.EventType.OBJECT_CREATED, s3.EventType.OBJECT_REMOVED],
        filters: [{
          prefix: 'path/in/bucket',
        }]
      }
    };
```

it throws the following error :

```
lib/cdk-workshop-stack.ts:25:7 - error TS2740: Type 'IBucket' is missing the following properties from type 'Bucket': autoCreatePolicy, lifecycleRules, notifications, metrics, and 34 more.

25       existingBucketObj: myBucket,
         ~~~~~~~~~~~~~~~~~

  node_modules/@aws-solutions-constructs/aws-s3-lambda/lib/index.d.ts:38:14
    38     readonly existingBucketObj?: s3.Bucket;
                    ~~~~~~~~~~~~~~~~~
    The expected type comes from property 'existingBucketObj' which is declared here on type 'S3ToLambdaProps'


Found 1 error.
````

**Comment by vzverv** [comment]
@hnishar It does as you can see from the logs in the initial message :) The interface of the function is pretty confusing, it says existingBucket, but in reality, it is about a freshly created bucket. 
I see 2 ways of resolving this: wait for that related issue to be fixed or use the workaround I posted in my previous post

**Comment by hnishar** [comment]
vzverv@ We will wait for the related [issue](https://github.com/aws/aws-cdk/issues/2004) to be fixed in CDK
