### ISSUE TITLE
API Gateway To Lambda: timeout cannot be over 29 seconds

### ISSUE THREAD

**Issue by kraashen** [awslabs/aws-solutions-constructs#1137]
AWS API Gateway timeout limit for integrations was previously 29 seconds. There has been an update to allow increasing the Gateway integration timeouts past the previous limit. https://aws.amazon.com/about-aws/whats-new/2024/06/amazon-api-gateway-integration-timeout-limit-29-seconds/ 

However, when implementing a Gateway API to Lambda, it seems that when synth'ing the stack, this seems to hit a validation error.

### Reproduction Steps

```
const ApiGateway = new ApiGatewayToLambda(
      this,
      'MyAPIGW',
      {
        lambdaFunctionProps: {
          runtime: Runtime.PROVIDED_AL2,
          handler: 'bootstrap',
          code: Code.fromAsset(join(__dirname, '..', '..', 'target', 'bin', 'linux', 'amd64', 'lambda', 'runtime')),
          timeout: Duration.minutes(5),
          environment: {
            ...
          },
        },
        apiGatewayProps: {
          defaultCorsPreflightOptions: {
            allowOrigins: ['*'],
            allowMethods: [HttpMethod.POST],
          },
          integrationOptions: {
            timeout: Duration.seconds(60),
          },
        },
      },
    );
```

### Error Log

```
WARN AWS_SOLUTIONS_CONSTRUCTS_WARNING:  Possible override of timeout value.
Failed to synthesize: Error: Integration timeout must be between 50 milliseconds and 29 seconds.
```

### Environment

  - **CDK CLI Version      :** 2.145.0 (build fdf53ba)
  - **CDK Framework Version:** 2.145.0
  - **AWS Solutions Constructs Version     :** 2.60.0
  - **OS                   :** MacOS
  - **Language             :** English

--- 

This is :bug: Bug Report

**Comment by kraashen** [comment]
Based on quick triage, this error seems to propagate from the aws-cdk core library: https://github.com/aws/aws-cdk/blob/db3e77d4b32a7464b38f8502d7c113ac163e17dc/packages/aws-cdk-lib/aws-apigateway/lib/integration.ts#L207-L209

**Comment by kraashen** [comment]
Fixed in `aws-cdk` release https://github.com/aws/aws-cdk/releases/tag/v2.147.0

**Comment by biffgaut** [comment]
Sorry for the slow response, thanks for following up.
