### ISSUE TITLE
Use NODEJS_20_X in use cases and patterns

### ISSUE THREAD

**Issue by trivikr** [awslabs/aws-solutions-constructs#1138]
Use NODEJS_20_X in use cases and patterns

### Use Case

Lambda NODEJS_16_X runtime is used in many tests and use cases https://github.com/search?q=repo%3Aawslabs%2Faws-solutions-constructs+NODEJS_16_X+path%3A*.ts&type=code

It's deprecated as of `Jun 12, 2024` and function create will be blocked on `Feb 28, 2025`.
Lambda Supported Runtimes https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

### Proposed Solution

Use NODEJS_20_X in use cases and patterns, which [was made available on Nov 15, 2023](https://aws.amazon.com/blogs/compute/node-js-20-x-runtime-now-available-in-aws-lambda/)

### Other

N/A

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
Sorry for the slow response - watch for this to come shortly.

**Comment by biffgaut** [comment]
The change is now in the repo, we should be pushing it in a new release when aws-apigatewayv2websockets-sqs is complete.

**Comment by trivikr** [comment]
> The change is now in the repo

Added in https://github.com/awslabs/aws-solutions-constructs/pull/1141

**Comment by biffgaut** [comment]
This was released with 2.61.0
