### ISSUE TITLE
aws-apigateway-dynamodb: setting "allowReadOperation" to false does not disable the read operation

### ISSUE THREAD

**Issue by JakePartusch** [awslabs/aws-solutions-constructs#115]
Setting `allowReadOperation` to `false` does not disable the read operation. 

### Reproduction Steps

``` typescript
import { ApiGatewayToDynamoDBProps, ApiGatewayToDynamoDB } from "@aws-solutions-constructs/aws-apigateway-dynamodb";

new ApiGatewayToDynamoDB(this, 'test-api-gateway-dynamodb-default', {
  allowReadOperation: false
});

```

### Error Log

There is no error in synthesizing the stack

### Environment

  - **CDK CLI Version      : 1.79.0**
  - **CDK Framework Version: 1.79.0**
  - **AWS Solutions Constructs Version     : 1.79.0**
  - **OS                   : Mac**
  - **Language             : TypeScript**

### Other

This issue seems to be with this conditional:
https://github.com/awslabs/aws-solutions-constructs/blob/8130c54616c0422b7b141b4bc9d3086becdf7a2d/source/patterns/%40aws-solutions-constructs/aws-apigateway-dynamodb/lib/index.ts#L154

Given the three input options (true/false/undefined), the conditional always will evaluate to `true`

--- 

This is :bug: Bug Report

**Comment by hnishar** [comment]
JakePartusch@ This bug is fixed in v1.80.0, for proof see [this](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/aws-apigateway-dynamodb/test/apigateway-dynamodb.test.ts#L241)
