### ISSUE TITLE
CloudFrontToS3: supporting http/3

### ISSUE THREAD

**Issue by yoshi-taka** [awslabs/aws-solutions-constructs#1158]
`HttpVersion: 'http2_3'` would be greatly appreciated.

### Use Case

https://aws.amazon.com/blogs/aws/new-http-3-support-for-amazon-cloudfront/

### Proposed Solution

defaults:
https://github.com/awslabs/aws-solutions-constructs/blob/main/source/patterns/%40aws-solutions-constructs/core/lib/cloudfront-distribution-defaults.ts

construct: 
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront.Distribution.html

tests:
https://github.com/search?q=repo%3Aawslabs%2Faws-solutions-constructs%20httpversion&type=code

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by biffgaut** [comment]
You can deploy this construct with other versions of HTTP right now by overriding the default in the [CloudFrontDistributionProps](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront.DistributionProps.html#httpversion). The code below  deploys a CloudFront distribution with HTTP 2 and 3:

```
    new CloudFrontToS3(this, 'test', {
      cloudFrontDistributionProps: {
        httpVersion: HttpVersion.HTTP2_AND_3
      }
    });
```

![image](https://github.com/user-attachments/assets/5bc9548a-1f84-4b3c-b74d-c2c9c52beb68)

For CloudFront distibutions already deployed, they can be upgraded with [no interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-distributionconfig.html#cfn-cloudfront-distribution-distributionconfig-httpversion).

**Comment by yoshi-taka** [comment]
Thanks a bunch! It’d be great if this could be the default. Feel free to close this issue.
