### ISSUE TITLE
Use supported version of Node.js in development

### ISSUE THREAD

**Issue by trivikr** [awslabs/aws-solutions-constructs#1165]
### Use Case

I followed instructions in https://github.com/awslabs/aws-solutions-constructs/blob/main/CONTRIBUTING.md while attempting to contribute to the repo.

The following error was thrown by jsii on running `npm run build+lint+test`

```console
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                            !!
!!  Node 16 has reached end-of-life on 2023-09-11 and is not supported.       !!
!!  Please upgrade to a supported node version as soon as possible.           !!
!!                                                                            !!
!!  This software is currently running on node v16.20.2.                      !!
!!  As of the current release of this software, supported node releases are:  !!
!!  - ^22.0.0 (Planned end-of-life: 2027-04-30)                               !!
!!  - ^20.0.0 (Planned end-of-life: 2026-04-30)                               !!
!!  - ^18.0.0 (Planned end-of-life: 2025-04-30)                               !!
!!                                                                            !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Proposed Solution

Use a supported version of Node.js for development.

Most projects use the latest LTS version.
At the time of writing in July 2024, it's Node.js 20.x

### Other

N/A

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by trivikr** [comment]
This is likely a miss in `CONTRIBUTING.md` documentation

The DEVELOPER_GUIDE recommends `jsii/superchain:1-bullseye-slim`, a change made in https://github.com/awslabs/aws-solutions-constructs/pull/1141

**Comment by trivikr** [comment]
Only doc update was needed.

Posted a PR at https://github.com/awslabs/aws-solutions-constructs/pull/1166

**Comment by biffgaut** [comment]
Thanks for pointing this out - the docker image had fallen behind in this file, the correct image to use is jsii/superchain:1-bullseye-slim. This is now updated in the doc.

**Comment by trivikr** [comment]
Thanks! I'm glad that the fix made in commit https://github.com/awslabs/aws-solutions-constructs/commit/be1c44e17ad0a70bcc40e3f513d391ca81c31f70 in the same as the one I'd posted in PR https://github.com/awslabs/aws-solutions-constructs/pull/1166
