### ISSUE TITLE
Use `jsii/superchain:1-bookworm-slim` for development

### ISSUE THREAD

**Issue by trivikr** [awslabs/aws-solutions-constructs#1167]
Use `jsii/superchain:1-bookworm-slim` for development

### Use Case

The projects currently uses `jsii/superchain:1-bullseye-slim` for development: https://github.com/awslabs/aws-solutions-constructs/blob/main/DEVELOPER_GUIDE.md#preparing-your-build-environment

As per their documentation in https://hub.docker.com/r/jsii/superchain, the `1-bullseye-slim` image is not actively maintained or updated.

### Proposed Solution

Switch to recommended `jsii/superchain:1-bookworm-slim` for development

### Other

The `jsii/superchain:1-bookworm-slim` uses latest version of node 18.x

```console
$ docker run -u root --rm --net=host -it -v $PWD:$PWD -w $PWD jsii/superchain:1-bookworm-slim
root@docker-desktop:/Users/trivikr/workspace/aws-solutions-constructs# node -v
v18.20.3
```

The `jsii/superchain:1-bullseye-slim` uses `node@v18.17.1`, as verified in https://github.com/awslabs/aws-solutions-constructs/pull/1166#issue-2440974816

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
Docs have been updated

**Comment by trivikr** [comment]
Docs still link `jsii/superchain:1-bullseye-slim`

Examples
* https://github.com/awslabs/aws-solutions-constructs/blob/main/DEVELOPER_GUIDE.md#preparing-your-build-environment
* https://github.com/awslabs/aws-solutions-constructs/blob/main/CONTRIBUTING.md#full-build

**Comment by biffgaut** [comment]
Sorry, I got this confused with 1165. We'll take a look.

**Comment by biffgaut** [comment]
OK, now it's done

**Comment by trivikr** [comment]
Verified that documentation was updated in the following commits:
* https://github.com/awslabs/aws-solutions-constructs/commit/71267c9379c02bc7efe41d72ac0d91c4f2ab273a
* https://github.com/awslabs/aws-solutions-constructs/commit/70275000108f131affb709278d2b02cf3dea91bd
