### ISSUE TITLE
Support monocdk

### ISSUE THREAD

**Issue by plastic-karma** [awslabs/aws-solutions-constructs#117]
I would like to use aws-solutions-constructs together with [monocdk](https://www.npmjs.com/package/monocdk).

### Use Case
 Monocdk is a different way of packaging cdk (see also [monolothic-packaging](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0006-monolothic-packaging.md)). When I am creating constructs with monocdk (e.g. a stack) and I pass that to a construct from aws-solutions-constructs, I get the following error:

```
Type 'import("<path to project>/node_modules/monocdk/lib/core/lib/construct-compat").ConstructNode' is not assignable to type 'import("<path to project>node_modules/@aws-cdk/core/lib/construct-compat").ConstructNode'.
        Types have separate declarations of a private property 'host'.
```

Example: 
```
import core = require('monocdk');
import {SqsToLambda} from "@aws-solutions-constructs/aws-sqs-lambda";

export class MyStack extends core.Stack {
     constructor(scope: core.Construct) {
           const lambdaFunction = new SqsToLambda(this, 'ExampleLambda', {...})
     }
}
```

* [ ] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hnishar** [comment]
plastic-karma@ The `aws-solutions-constructs` modules do not support `monocdk`, the reason being `aws-solutions-constructs` are built using `@aws-cdk/**` modules and hence cannot be combined with the `monocdk` module within the same CDK app. In general, CDK app or library cannot combine `monocdk` and `@aws-cdk/**` modules, for reference see [this](https://github.com/aws/aws-cdk/issues/11658) issue in CDK repo.

**Comment by plastic-karma** [comment]
Thanks  hnishar@ for the response. I understand the current limitation. But what is the plan for the future? Will aws-solutions-constructs migrate to mono-cdk at some point?

**Comment by hnishar** [comment]
Yes, we have a backlog item to look into CDK v2.0 (aka monocdk) support for `aws-solutions-constructs`, at this point there's no ETA.. as we solidify the plans I will share the updates here..

**Comment by hnishar** [comment]
aws-solutions-constructs [v2.0.0-rc.1](https://github.com/awslabs/aws-solutions-constructs/blob/main/CHANGELOG.v2.md#200-rc1-2021-10-12) is now available  🎉 in NPM, PyPi and Maven. It will require `aws-cdk-lib` version`^2.0.0-rc.23`, for more information on how to use CDK v2, refer to [this](https://aws.amazon.com/blogs/developer/announcing-aws-cloud-development-kit-v2-developer-preview/) blog

**Comment by hnishar** [comment]
CDK & Solutions Constructs v2 is now GA

https://github.com/awslabs/aws-solutions-constructs/releases/tag/v2.0.0
