### ISSUE TITLE
Lambda function is not reusable for OpenApiGatewayToLambda

### ISSUE THREAD

**Issue by adminy** [awslabs/aws-solutions-constructs#1191]
when I try to reuse a lambda function in `OpenApiGatewayToLambda` constructor via `existingLambdaObj`, I get an error relating to https://github.com/awslabs/aws-solutions-constructs/blob/9315c9324cb902a50b852a4d61dbb17f8573e2a7/source/patterns/%40aws-solutions-constructs/aws-openapigateway-lambda/lib/index.ts#L215

as this permission is added for every lambda but cdk would create it over and over again with the same name and it has an expectation of it to be unique.

**Comment by biffgaut** [comment]
Just to clarify as we dive deeper - you are sharing a Lambda function between 2 openapigateway-lambda constructs?

**Comment by biffgaut** [comment]
We've  implemented the fix for this, it should be published to the various repositories this evening.

**Comment by adminy** [comment]
thank you.

**Comment by biffgaut** [comment]
v2.71.0 includes this fix
