### ISSUE TITLE
Sqs lambda doesn't work for FIFO queue

### ISSUE THREAD

**Issue by mmuller88** [awslabs/aws-solutions-constructs#12]
The aws-sqs-lambda pattern fails if you want to use a fifo sqs queue as the documentation says that the name of the queue needs to end with .fifo https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html . But as the dead letter queue is applied too and gets the same name when you use the queueProps parameter. https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/aws-sqs-lambda/lib/index.ts#L51

One easy fix would be to create dlqueueProps . I created a PR: https://github.com/awslabs/aws-solutions-constructs/pull/13

### Reproduction Steps

Apply:

```TypeScript
    const sqsToLambda = new SqsToLambda(scope, 'SqsToLambda', {
      deployLambda: false,
      existingLambdaObj: this.executerLambda,
      queueProps: {
        queueName: `${scope.stackName}.fifo`,
        fifo: true,
      },
    });
```

### Error Log

9/61 | 1:58:45 PM | UPDATE_FAILED        | AWS::SQS::Queue                   | SqsToLambda/queue (SqsToLambdaqueueE6C100FE) AlfInstancesStackEuWest1Dev.fifo already exists in stack arn:aws:cloudformation:eu-west-1:981237193288:stack/AlfInstancesStackEuWest1Dev/3e9fb030-baae-11ea-8a64-0abd335268a4
	new Queue (/home/travis/build/mmuller88/alf-cdk/node_modules/@aws-solutions-constructs/core/node_modules/@aws-cdk/aws-sqs/lib/queue.js:48:23)
	\_ Object.buildQueue (/home/travis/build/mmuller88/alf-cdk/node_modules/@aws-solutions-constructs/core/lib/sqs-helper.js:38:12)
	\_ new SqsToLambda (/home/travis/build/mmuller88/alf-cdk/node_modules/@aws-solutions-constructs/aws-sqs-lambda/lib/index.js:51:34)
	\_ new AlfCdkLambdas (/home/travis/build/mmuller88/alf-cdk/lib/AlfCdkLambdas.js:141:29)
	\_ new AlfInstancesStack (/home/travis/build/mmuller88/alf-cdk/index.js:13:25)
	\_ Object.<anonymous> (/home/travis/build/mmuller88/alf-cdk/index.js:89:1)
	\_ Module._compile (internal/modules/cjs/loader.js:1138:30)
	\_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
	\_ Module.load (internal/modules/cjs/loader.js:986:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:879:14)
	\_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
	\_ internal/main/run_main_module.js:17:47

### Environment

  - **CDK CLI Version      : 1.47
  - **AWS Solutions Constructs Version     : 1.47

### Other
My current workaround is to disable the deadletter queue with

deployDeadLetterQueue: false

--- 

This is :bug: Bug Report

**Comment by hnishar** [comment]
mmuller88@ Thanks for the contribution, the PR has been merged in v1.48.0
