### ISSUE TITLE
NestedStack usability

### ISSUE THREAD

**Issue by ZakHargz** [awslabs/aws-solutions-constructs#120]
I'm looking to extend the core/vpc_helper.ts construct to be reusable across various AWS accounts in my organisation.  Am I able to include this inside a NestedStack?

I've tried in the past but often get 'Cannot consume a cross reference from stack'.

Many thanks

**Comment by purplebari** [comment]
I not sure I understand what you mean by:

>be reusable across various AWS accounts in my organisation

**Comment by ZakHargz** [comment]
Hey - I've just read this back and I certainly didn't explain well!

We're looking at creating a library of items which extends the generic '@aws-cdk/*' constructs.  An example of this would be to import '@aws-cdk/aws-ec2' and have a simple Vpc that has been tailed to our specific needs.  We'd like to distribute this as a NPM module for other teams to use - We would have an interface to require certain values such as `cidr` and `maxAzs`. 

Unfortunately we've tried this, but we keep running into the issue of:

`Error: Stack "Stack B" cannot consume a cross reference from stack "Stack A". Cross stack references are only supported for stacks deployed to the same environment or between nested stacks and their parent stack
`

Stack A has the NPM module imported such as:

`        const isolatedVpc = new BaseIsolatedVpc(this, id, {
            vpcCidr: "*.*.*.*/*",
            maxAzs: 2
        });
        this.isolatedVpc = isolatedVpc
`

We then pass the `isolatedVpc` into stack B (passed in via props)

When we try and synth, we run into the cross-stack issue.  If I remove the module and set this up as `ec2.Vpc` it works fine.  The thing to note, Stack A and Stack B are NestedStacks of said parent (where we include both imports and their given props).

I'm curious if the following contructs in this repo would fix the issue, or would I need to re-think my scenario.

Thanks,

**Comment by biffgaut** [comment]
I don't think that the vpc-helper.ts file does anything that addresses the issue you are facing.

What _might_ work is sharing the VPC via an identifier rather than as a CDK object. Pass the VPC id into stack B, then obtain an IVpc interface using the [fromLookup](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Vpc.html#static-fromwbrlookupscope-id-options) method.

You ability to change an IVpc is less than that of a VPC interface, plus you want to watch out for all the usual CloudFormation issues of changing one stack from another.

Hope this helps.

**Comment by ZakHargz** [comment]
Ah okay, I see what you mean.  Is there a way to get around me updating the Vpc that is an isolated stack but has exported outputs used by other stacks?

Thanks

**Comment by biffgaut** [comment]
I think that all depends upon your use case. Getting the VPC from the other stack using fromResource() does not attempt to update the VPC. At that point you should be able to launch new EC2 instances into the VPC, or set up some flavor of ELB, etc. If you try to something like change the enableDnsHostnames setting you will probably run into trouble. Off the top of my head, I'm not sure what would happen if you tried to create new subnets - that might be possible.

But the best course would be to ensure that the VPC you are sharing is set up correctly for any future stacks to use without update.

**Comment by biffgaut** [comment]
Auto closed after 14 days
