### ISSUE TITLE
ApiGatewayToSqs : add schema validation for create operation

### ISSUE THREAD

**Issue by KuntzOl** [awslabs/aws-solutions-constructs#1215]
It would be helpful to have schema validation made directly on the API Gateway when we do a creation operation.

**Comment by biffgaut** [comment]
We're looking into this, thanks for the suggestion.

**Comment by biffgaut** [comment]
This is addressed in PR 1216 and should be published to npm, etc. this weekend.

**Comment by biffgaut** [comment]
This is now available through the new messageSchema prop in v2.72.0
