### ISSUE TITLE
kinesisFirehoseProps type not defined

### ISSUE THREAD

**Issue by Rajivhost** [awslabs/aws-solutions-constructs#123]
Hi,

Can we have the kinesisFirehoseProps type defined as described on docs instead of any?

![image](https://user-images.githubusercontent.com/3539984/105570333-043c7980-5d49-11eb-86d3-ff013759de67.png)

Br,
Rajiv.

**Comment by Rajivhost** [comment]
Just checked this on source code.

![image](https://user-images.githubusercontent.com/3539984/105570418-a6f4f800-5d49-11eb-8747-e10047fbbc28.png)

**Comment by purplebari** [comment]
Adding "| any" is pretty standard throughout the constructs, as it allows clients to specify a subset of props values that may not include all required attributes. For CfnDeliveryStreamProps it seems that there are no required props, so we may not need the "| any" in this situation. We'll dig a little deeper an see if there any notes around why we have | any here and explore removing it. Thanks.
