### ISSUE TITLE
FargateToS3: Is it possible to disable and make it optional to add an interface/gateway endpoint to the VPC for S3?

### ISSUE THREAD

**Issue by princeanire** [awslabs/aws-solutions-constructs#1230]
Hi 
is it possible for the FargateToS3 solution construct to make it optional and disable the creation of interface/gateway endpoint to the VPC for S3 service when using the construct,

### Use Case

there are use cases and situations that S3 Interface endpoint and/or S3 Gateway is already created and added to the VPC before the solution construct is used - when deploying the cloudformatoin template the there would be an error as the rtb entity to s3 endpoint/s are already included or interface/gateway endpoint is already added before

### Proposed Solution

make adding an interface/gateway endpoint to the VPC optional but by default the solutions constructs adds the interface endpoint, so that the user can disable it in use cases that the s3 interface endpoint for s3 is already included before

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
Interesting topic. While looking into it, I notice 2 things:

* I can create 2 constructs with endpoints in the same VPC in my stack (I use aws-lambda-s3, but the VPC behavior should be the same.
* I can make it break by importing an existing VPC in the account that already has an S3 endpoint, but the error I see is not creating the actual endpoint, but a collision regarding the Route Table

Is this what you see?

**Comment by princeanire** [comment]
Yep, we encounter collision regarding the Route Table

it errors that a route entry to the S3 prefix list already exists - our workaround to this is that we manually delete the route table entry synthesized by our AWS cdk and then manually deploy it through cloudformation, manually process and we have to do this multiple times through our multiple deployments

**Comment by biffgaut** [comment]
I believe you are creating the construct correctly. There is a technique called [escape hatches](https://docs.aws.amazon.com/cdk/v2/guide/cfn_layer.html) that allow you to alter the behavior of a construct. If you can navigate the VPC at the L2 level to get to the L2 RouteTable construct, then use escape hatches to alter the RouteTable you might be able to avoid the issue. I'll also try to give that a try.

**Comment by princeanire** [comment]
Hey @biffgaut, thanks for bringing up escape hatches! It looks like this isn't really a feature request after all. The docs actually cover my situation pretty well, especially with the escape hatches. So, I'll go ahead and close this. Thanks again!
