### ISSUE TITLE
With CDK 2.0 alpha coming out, what are the plans for this library?

### ISSUE THREAD

**Issue by maria-jackson** [awslabs/aws-solutions-constructs#125]
Will this library adopt 2.0 or will there be a new library?

**Comment by biffgaut** [comment]
We talk regularly with the CDK team and will be releasing a version of Solutions Constructs compatible with CDK 2.0 when it goes to General Availability.

The current plan is that all code written with current Solutions Constructs will continue to work with a change in "import" statements.

**Comment by biffgaut** [comment]
Reopening this issue so interested parties can follow it. Any CDK 2.0 work is still a ways off however.

**Comment by hnishar** [comment]
CDK v2 is now in developer preview and we're looking into the best way to make Solutions Constructs work with CDK v2

**Comment by relm923** [comment]
Any update on this?

**Comment by hnishar** [comment]
relm923@ Still work in progress, hope to have something out there soon

**Comment by hnishar** [comment]
CDK & Solutions Constructs v2 is now GA

https://github.com/awslabs/aws-solutions-constructs/releases/tag/v2.0.0
