### ISSUE TITLE
Cannot find package @aws-solutions-constructs/aws-serverless-image-handler on npmjs.com

### ISSUE THREAD

**Issue by viliam-jobko** [awslabs/aws-solutions-constructs#128]
When trying to replicate code from https://github.com/awslabs/aws-solutions-constructs/tree/master/source/use_cases/aws-serverless-image-handler#aws-serverless-image-handler I found out that the package `@aws-solutions-constructs/aws-serverless-image-handler` cannot be installed. `npm` returns `npm ERR! 404 Not Found`.

### Reproduction Steps
Run `npm install @aws-solutions-constructs/aws-serverless-image-handler` or visit https://www.npmjs.com/package/@aws-solutions-constructs/aws-serverless-image-handler.

### Error Log

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@aws-solutions-constructs%2faws-serverless-image-handler - Not found
npm ERR! 404 
npm ERR! 404  '@aws-solutions-constructs/aws-serverless-image-handler@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2021-02-02T21_51_27_377Z-debug.log
```

### Environment

  - **CDK CLI Version      : not installed**
  - **CDK Framework Version: not installed**
  - **AWS Solutions Constructs Version     : not installed**
  - **OS                   : MacOS**
  - **Language             : TypeScript**

### Other

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Hello,

Thanks for your interest in AWS Solutions Constructs! Only the Constructs themselves are available in NPM, the sample use cases (such as aws-serverless-image-handler) are not. To work with the sample use cases  you should clone the GitHub repository and then navigate to the sample use case you want to explore.

Thanks
