### ISSUE TITLE
property `kinesisStreamRole` missing from aws-kinesisstreams-kinesisfirehose-s3

### ISSUE THREAD

**Issue by AlJohri** [awslabs/aws-solutions-constructs#129]
Based on this code here:

https://github.com/awslabs/aws-solutions-constructs/blob/2d8d538a79d5988d7db9a3f0c72dfa648fe0e869/source/patterns/%40aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/lib/index.ts#L73-L81

Looks like the `kinesisStreamRole` property is missing from the `KinesisStreamsToKinesisFirehoseToS3` construct.

### Environment

  - **CDK CLI Version      :** 1.85.0
  - **CDK Framework Version:** ?
  - **AWS Solutions Constructs Version     :** 1.85.0
  - **OS                   :** macOS 11.1
  - **Language             :** Typescript

--- 

This is :bug: Bug Report

**Comment by AlJohri** [comment]
The [README](https://github.com/awslabs/aws-solutions-constructs/tree/master/source/patterns/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3) seems to suggest this property should exist:

![Screen Shot 2021-02-11 at 11 43 51 AM](https://user-images.githubusercontent.com/2790092/107668293-82ac7d00-6c5e-11eb-8c2e-8e230c1f2f41.png)

**Comment by biffgaut** [comment]
Yep, from what you show here this looks like a bug. We will dive deeper and add it to our backlog - thanks!

**Comment by biffgaut** [comment]
Fixed and released
