### ISSUE TITLE
aws-kinesisstreams-kinesisfirehose-s3 does not return s3Bucket

### ISSUE THREAD

**Issue by beomseoklee** [awslabs/aws-solutions-constructs#133]
The `aws-kinesisstreams-kinesisfirehose-s3` pattern does not return `s3Bucket`. To get the S3 bucket or S3 bucket name created by the pattern, we should go this way instead:
```typescript
const kinesisStreamsToKinesisFirehoseToS3 = new KinesisStreamsToKinesisFirehoseToS3(this, 'TestPatter', {});
const kinesisFirehoseToS3 = kinesisStreamsToKinesisFirehoseToS3.node.findChild('KinesisFirehoseToS3');
const s3Bucket = <CfnBucket>kinesisFirehoseToS3.node.findChilde('S3Bucket');
const s3BucketName = s3Bucket.bucketName;
```

### Reproduction Steps

```typescript
const kinesisStreamsToKinesisFirehoseToS3 = new KinesisStreamsToKinesisFirehoseToS3(this, 'TestPatter', {});
const s3Bucket = kinesisStreamsToKinesisFirehoseToS3.s3Bucket;  // It's always `undefined`
const s3BucketName = s3Bucket.bucketName;
```

### Error Log

```
/node_modules/@aws-cdk/core/lib/cfn-output.ts:53
    this._value = value;
            ^
Error: Missing value for CloudFormation output at path "MyStack/MyDataBucket"
```

### Environment

  - **CDK CLI Version      :** 1.86
  - **CDK Framework Version:** Node v12.20.0
  - **AWS Solutions Constructs Version     :** 1.86
  - **OS                   :** Mac OS
  - **Language             :** TypeScript

### Other

I guess simply this would fix the bug because if there's no S3 bucket in the `aws-kinesisfirehose-s3` pattern, the `aws-kinesisstreams-kinesisfirehose-s3` would return `undefined` as well:
```typescript
this.s3Bucket = kdfToS3Construct.s3Bucket;
```

https://github.com/awslabs/aws-solutions-constructs/blob/3fd15e984943fe295690d8b0654d77157ffda8e3/source/patterns/%40aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/lib/index.ts#L135-L144

I'm willing to fix this bug, so please let me know.

--- 

This is :bug: Bug Report

**Comment by hnishar** [comment]
beomseoklee@ Thanks for the issue and finding the root cause, feel free to submit the PR

**Comment by biffgaut** [comment]
beomseoklee@ The newly clarified design guidelines also call for S3 logging bucket to be exposed as a property - it is, but it is also unset just like S3 bucket. Can you address that as well? Thanks.
