### ISSUE TITLE
Support IBucket for the existingBucketObj prop in the aws-cloudfront-s3 pattern

### ISSUE THREAD

**Issue by pohnemus** [awslabs/aws-solutions-constructs#139]
Support IBucket for the existingBucketObj prop in the [aws-cloudfront-s3](https://docs.aws.amazon.com/solutions/latest/constructs/aws-cloudfront-s3.html) pattern.

### Use Case

We have a few existing S3 buckets that are maintained outside of a CDK stack and we'd like to put CloudFront in front of them, ideally using the aws-cloudfront-s3 pattern. We were hopeful we could use the `existingBucketObj` prop in the [aws-cloudfront-s3](https://docs.aws.amazon.com/solutions/latest/constructs/aws-cloudfront-s3.html) pattern, however each of the methods available to import a bucket return an `IBucket` rather than a `Bucket` that the pattern expects - https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html#static-fromwbrbucketwbrarnscope-id-bucketarn.

### Proposed Solution

I'm not sure if this would be possible, but a change similar to what was completed in #33 seems like it would accomplish what we're after.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
Thanks - we'll take a look if it's possible. Often we require the the full construct (e.g. Bucket) rather than the Interface (e.g. - IBucket) because the Solutions Construct performs operations that aren't available through the Interface (usually because the operation can't be performed on a resource outside the stack). We'll look at the internals of the aws-cloudfront-s3 and see if that's the case here.

**Comment by mjdinsmore** [comment]
@biffgaut - In this case, using the Java API, the only way to get an existing Bucket in the CDK seems to be from the Bucket API:
`
IBucket iBucket = Bucket.fromBucketArn(scope, id, bucketArn);
`
There is no other option for getting a Bucket from an existing ARN or name that I am aware of.   That is why @pohnemus was requesting support for the IBucket.  This all seems to be related to the open is https://github.com/aws/aws-cdk/issues/2004 (with existing PR https://github.com/aws/aws-cdk/pull/11773)?

**Comment by biffgaut** [comment]
This is a bigger concern than just this construct - it would be a change of Design Guidelines to allow any existing bucket to be IBucket. We will research across the constructs if this is feasible and report back.
