### ISSUE TITLE
Wrong module names

### ISSUE THREAD

**Issue by moltar** [awslabs/aws-solutions-constructs#14]
https://github.com/awslabs/aws-solutions-constructs/tree/master/source/patterns/%40aws-solutions-constructs/aws-sqs-lambda

`aws_solutions_constructs.aws_sns_lambda`

s/sns/sqs/

**Comment by hnishar** [comment]
moltar@ Good catch, thanks for the feedback, it will be corrected in the next release!

**Comment by hnishar** [comment]
This has been fixed in the latest release v1.49.0
