### ISSUE TITLE
Argument of type 'this' is not assignable to parameter of type 'Construct'.

### ISSUE THREAD

**Issue by moltar** [awslabs/aws-solutions-constructs#15]
Getting the following TS error:

```
Argument of type 'this' is not assignable to parameter of type 'Construct'.
  Type 'AppStack' is not assignable to type 'Construct'.
    Property 'onValidate' is protected but type 'Construct' is not a class derived from 'Construct'.ts(2345)
```

### Reproduction Steps

```
    new SqsToLambda(this, 'CurrencyWorker', {
      existingLambdaObj: testFunction,
    })
```

Using latest CDK packages.

Maybe your packages are out of date?

Thanks.

**Comment by cynicaljoy** [comment]
Ever time I've seen this with CDK it's because I was using a mix-mash of module versions. Can you validate that all of the CDK based modules in your `package.json` are you using `1.46.0`?

**Comment by moltar** [comment]
I'm actually using `1.50.0`. I was urged by CDK CLI to upgrade today 🤷‍♂️ 

```sh
grep cdk package.json
```

```
    "@aws-cdk/aws-ec2": "1.50.0",
    "@aws-cdk/aws-iam": "1.50.0",
    "@aws-cdk/aws-lambda": "1.50.0",
    "@aws-cdk/aws-lambda-destinations": "1.50.0",
    "@aws-cdk/aws-lambda-event-sources": "1.50.0",
    "@aws-cdk/aws-rds": "1.50.0",
    "@aws-cdk/aws-sqs": "1.50.0",
    "@aws-cdk/core": "1.50.0",
    "@aws-cdk/assert": "1.50.0",
    "aws-cdk": "1.50.0",
```

**Comment by hnishar** [comment]
moltar@, cynicaljoy@ is correct, the versions of @aws-cdk/* modules must match the version of @aws-solutions-constructs/* modules, or else you will see that error, currently the latest version for @aws-solutions-constructs/* modules is 1.48.0, use that for @aws-cdk/* modules and it should work!

**Comment by moltar** [comment]
Do you have a policy for upgrades? Any idea when this repo will be in sync with latest cdk package versions?

CDK CLI urged me to upgrade. It was in scary orange colour. I didn’t look into it, assuming there was a critical update. Figured there’s no harm in upgrading.

**Comment by hnishar** [comment]
moltar@, We try to refresh the patterns with the latest CDK versions as quickly as possible. That being said, the CDK CLI version can be different from the "dependencies" in package.json. As long as the version numbers in package.json dependencies match up, you should not see the error. 

For example, CDK CLI v1.51.0 and package.json dependencies v1.48.0 will work just fine!

**Comment by hnishar** [comment]
moltar@ v1.50.0 is now released!

**Comment by moltar** [comment]
> We try to refresh the patterns with the latest CDK versions as quickly as possible

Maybe Renovate Bot with auto merge for PRs for "cdk" family of packages would be a good solution?

If you trust your test coverage.

It reacts pretty quickly, in under an hour, usually. Then tests pass, and PR might take another couple of hours to get closed.

> That being said, the CDK CLI version can be different from the "dependencies" in package.json

That's good to know, thanks!

> moltar@ v1.50.0 is now released!

🎉  thanks!

**Comment by hnishar** [comment]
Good suggestion! thanks!
