### ISSUE TITLE
LambdaSqs java contains the wrong classes in version 1.91.0

### ISSUE THREAD

**Issue by niqo01** [awslabs/aws-solutions-constructs#150]
I upgraded `software.amazon.awsconstructs:lambdasqs` in my java project from version `1.90.0` to `1.91.0`
Using the new version my java cdk project does not compile anymore due to failing imports.
After investigating I saw that the content of the library does not contains the proper classes. See screenshot below.

### Error Log

![lambdasqs](https://user-images.githubusercontent.com/1121251/111710267-efdba100-880e-11eb-84bc-c36e78904f55.png)

### Environment

  - **CDK CLI Version      : 1.94.1
  - **CDK Framework Version: 1.94.1
  - **AWS Solutions Constructs Version     : 1.91.0
  - **OS                   : Ubuntu
  - **Language             : Java

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Thanks, we'll take a look.

One issue I see - you must use the same version of the CDK and Solutions Constructs. So if you are using 1.91.0 of Solutions Constructs then you should also be using version 1.91.0 of the CDK.

Once you've addressed that, if you're still seeing the error, could you run `jar tf lambdasqs-1.91.0.jar` and post the contents of the jar file on your disk? Thanks.

**Comment by biffgaut** [comment]
We've found the error - looking for a fix. Although you still want to sync your framework and Constructs versions.

**Comment by biffgaut** [comment]
We just released 1.92.0, we believe it fixes the issue.
