### ISSUE TITLE
Construct KinesisStreamsToLambda in Java generates props as Object 

### ISSUE THREAD

**Issue by drissamri** [awslabs/aws-solutions-constructs#157]
The `KinesisStreamsToLambda` construct has a `KinesisStreamsToLambdaProps` on which you can set `kinesisEventSourceProps`. 

This field is generated as `Object` in Java which seems like a bug? 
`private java.lang.Object kinesisEventSourceProps;` 

Shouldn't this be a class just like the other props?
```
 new KinesisStreamsToLambda(this, "paymentStream",
    KinesisStreamsToLambdaProps.builder()
       .kinesisStreamProps(StreamProps.builder().build())
       .kinesisEventSourceProps(<<THIS IS NOT TYPED>>)
       .build());
```
```
private java.lang.Object kinesisEventSourceProps;
private software.amazon.awscdk.services.kinesis.StreamProps kinesisStreamProps;
private software.amazon.awscdk.services.lambda.FunctionProps lambdaFunctionProps;
```

**Comment by biffgaut** [comment]
Thanks, we'll check it out.

**Comment by drissamri** [comment]
Is there any workaround that can be used until this is fixed?

**Comment by biffgaut** [comment]
This appears to be an issue with how JSII translates our Typescript constructs into Java. The pattern of using `EventSourceProps | any` in Typescript allows users to provide a subset of properties that does not include properties that might otherwise be required. This pattern, used in several places throughout Solutions Constructs, is what causes the non-typed argument that prevents you from using the Builder pattern. We're looking into it, but have no ETA on a solution or workaround.

**Comment by biffgaut** [comment]
Ha! Sometimes no ETA means sooner rather than later!

You can build the props object outside of building the construct and pass it as an argument. This code compiles and deploys the construct (your details such as where the Lambda function resides may vary):


```
    public JavaClientStack(final Construct parent, final String id, final StackProps props) {
        super(parent, id, props);
        
        // Defines a new lambda resource
        final Function hello = Function.Builder.create(this, "HelloHandler")
            .runtime(Runtime.NODEJS_14_X)    // execution environment
            .code(Code.fromAsset("lambda"))  // code loaded from the "lambda" directory
            .handler("index.handler")        // file is "hello", function is "handler"
            .build();
            
        final KinesisEventSourceProps _props = KinesisEventSourceProps.builder()
                .startingPosition(StartingPosition.LATEST)
                .batchSize(5)
                .build();
                
        KinesisStreamsToLambda.Builder.create(this, "paymentStream")
            .existingLambdaObj(hello)
            .kinesisEventSourceProps(_props)
            .build();
    }
```
