### ISSUE TITLE
S3ToStepFunction should start Step also for MultipartComplete

### ISSUE THREAD

**Issue by sannies** [awslabs/aws-solutions-constructs#159]
S3ToStepFunction is only triggered for PutObject but not on CompleteMultipartUpload. You should include the later, too. I can't imagine a use-case that specifically targets PutObject upload only.  

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
Good point - I'll run it by the team, then perhaps take you up on your offer to the change yourself.😃
