### ISSUE TITLE
aws-kinesisstreams-gluejob: Unknown Classification, classification instead set as table property

### ISSUE THREAD

**Issue by FinnIckler** [awslabs/aws-solutions-constructs#184]
When you create a Glue Table using the KinesisstreamToGlue Job Construct, the classification is set to unknown. Instead, a table property "classification" : "json" is set.  

Here is a screenshot of the resulting stream  
<img width="660" alt="Screenshot 2021-05-18 at 18 06 01" src="https://user-images.githubusercontent.com/10168980/118701614-3603af80-b814-11eb-806e-bc144037b92b.png">

### Reproduction Steps

I created this with an existing stream, but I am not sure if this is what caused the bug, or if it also would be there without it.

```
SCHEMA: glue.CfnTable.ColumnProperty = [
    {
        "name": "user",
        "type": "string",
        "comment": "Name of the user"
    },
    {
        "name": "package_id",
        "type": "string",
        "comment": "A unique package id"
    },
    {
        "name": "product_id",
        "type": "int",
        "comment": "A list of product ids that are in the package"
    },
    {
        "name": "origin",
        "type": "string",
        "comment": "Which FC the package came from"
    },
    {
        "name": "destination",
        "type": "string",
        "comment": "The address where the package is delivered to"
    },
    {
        "name": "weight",
        "type": "float",
        "comment": "The weight of the package"
    }
]

input_data_stream = kinesis.Stream(self, "input-stream", stream_name="input-data-stream",
                                                shard_count=2,
                                                retention_period=core.Duration.hours(24))

streaming_job = KinesisstreamsToGluejob(self, "streaming-job", glue_job_props={"command": {
            "name": "gluestreaming",
            "pythonVersion": "3",
            "scriptLocation": assets.Asset(self, "SparkCode", path="spark_code/transform.py").s3_object_url,
        }}, field_schema=SCHEMA, existing_stream_obj=input_data_stream)
```

### Error Log

I can't execute any jobs on the table as the classification is set to unknown

### Environment

  - **CDK CLI Version      :1.104
  - **CDK Framework Version:1.99
  - **AWS Solutions Constructs Version     :1.99
  - **OS                   :MacOs
  - **Language             :Python

### Other

--- 

This is :bug: Bug Report

**Comment by FinnIckler** [comment]
This might be a glue issue, speaking to the service team about this.

**Comment by biffgaut** [comment]
Thanks - let us know what you hear.
