### ISSUE TITLE
aws-lambda-sqs

### ISSUE THREAD

**Issue by lobobinario** [awslabs/aws-solutions-constructs#186]
Let the user to choose to use lambda environment variable (SQS_QUEUE_URL) or not, allowing to override it using lambdaFunctionProps object.

### Use Case

Sometime you code your lambda to use lambda name or any other request to retrieve the SQS QueueUrls. In that case you wouldn't need to have the parameter SQS_QUEUE_URL. Currently there is no option to override it and avoiding to create a environment variable that won't be used.
In the current use case, the environment var creation is mandatory

### Proposed Solution

Allow environment var independency. Let to override the lambda environment variable allowing a the user to decide if using an environment variable tied to the lambda to resolve sqs url or make it by lambda code itself.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
Thanks for the suggestion. We recommend using Environment Variables to supply environment specific information such as identifying info for other services such as queues. If you have a use case where you must use some other mechanism and the existence of the unused environment variable is forbidden, you can use the CDK Escape Hatch to remove the environment variable.

```
import * as cdk from '@aws-cdk/core';
import * as lambda from '@aws-cdk/aws-lambda';
import { LambdaToSqs, LambdaToSqsProps } from '@aws-solutions-constructs/aws-lambda-sqs';

export class Issue186Stack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const lambdaToSqs = new LambdaToSqs(this, 'lambdaToSqs', {
      lambdaFunctionProps: {
         code: lambda.Code.fromAsset(`lambda`),
         runtime: lambda.Runtime.NODEJS_14_X,
         handler: 'index.handler'
      },
    });

    // Escape Hatch code to delete Environment Variable
    const cfnFunction = lambdaToSqs.lambdaFunction.node.defaultChild as lambda.CfnFunction;
    cfnFunction.addPropertyDeletionOverride('Environment.Variables.SQS_QUEUE_URL');

  }
}
```

**Comment by lobobinario** [comment]
Thanks!
The workaround did the job.
