### ISSUE TITLE
Add "QueueWithDLQ" construct

### ISSUE THREAD

**Issue by mike24zl** [awslabs/aws-solutions-constructs#19]
I would like to contribute a "QueueWithDLQ" construct.

### Use Case
Queue + DLQ is a very common practice and I think it is almost always desired.
This construct will reduce boiler plate code in most cases and standardise this common practice.

### Proposed Solution
A (fairly simple) extension to the Queue construct

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hnishar** [comment]
mike24zl@ The focus of 'aws-solutions-constructs' library is multi-service patterns involving two or more services (resources). That being said, the SQS pattern 'aws-sqs-lambda' by default deploys the main Queue + DLQ, for details see [here](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/aws-sqs-lambda/lib/index.ts#L88) and [here](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/core/lib/sqs-helper.ts#L35)

**Comment by hnishar** [comment]
Closing the issue as the requested feature is already covered by the existing -sqs- patterns.
