### ISSUE TITLE
Split Service defaults from core and utility.

### ISSUE THREAD

**Issue by bluedoors** [awslabs/aws-solutions-constructs#2]
I propose moving the Service defaults out of `core` and into a `defaults` package to enable “swapping in” more scoped-down and customized defaults sets for customer-specific implementations. May also provide some organizational benefits as the solution scales up the number of patterns in the library

### Use Case

Thinking broadly across customers I work with I’d expect that overriding the core service defaults on a per customer basis would be a likely use case (especially with Enterprise customers that typically go through a process of allowing Services to be used within the organisation along with a set of specified default configurations to meet their security control position). Ideally 'aws-solutions-constructs' would evolve to support this model? Perhaps the service defaults are moved out of 'core' and into a 'defaults' package? Then each customer would just need to have their own version of the defaults as appropriate. This would allow 'aws-solutions-constructs' to add more ‘core’ functionality and utility function that could be picked up on next pull but not impact any service defaults.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hnishar** [comment]
The whole purpose of `core` package is to setup the sensible defaults for each resource e.g. S3 bucket, Lambda function, Cloudfront WebDistribution, etc in addition to what's already setup by respective CDK L2 constructs. Additionally it provides an `override` functionality for users to input the construct props to override the defaults. One possible way to support the use case would be to fork the repo and customize the `core` module to meet specific customer requirements, with a periodic sync from the repo to consume new features and bug fixes, and possibly contribute back (via PR) any defaults that can be generalized and be applicable to other customers.

**Comment by hnishar** [comment]
Closing the issue, feel free to re-open if you have any follow-up questions.
