### ISSUE TITLE
Ability to customize the bucket_props for the logging S3 bucket created by the "aws-s3-lambda" construct

### ISSUE THREAD

**Issue by johnculkin** [awslabs/aws-solutions-constructs#213]
I have the following specified in bucket_props but it is only being respected by the main bucket. 

```
            bucket_props=aws_s3.BucketProps(
                removal_policy=core.RemovalPolicy.DESTROY,
                auto_delete_objects=True            )
```

When I destroy my stack, the logging bucket remains. 

### Use Case

I would like this feature so that I can completely remove all resources created by my stack during testing deploy/destroys. 

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
This seems to make a lot of sense, it's similar to allowing clients to define properties for the Dead Letter Queue in construct using SQS. It would involve changing the [Design Guidelines](https://github.com/awslabs/aws-solutions-constructs/blob/main/DESIGN_GUIDELINES.md) - which means changing the interface for all constructs using an S3 bucket. We will add it to our backlog.

**Comment by leftiness** [comment]
By default, the logging bucket remains. If you provide `removal_policy=RemovalPolicy.DESTROY`, then cdk destroy crashes because `auto_delete_objects=True` doesn't get passed through to `createLoggingBucket()`.

https://github.com/awslabs/aws-solutions-constructs/blob/5411ab73301f85ff7a5df1e6425996e2c6e8ffb5/source/patterns/%40aws-solutions-constructs/core/lib/s3-bucket-helper.ts#L129

```
The bucket you tried to delete is not empty. You must delete all versions in the bucket. (Service: Amazon S3; Status Code: 409; Error Code: BucketNotEmpty; Request ID: G1WEE
X8WN96MV103; S3 Extended Request ID: UUFyUDyUCxcb4F2+zFUXRUEtTvmaESEcgVEMxgaZVJeiBHIlemyV5sw3iFM6gI/xoKIMg+Nkls8=; Proxy: null)

	new Bucket (/tmp/jsii-kernel-mGKkbF/node_modules/@aws-cdk/aws-s3/lib/bucket.js:573:26)
	\_ createLoggingBucket (/tmp/jsii-kernel-mGKkbF/node_modules/@aws-solutions-constructs/core/lib/s3-bucket-helper.js:58:27)
	\_ s3BucketWithLogging (/tmp/jsii-kernel-mGKkbF/node_modules/@aws-solutions-constructs/core/lib/s3-bucket-helper.js:105:25)
	\_ Object.buildS3Bucket (/tmp/jsii-kernel-mGKkbF/node_modules/@aws-solutions-constructs/core/lib/s3-bucket-helper.js:24:16)
	\_ new LambdaToS3 (/tmp/jsii-kernel-mGKkbF/node_modules/@aws-solutions-constructs/aws-lambda-s3/lib/index.js:50:62)
	\_ /tmp/tmp17p01pu4/lib/program.js:8154:58
	\_ Kernel._wrapSandboxCode (/tmp/tmp17p01pu4/lib/program.js:8582:24)
	\_ Kernel._create (/tmp/tmp17p01pu4/lib/program.js:8154:34)
	\_ Kernel.create (/tmp/tmp17p01pu4/lib/program.js:7895:29)
	\_ KernelHost.processRequest (/tmp/tmp17p01pu4/lib/program.js:9479:36)
	\_ KernelHost.run (/tmp/tmp17p01pu4/lib/program.js:9442:22)
	\_ Immediate._onImmediate (/tmp/tmp17p01pu4/lib/program.js:9443:46)
	\_ processImmediate (internal/timers.js:462:21)
```

**Comment by biffgaut** [comment]
In progress by suthjare

**Comment by biffgaut** [comment]
LInked to:
[#375](https://github.com/awslabs/aws-solutions-constructs/issues/375) 
[#394](https://github.com/awslabs/aws-solutions-constructs/issues/394)
