### ISSUE TITLE
New Pattern: Custom Resource - run ECS task

### ISSUE THREAD

**Issue by moltar** [awslabs/aws-solutions-constructs#22]
A custom resource that runs an ECS task during the deployment.

### Use Case

The use case I have right now is database schema migrations.

I'm running a Fargate Task to perform the migration.

### Proposed Solution

Custom resource that triggers a Lambda function, which uses `aws-sdk` to run an ECS task.

### Other

There is quite a bit of wiring and things to figure out and get right.

Would be worth having it centralized and can also provide learning material for other Custom Resource implementations.

I have some code for this, but I am no AWS expert, but I can share whatever I got.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by flochaz** [comment]
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_custom-resources.AwsSdkCall.html might already do what you want.

**Comment by moltar** [comment]
An interesting approach indeed. But there seems to be a bug?

```
2020-07-27T11:00:23.702Z	9a6794e8-bb58-48f0-be12-b2a5bd441723	INFO	Installing latest AWS SDK v2
npm WARN enoent ENOENT: no such file or directory, open '/tmp/package.json' 

/bin/sh: tree: command not found 

2020-07-27T11:00:55.980Z	9a6794e8-bb58-48f0-be12-b2a5bd441723	INFO	Failed to install latest AWS SDK v2: Error: Command failed: tree /tmp/node_modules
/bin/sh: tree: command not found
```

**Comment by moltar** [comment]
But the FN still ran successfully... So I guess it has no effect on the outcome. But it is weird that it is even trying to install `aws-sdk` and then calling `tree` for some reason. Why would it do that?

**Comment by hnishar** [comment]
Also, please check in the main CDK repo package [aws-ecs-patterns](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-ecs-patterns) to see if it has what you're looking for ?

**Comment by hnishar** [comment]
Closing the issue, feel free to re-open if you have any follow-up questions.
