### ISSUE TITLE
Stepfunction vended log group name

### ISSUE THREAD

**Issue by knihit** [awslabs/aws-solutions-constructs#230]
### Reproduction Steps

When using the following code:

            const lambdaStepFunction = new LambdaToStepFunction(this, 'WorkflowEngine', {
                existingLambdaObj: props.lambdaFunc,
                stateMachineProps: {
                    definition: props.chain,
                    ...(props.stateMachineType === StateMachineType.EXPRESS && {
                        stateMachineType: props.stateMachineType
                    })
                }
            });

the construct creates the a /aws/vended log group whose name is consistent across deployments. Hence when the stack is deleted and recreated again (and since the log policy is 'Retain'), the Cloudformation template fails deployment because the log group exists. Is this by design. I see that the code internally calls 'getResourceName' which uses a SHA256 hash to create the name.

I passed my own logs that I created, but the vended logs created by the construct are created anyways.

        const logGroup = new LogGroup(scope, 'StMacLogGroup', {
            logGroupName: `/aws/vendedlogs/${this.node.id}-${props.uuid}/`,
            retention: RetentionDays.INFINITE,
        });
 
        (logGroup.node.defaultChild as CfnLogGroup).cfnOptions.metadata = {
            cfn_nag: {
                rules_to_suppress: [{
                    id: 'W84',
                    reason: 'Log group data is always encrypted in CloudWatch Logs using AWS Managed KMS Key. For customers wanting to us CMK for '+
                        'CloudWatchLogs should customize the solution further to add encryption options'
                }, {
                    id: 'W86',
                    reason: 'Log Groups are set to \'Never Expire\'. Customers should customize the retention policy based on their organization\'s '+
                        'retention policies'
                }]
            }
        }

        const lambdaStepFunction = new LambdaToStepFunction(this, 'WorkflowEngine', {
            existingLambdaObj: props.lambdaFunc,
            stateMachineProps: {
                definition: props.chain,
                ...(props.stateMachineType === StateMachineType.EXPRESS && {
                    stateMachineType: props.stateMachineType
                }),
                logs: {
                    destination: logGroup,
                    level: LogLevel.ERROR,
                    includeExecutionData: false
                }
            }
        });

### UPDATE:
To add to the above, I have a wrapper class (https://github.com/awslabs/discovering-hot-topics-using-machine-learning/blob/main/source/lib/text-analysis-workflow/workflow-construct.ts), which calls this construct. This wrapper class is invoked twice to create two separate step functions but only one log group gets created in the CFN template.

### Error Log

Resource handler returned message: "Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"/aws/vendedlogs/states/discoveringhottopicsusingmachinelearningworkflowenginestatemachinelog9bc2fdd469d0"}' already exists." 

### Environment

  - **CDK CLI Version      :** 1.109.0
  - **CDK Framework Version:** 1.107.0
  - **AWS Solutions Constructs Version     :** 1.107.0
  - **OS                   :** MacOS, BigSur
  - **Language             :** Typescript, Node.

### Other

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Interesting - we'll take a look. Thanks.

**Comment by muktadadariya** [comment]
Team, Any update on this bug?

**Comment by biffgaut** [comment]
Nothing yet. The requirement that logs in for State Machines be prefaced with vendedlogs because of name length restrictions forces us to create the log names ourselves in a way that can be replicated (e.g. - we can't just randomize). How we do this and still keep the log names unique within and between stacks is a puzzle we haven't solved yet and haven't had an opportunity to dive deep into CDK code to see if they have a solution.

**Comment by biffgaut** [comment]
This was fixed in PR #922
