### ISSUE TITLE
Update to 1.110.0

### ISSUE THREAD

**Issue by naseemkullah** [awslabs/aws-solutions-constructs#234]
Update all cdk components to 1.110.0 which was just released

### Use Case

edit: I no longer have a hard use case for this. In general it's nice not to trail behind too many versions though for users who would want to use features that have since been introduced, so I will leave this open.

### Other

* [ ] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
Complete
