### ISSUE TITLE
New Pattern: aws-sns-sqs

### ISSUE THREAD

**Issue by hnishar** [awslabs/aws-solutions-constructs#24]
Add your +1 👍  to help us prioritize
--- 

## Overview:
This AWS Solutions Construct implements an Amazon SNS Topic connected to an Amazon SQS queue.

## User provided props for the construct:
* Either an existing instances of `sns.Topic` or `sns.TopicProps` to deploy new SNS topic
* Either an existing instances of `sqs.Queue` or `sqs.QueueProps` to deploy new SQS queue
* Optional `enableEncryption` to encrypt the SNS topic (default: true)
* Optional `encryptionKey` user provided encryption key
* Optional `deployDeadLetterQueue` to deploy the DLQ (default: true)
* Optional `deadLetterQueueProps` for the DLQ

## Default settings

Out of the box implementation of the Construct without any override will set the following defaults:

### Amazon SNS Topic
* Enable server-side encryption forSNS Topic using Customer managed KMS Key

### Amazon SQS Queue
* Configure least privilege access permissions for SQS Queue
* Deploy SQS dead-letter queue for the source SQS Queue.
* Enable server-side encryption for source SQS Queue using AWS Managed KMS Key.

**Comment by danielmatuki** [comment]
Hi @hnishar I'm available to contribute to implement this new pattern.

**Comment by hnishar** [comment]
Awesome! Thanks for reaching out and helping us out!
