### ISSUE TITLE
(cloudfront-to-s3) any in cloudfront distribution props type

### ISSUE THREAD

**Issue by naseemkullah** [awslabs/aws-solutions-constructs#247]
https://github.com/awslabs/aws-solutions-constructs/blob/7c5571365e44598bc8dff97038ab1ace0d9c7d94/source/patterns/%40aws-solutions-constructs/aws-cloudfront-s3/lib/index.ts#L41

The `| any` can throw users off, e.g. mistakenly configure `functionAssociations` at the top level where it should be nested in `defaultBehavior` (or an additional behaviour) to associate it to the CloudFront distribution.

If agreed upon I can submit a PR removing the `| any` from the CloudFront distribution props type.

**Comment by biffgaut** [comment]
We agree with the risk of | any, but made a conscious decision to include it anyway. Without | any, users could not override a single property value without re-specifying every required property attribute. This would make the constructs significantly harder to use and less flexible. Our design decision was that the flexibility outweighed the risk.

**Comment by naseemkullah** [comment]
Could [Partial](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype)<cloudfront.DistributionProps> not be used instead?

**Comment by naseemkullah** [comment]
https://github.com/awslabs/aws-solutions-constructs/issues/250 opened to continue discussion
