### ISSUE TITLE
New Pattern: aws-events-rule-sqs

### ISSUE THREAD

**Issue by deolank** [awslabs/aws-solutions-constructs#25]
### Overview:
This AWS Solutions Construct implements an a CloudWatch Events rule which sends events to a new or an existing SQS queue.

### User provided props for the construct:
Either an existing instances of CloudWatch Events rule or CWEventsrule.Props to deploy new CW Events rule.
Either an existing instances of sqs.Queue or sqs.QueueProps to deploy new SQS queue
Optional enableEncryption to encrypt the SQS queue (default: true)
Optional encryptionKey user provided encryption key

### Default Settings:

CloudWatch Events Rule:
Create a CloudWatch Events rule to send events to SQS queue

Amazon SQS Queue
Configure least privilege access permissions for SQS Queue
Enable server-side encryption for source SQS Queue using AWS Managed KMS Key.

**Comment by hnishar** [comment]
deolank@ This will be a good candidate for a new pattern, please check the existing events-rule pattern before implementing this one, e.g. [aws-events-rule-lambda](https://github.com/awslabs/aws-solutions-constructs/tree/master/source/patterns/%40aws-solutions-constructs/aws-events-rule-lambda)

**Comment by gockle** [comment]
@hnishar I will creating a PR for this feature.

**Comment by hnishar** [comment]
This has been pushed out in the latest release v1.62.0
