### ISSUE TITLE
Allow passing sqsEventSourceProps into LambdaToSqsToLambda

### ISSUE THREAD

**Issue by Garethp** [awslabs/aws-solutions-constructs#263]
The `SqsToLambda` construct [allows you to pass in sqsEventSourceProps](https://github.com/awslabs/aws-solutions-constructs/blob/main/source/patterns/%40aws-solutions-constructs/aws-sqs-lambda/lib/index.ts#L72) but for some reason you can't use those props in [`LambdaToSqsToLambda`](https://github.com/awslabs/aws-solutions-constructs/blob/main/source/patterns/%40aws-solutions-constructs/aws-lambda-sqs-lambda/lib/index.ts) even though [it uses `SqsToLambda`](https://github.com/awslabs/aws-solutions-constructs/blob/main/source/patterns/%40aws-solutions-constructs/aws-lambda-sqs-lambda/lib/index.ts#L129) in it's implementation

### Use Case

Use cases include using `LambdaToSqsToLambda` but wanting to control your `batchSize` or other properties

### Proposed Solution

Add 

```ts
    /**
     * Optional user provided properties for the dead letter queue
     *
     * @default - Default props are used
     */
    readonly sqsEventSourceProps?: SqsEventSourceProps
```

to [`LambdaToSqsToLambdaProps`](https://github.com/awslabs/aws-solutions-constructs/blob/main/source/patterns/%40aws-solutions-constructs/aws-lambda-sqs-lambda/lib/index.ts#L25) and pass it through to [the constructor properties of `SqsToLambda`](https://github.com/awslabs/aws-solutions-constructs/blob/main/source/patterns/%40aws-solutions-constructs/aws-lambda-sqs-lambda/lib/index.ts#L129)

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
Thanks - we'll take a look.
