### ISSUE TITLE
New Pattern: aws-wafv2-appsync

### ISSUE THREAD

**Issue by Rajivhost** [awslabs/aws-solutions-constructs#265]

**Comment by biffgaut** [comment]
We're not seeing a lot of demand for appsync constructs yet, so with limited resources we will put this in our backlog until we see demand.

**Comment by harunhasdal** [comment]
I am happy to pick this one

**Comment by biffgaut** [comment]
Ah - I see your PR. I'll take a look - the nature of wafwebacl constructs requiring an already instantiated AppSync CDK construct reduces the risk of an eventual AppSync->(some target) construct since there is really no AppSync interface on this construct, so this may work out. The PR looks pretty complete with integration and unit tests - we appreciate that!

**Comment by harunhasdal** [comment]
> how would you feel about an AppSync construct with more functionality, such as appsync- dynamodb?

I'd be interested to look into it, as part of a new feature. I'll check what the progress is for L2 constructs for AppSync GraphQL APIs. Maybe we can look at a pattern similar to what Amplify GraphQL APIs do, e.g. appsync - lambda - dynamodb

**Comment by harunhasdal** [comment]
Looking at [AWS CDK appsync alpha docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-appsync-alpha-readme.html ), there is already an L2 construct in the works which provides adding a dynamodb datasource as well.

**Comment by biffgaut** [comment]
As our WAF interface is all L1 constructs, that makes the inclusion of L1 AppSync constructs less concerning. If someone wants to use the Experimental AppSync construct, it should be straightforward to pull the L1 construct out of the L2 construct. If they include DynamoDB functionality (hey - are they in our lane? :-), then this construct with the Alpha construct starts to become a big hunk of a solution.

**Comment by biffgaut** [comment]
(oops - wrong button...)

**Comment by biffgaut** [comment]
I believe the aws-wafwebacl-appsync construct addresses this issue.
