### ISSUE TITLE
New Pattern: aws-s3-sqs

### ISSUE THREAD

**Issue by hnishar** [awslabs/aws-solutions-constructs#27]
Add your +1 👍  to help us prioritize
--- 

## Overview:
This AWS Solutions Construct implements an AWS S3 Bucket that is configured to send notifications to a queue and an Amazon SQS queue

## User provided props for the construct:
* Either an existing instances of `s3.Bucket` or `s3.BucketProps` to deploy new S3 Bucket
* Either an existing instances of `sqs.Queue` or `sqs.QueueProps` to deploy new SQS queue
* Optional `deployDeadLetterQueue` to deploy the DLQ (default: true)
* Optional `deadLetterQueueProps` for the DLQ

## Default settings

Out of the box implementation of the Construct without any override will set the following defaults:

### Amazon S3 Bucket
* Configure Access logging for S3 Bucket
* Enable server-side encryption for S3 Bucket using AWS managed KMS Key
* Turn on the versioning for S3 Bucket
* Don't allow public access for S3 Bucket
* Retain the S3 Bucket when deleting the CloudFormation stack

### Amazon SQS Queue
* Deploy SQS dead-letter queue for the source SQS Queue
* Enable server-side encryption for source SQS Queue using AWS Managed KMS Key

**Comment by danielmatuki** [comment]
Hi @hnishar I can help with this construct. Is there someone already working on it?
