### ISSUE TITLE
cdk deploy fails to build with "Cannot read property 'rules_to_suppress' of undefined" error for utils.js 

### ISSUE THREAD

**Issue by muktadadariya** [awslabs/aws-solutions-constructs#273]
### Environment

  - **CDK CLI Version      :**
  - **CDK Framework Version:**
  - **AWS Solutions Constructs Version     :**v1.111.0
<img width="1268" alt="Screen Shot 2021-07-23 at 4 25 25 PM" src="https://user-images.githubusercontent.com/26233332/126837806-d68a279d-9618-4193-b4ef-b94a3ed11f9b.png">

  - **OS                   :**Mac
  - **Language             :**js

### Other

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
We see this and are addressing it right now. We've implemented a fix, but are testing deployment of all the constructs before publishing to NPM. For now, please continue to use 1.110.1. We hope to publish 1.112.0 over the weekend.

**Comment by biffgaut** [comment]
We will push this to NPM, PyPi, etc. in the next 24 hours.

**Comment by biffgaut** [comment]
1.112.0 of AWS Solutions Constructs has been published to NPM, PyPi and Maven.

**Comment by muktadadariya** [comment]
Thank you Biff!! It is now working for me.
