### ISSUE TITLE
New Pattern: Consolidated Logging Bucket

### ISSUE THREAD

**Issue by mobri2a** [awslabs/aws-solutions-constructs#29]
The AWS Solutions Construct creates an encrypted S3 Bucket for access logging if it does not already exist.  Bucket is automatically set to that no public access is enabled, encrypted, and allows log service write access.

### User provided props for the construct

- Bucket name for the logging bucket
- Bucket for which access logging is to be enabled
- KMS key or SSE encryption

### Use Case

When deploying an s3 bucket it is a best practice to log access data data. This can result in S3 bucket sprawl, as each application creates another logging bucket for s3 buckets used in the app. This construct allows use/reuse of a log bucket for multiple s3 buckets' access logs by creating it when needed, and reusing it when it already exists. Best practices for security of the bucket help ensure the security and confidentiality of the data by restricting public access and using encryption. The bucket name of the bucket whose access is being logged is used as the prefix in the log bucket.

### Proposed Solution

Create the S3 log bucket if it doesn't exist
Apply the necessary ACLs to prevent public access
Apply the necessary Grants to allow log service write access
Configure access logging for the bucket to be logged to a prefix in the logging bucket

Ex. app_bucket needs access logging. log_bucket is created. Access to app_bucket is logged to s3://log_bucket/app_bucket

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hnishar** [comment]
Interesting idea on sharing the same LoggingBucket across S3 related patterns. Instead of making a new construct, I'd suggest to provide optional input (construct props) for user to reference an existing LoggingBucket for *-s3-* patterns and also the focus of this library is multi-service patterns.

**Comment by hnishar** [comment]
Closing the issue, feel free to re-open if you have any follow-up questions.
