### ISSUE TITLE
Documentation links hit wrong construct

### ISSUE THREAD

**Issue by mbonig** [awslabs/aws-solutions-constructs#3]
Clicking on the construct Props interface link will take me to the wrong construct (always to aws-apigateway-dynamodb).

### Reproduction Steps

1. Go here: https://docs.aws.amazon.com/solutions/latest/constructs/aws-dynamodb-stream-lambda.html
2. Scroll down to "Initializer" 
3. Click on bullet "props DynamoDBStreamToLambdaProps"

Result: 
should go to the props of the 'ApiGatewayToDynamoDB' construct

### Error Log

None.

### Environment

  - **CDK CLI Version      :**. 1.46.0
  - **CDK Framework Version:** NA
  - **AWS Solutions Constructs Version     :** 1.46.0
  - **OS                   :** NA
  - **Language             :** NA

### Other

I'm guessing it's due to the ambiguous `(#pattern-construct-props)`. Works fine when single-construct displays but when consolidated into a single-page for all constructs it becomes ambiguous and the first one is hit.

--- 

This is :bug: Bug Report

**Comment by hayesry** [comment]
Thanks for the find @mbonig, updated documentation on it's way out!

**Comment by hnishar** [comment]
Documentation has been updated
