### ISSUE TITLE
core/lib/CloudFrontDistributionForApiGateway function bug

### ISSUE THREAD

**Issue by beomseoklee** [awslabs/aws-solutions-constructs#30]
https://github.com/awslabs/aws-solutions-constructs/blob/ccf819c99a907634cc78de26cca07d77eb748656/source/patterns/%40aws-solutions-constructs/core/lib/cloudfront-distribution-helper.ts#L119-L125

The above source code has a bug. No matter what parameter is provided to ```httpSecurityHeader```, ```_httpSecurityHeaders``` would be ```true```.

--- 

This is :bug: Bug Report

**Comment by wesselvdv** [comment]
I guess the idea was to do an undefined check. This is currently messing up using this solution for a different region than `us-east-1`, because the edge lambda association fails.

**Comment by hnishar** [comment]
This has been addressed in the latest release [v1.54.0](https://github.com/awslabs/aws-solutions-constructs/releases/tag/v1.54.0)
