### ISSUE TITLE
[cloudfront-s3] - option to disable creation of cloudfront logging bucket or pass in removal policy to it

### ISSUE THREAD

**Issue by naseemkullah** [awslabs/aws-solutions-constructs#302]
https://github.com/awslabs/aws-solutions-constructs/blob/f50cbbc46ab4cd0f2360e1cc6ee82298905938a4/source/patterns/%40aws-solutions-constructs/core/lib/cloudfront-distribution-helper.ts#L179-L186

It appears that there is no way currently to avoid creating a logging bucket for the cloudfront distribution, would it be possible to change this such that one could disable its creation if `enableLogging` is set to false for the cloudfront web distribution props?

My issue is that I am deploying ephemeral stacks that use this construct and empty unused cloudfront logging buckets are being left behind.

Another option would be to be able to thread through the removal policy to the bucket created [here](https://github.com/awslabs/aws-solutions-constructs/blob/f50cbbc46ab4cd0f2360e1cc6ee82298905938a4/source/patterns/%40aws-solutions-constructs/core/lib/cloudfront-distribution-helper.ts#L183).

**Comment by biffgaut** [comment]
Thanks - we'll take a look. Definitely see the problem. It hasn't become glaringly obvious yet because the Lambda@Edge functions prevent cleanly deleting the stack without manual intervention. But we're currently moving from Lambda@Edge to CloudFront functions so teardown will be easier - at that point the remaining buckets will become a problem for us as well.

**Comment by naseemkullah** [comment]
Hi @biffgaut, I've disabled the edge function and pass in my own cloudfront function so have not hit that issue,

I've started work on https://github.com/awslabs/aws-solutions-constructs/pull/303

**Comment by biffgaut** [comment]
It's in the unit test "test override cloudfront replace custom lambda@edge" - the snapshot no longer matches. Just leave it for now, we're discussing the issue on our end. We like fixing the problem you're pointing out, but your fix only hits half of it. We'll be in touch very shortly.

**Comment by naseemkullah** [comment]
>       * In each Cloudfront construct folder run `npm run snapshot-update' and 'cdk-integ'

Just to clarify, this needs to run in every construct, not just the one I am working on?

**Comment by naseemkullah** [comment]
I hope a solution for the snapshot generation/test expected values comes soon, it would help reduce the hoops to go through when contributing, especially for outside collaborators such as myself. That said I think #303 can be reviewed now.

**Comment by naseemkullah** [comment]
closed via #303
