### ISSUE TITLE
Upgrade deprecated CDK property used by API Gateway patterns

### ISSUE THREAD

**Issue by beomseoklee** [awslabs/aws-solutions-constructs#31]
I was using aws-cloudfront-apigateway-lambda pattern, and I found the default authorization type for API Gateway is IAM. I needed to change that one to NONE, but I saw that the pattern is using deprecated CDK property ```options```.
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.LambdaRestApi.html

### Use Case

```options``` property is still available, but since it's deprecated property, it would be better to replace ```options``` to other live properties.

### Proposed Solution

Since every ```options``` properties are available in ```LambdaRestApiProps```, it would be easy to use ```LambdaRestApiProps``` itself instead of ```options```.
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.LambdaRestApiProps.html

### Other

These are source code where ```options``` are used.

https://github.com/awslabs/aws-solutions-constructs/blob/ccf819c99a907634cc78de26cca07d77eb748656/source/patterns/%40aws-solutions-constructs/core/lib/apigateway-defaults.ts#L50-L56

https://github.com/awslabs/aws-solutions-constructs/blob/ccf819c99a907634cc78de26cca07d77eb748656/source/patterns/%40aws-solutions-constructs/core/lib/apigateway-defaults.ts#L64-L70

* [ ] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hnishar** [comment]
This has been addressed in the latest release [v1.54.0](https://github.com/awslabs/aws-solutions-constructs/releases/tag/v1.54.0)
