### ISSUE TITLE
Create CloudWatch Logs for Lambda functions

### ISSUE THREAD

**Issue by thomasklinger1234** [awslabs/aws-solutions-constructs#316]
### Use Case

I need to do the following per Lambda function when using any of the constructs that create a Lambda function:

```
       new logs.LogGroup(this, "dummy-logs", {
            logGroupName: `/aws/lambda/${dummyFn.lambdaFunction.functionName}`,
            removalPolicy: cdk.RemovalPolicy.DESTROY,
            retention: logs.RetentionDays.ONE_WEEK,
        });
```

Otherwise, it won't create an log groups per Lambda which is annoying for the following reasons:

- Stale log groups which do not vanish when the stack is deleted
- Cost for tracking unmanaged log groups (How do people handle these?)

### Proposed Solution

Make it possible to auto-create the log group, either via `logGroupProps`/`existingLogGroup` or via a method on the constructs like `createLogGroup()`.

This will be a non-breaking change since the current behavior can still be used.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
Thanks - we'll take a look.

**Comment by biffgaut** [comment]
We're pretty sure this isn't possible. We use the Lambda.Function construct internally, and there is no way to pass an existing Log Group nor LogGroupProps on creation of a that construct. [FunctionProps](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Function.html) does allow you to specify the retention interval for log entries, but other than that the construct takes complete control of creating the log group. The logGroup property of the Function construct is readonly, so can't be set.
