### ISSUE TITLE
Why is KinesisFirehoseToS3Props.existingBucketObj of type s3.Bucket and not s3.IBucket

### ISSUE THREAD

**Issue by cfredhart** [awslabs/aws-solutions-constructs#33]
I am trying to create a KinesisFirehose to an existing S3 bucket. I would like to be able to pass the existing bucket (not created via CDK or CloudFormation) to the `KinesisFirehoseToS3` constructor in the `KinesisFirehoseToS3Props`. I am looking the bucket up using `Bucket.fromBucketName` which returns an `IBucket` rather than a `Bucket`. Since the `existingBucketObj` attribute of `KinesisFirehoseToS3Props` is of type `Bucket`, I cannot pass the `IBucket` reference to this construct. 

It appears that the implementation of `KinesisFirehoseToS3` does not make use of any features of the `existingBucketObj` property that are not in `IBucket`. Would it be possible to change the type of the `existingBucketObj` property to `Ibucket`?

**Comment by hnishar** [comment]
cfredhart@ thanks for reporting the issue, we will look into it and provide the fix for it soon. Please keep the feedback coming.

**Comment by hnishar** [comment]
cfredhart@ the update has been pushed out in the latest release v1.57.0, for proof see the integegration test case [here](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/aws-kinesisfirehose-s3/test/integ.pre-existing-bucket.ts) and the resulting CFN template [here](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/aws-kinesisfirehose-s3/test/integ.pre-existing-bucket.expected.json)
