### ISSUE TITLE
Provide props for CloudTrail S3 buckets created by S3ToStepfunctions

### ISSUE THREAD

**Issue by leftiness** [awslabs/aws-solutions-constructs#332]
The client should have the option (but not requirement) to provide any props used within the construct. 

S3ToStepfunctions creates CloudTrail S3 buckets with props that can't be provided.

### Use Case

I want to provide `s3.BucketProps` for `cloudtrailBucket` and `cloudtrailLoggingBucket` so that they will be destroyed.

```js
{
  autoDeleteObjects: true,
  removalPolicy: RemovalPolicy.DESTROY
}
```

### Proposed Solution

```js
[this.cloudtrailBucket, this.cloudtrailLoggingBucket] = defaults.buildS3Bucket(
  this,
  { bucketProps: props.cloudtrailBucketProps },
  'CloudTrail'
); 
```

### Other

https://github.com/awslabs/aws-solutions-constructs/blob/5411ab73301f85ff7a5df1e6425996e2c6e8ffb5/source/patterns/%40aws-solutions-constructs/aws-s3-stepfunctions/lib/index.ts#L109

Similar issue: #213 

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
Thanks, we'll take a look.

**Comment by leftiness** [comment]
Workaround: use `deploy_cloud_trail=False`. Create your own CloudTrail resources. 

```py
my_bucket = Bucket(
    self, "my-bucket",
    removal_policy=RemovalPolicy.DESTROY,
    auto_delete_objects=True)

my_trail = Trail(
    self, "my-trail",
    bucket=Bucket(
        self, "my-trail-bucket",
        removal_policy=RemovalPolicy.DESTROY,
        auto_delete_objects=True))

my_trail.add_s3_event_selector(
    [S3EventSelector(bucket=my_bucket)],
    include_management_events=False)

S3ToStepFunction(
    self, "my-s3-to-stepfunction",
    existing_bucket_obj=my_bucket,
    state_machine_props=StateMachineProps(definition=my_stepfunction),
    log_group_props=LogGroupProps(removal_policy=RemovalPolicy.DESTROY),
    deploy_cloud_trail=False)
```
