### ISSUE TITLE
[Question] What is the aws-cdk dependency update timeline?

### ISSUE THREAD

**Issue by robertd** [awslabs/aws-solutions-constructs#34]
Hello,

I'm running a project in aws-cdk 1.56.0 and I'm unable to use some of the aws-solutions-constructs 1.54.0 (aws-cloudfront-s3). I was wondering what's the aws-cdk dependency update timeline, since they have weekly releases? What is expected lag time to get aws-solutions-constructs' aws-cdk dependency up to date?

Thanks!

**Comment by hnishar** [comment]
robertd@ We strive to update the library for the new CDK releases as quickly as possible, all the patterns are now updated to the latest CDK release v1.56.0

**Comment by robertd** [comment]
Thanks @hnishar. I was just wondering so I can plan for the aws-cdk release sync.
