### ISSUE TITLE
AWS::KinesisFirehose::DeliveryStream deliveryStreamType and deliveryStreamEncryptionConfiguration

### ISSUE THREAD

**Issue by derrikf-spindance** [awslabs/aws-solutions-constructs#352]
https://github.com/awslabs/aws-solutions-constructs/blob/522feb190085463206dd0edb14b4b6655b8cfb8c/source/patterns/%40aws-solutions-constructs/aws-kinesisfirehose-s3/lib/index.ts#L168-L180

Why is encryption automatically enabled for a deliveryStreamType of "DirectPut"?

I'm aware of why it's a good idea, but I'd like to have the choice to not enable encryption by default.

Alternatively, maybe check for explicitly set:

```
encryptionConfiguration: {
    noEncryptionConfig: 'NoEncryption',
},
```

and if it isn't set, then enable encryption(?)

**Comment by biffgaut** [comment]
Thanks, we'll take a look.

**Comment by biffgaut** [comment]
Try turning off the property after instantiating the contruct:

```
    const f2s3 = new KinesisFirehoseToS3(this, 'new-stream', {
      bucketProps: {
        removalPolicy: cdk.RemovalPolicy.DESTROY
      }
    });
    f2s3.kinesisFirehose.deliveryStreamEncryptionConfigurationInput = undefined;
```

When I do that the deliveryStreamEncryptionConfiguration is removed from the output template.
