### ISSUE TITLE
Using an existing bucket to create CloudFront, the origin domain mapping error

### ISSUE THREAD

**Issue by James96315** [awslabs/aws-solutions-constructs#365]
![image](https://user-images.githubusercontent.com/75407126/132298264-6319abac-7f1e-445f-a17e-4313283d3f69.png)

### Reproduction Steps

        //this stack is deployed in us-east-1, and bucket is in us-west-2
        const websiteBucket = Bucket.fromBucketName(this,'BucketByName','BucketName')
        const portal = new CloudFrontToS3(this, 'Portal', {
            insertHttpSecurityHeaders: false,
            existingBucketInterface: websiteBucket,
            cloudFrontDistributionProps: {
                errorResponses: [
                    {
                        ttl: cdk.Duration.seconds(10),
                        httpStatus: 403,
                        responseHttpStatus: 200,
                        responsePagePath: '/index.html'
                    }
                ],
                domainNames: ['www.urdomain.com'],
                certificate: certificate,
                comment: 'Portal',
                priceClass: cloudfront.PriceClass.PRICE_CLASS_ALL,
                minimumProtocolVersion: cloudfront.SecurityPolicyProtocol.TLS_V1_2_2021
            }
        })

### Environment

  - **CDK CLI Version      : 1.120.0**
  - **AWS Solutions Constructs Version     :1.120.0**
  - **OS                   :**
  - **Language             :typescript**

### Other

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
I don't fully understand your question. Is the issue:

* that the  bucket URL says us-east-1 when the bucket is actually in us-west-2
* when you try to deploy a stack in us-east-1 that references a bucket in us-west-2 you get an error

**Comment by James96315** [comment]
the origin domain

> I don't fully understand your question. Is the issue:
> 
> * that the  bucket URL says us-east-1 when the bucket is actually in us-west-2
> * when you try to deploy a stack in us-east-1 that references a bucket in us-west-2 you get an error

The original domain is set incorrectly. Although the bucket name is correct, the region is wrong. After deployment, the CloudFront URL cannot be accessed. The bucket is not in us-east-1, but in the us-west-2 region.

**Comment by hnishar** [comment]
@James96315 possibly related to [this](https://github.com/aws/aws-cdk/issues/16386) issue in CDK, there's no extra logic in Solutions construct to provide the region, see [here](https://github.com/awslabs/aws-solutions-constructs/blob/main/source/patterns/%40aws-solutions-constructs/core/lib/cloudfront-distribution-defaults.ts#L49)

**Comment by biffgaut** [comment]
As @hnishar  points out, this behavior is built into the CDK L2 construct - that construct assumes the bucket is in the deployment region. It's a very new issue, so we've no idea yet as to how fast or if the CDK team will respond. In the meantime, to achieve your goals but stay in CDK/Solutions Constructs, you might look at setting up the CloudFront distribution using the L1 CloudFront construct, CfnDistribution. The L1 construct is just a wrapper over the CloudFormation implementation, it doesn't make any assumptions or optimizations to help you out but it also allows you to specify all aspects of your resource configuration.

**Comment by James96315** [comment]
refer to https://github.com/aws/aws-cdk/issues/16386#issuecomment-916823583

```
const s3Origin = s3.Bucket.fromBucketAttributes(this, 'ImportBucket', {
  bucketName: 'demo2cloudfront',
  region: 'us-east-2',
});

```
