### ISSUE TITLE
Longer IDs in deprecated constructs breaking existing installations

### ISSUE THREAD

**Issue by biffgaut** [awslabs/aws-solutions-constructs#369]
[PR 315](https://github.com/awslabs/aws-solutions-constructs/pull/315) increased the length of the id by seven characters ("-wrapped") when it launches implementation of the construct with a new name inside the shel with the old name.

Unfortunately both the shell and the internal construct can't use the same name, so we must alter the id in some way if we don't alter the actual id sent from the client. We will:

* Change the added text to just "w" to reduce the number of implementations impacted
* The fix for impacted implementations is to switch the new constructs. As they are functionally equivalent, this is very simple - merely npm install'ing the new construct and changing the type references in the code.

There are about 8 renamed constructs where this pattern needs to be addressed.

### Reproduction Steps

See comment in [PR 315](https://github.com/awslabs/aws-solutions-constructs/pull/315)

### Environment

  - **CDK CLI Version      :**
  - **CDK Framework Version:**
  - **AWS Solutions Constructs Version     :**
  - **OS                   :**
  - **Language             :**

### Other

--- 

This is :bug: Bug Report

**Comment by pvbouwel** [comment]
Shortening the wrapping would have worked in my case. Since it is often a good time to switch away from deprecated constructs I've switched (in my case `aws-events-rule-sqs` ->  `aws-eventbridge-sqs`) to the new constructs and that works also great as expected . Thanks

**Comment by biffgaut** [comment]
Glad to hear the transition to the new name went smoothly - we tried to ensure this but it still gives us some concern.
