### ISSUE TITLE
Inconsistent API Gateway Authentication Between Constructs

### ISSUE THREAD

**Issue by purplebari** [awslabs/aws-solutions-constructs#37]
Adding the following property to the props object for ApiGatewayLambda and ApiGatewayDynamoDb causes the API Gateway to be launched with no authentication.
```
      apiGatewayProps: {
        defaultMethodOptions: {
          authorizationType: api.AuthorizationType.NONE
        }
      }
```
Adding the same property to the props object for ApiGatewaySqs is ignored and no message is provided to the user that they are not getting the behavior they requested.

### Reproduction Steps

Line 189 of aws-apigateway-sqs is:
```
  authorizationType: api.AuthorizationType.IAM,
```
This is not found in the same addMethod() function in aws-apigateway-dynamodb.

It might be worth considering moving this function to core/apigatewayhelper.ts to remove the redundant implementations and ensure behavior stays consistent in the future.

### Error Log

N/A

### Environment

  - **CDK CLI Version      :*1.56.0*
  - **CDK Framework Version:*1.56.0*
  - **AWS Solutions Constructs Version     :*1.56.0*
  - **OS                   :*macOS*
  - **Language             :*typescript*

### Other

--- 

This is :bug: Bug Report

**Comment by hnishar** [comment]
purplebari@ This bug has been fixed in the latest release v1.58.0
