### ISSUE TITLE
aws-cloudfront-apigateway Documentation Error

### ISSUE THREAD

**Issue by purplebari** [awslabs/aws-solutions-constructs#38]
The sample code on the readme page says
```
const _api = defaults.RegionalApiGateway(stack, func);
```

which leads to this error:
▶ cdk synth
Cannot read property 'deployLambdaFunction' of undefined
Subprocess exited with error 1

I believe the correct example code should say:
```
  const [_api] = defaults.RegionalLambdaRestApi(this, func);
```

This agrees with the test code.
### Environment

  - **CDK CLI Version      :** 1.56.0
  - **CDK Framework Version:** 1.56.0
  - **AWS Solutions Constructs Version     :** 1.56.0
  - **OS                   :** MacOS
  - **Language             :** typescript

### Other

--- 

This is :bug: Bug Report

**Comment by hnishar** [comment]
purplebari@ The documentation has been fixed in the latest release v1.58.0
