### ISSUE TITLE
missing cloudwatch.Alert[] property in Readme.md files

### ISSUE THREAD

**Issue by surukonda** [awslabs/aws-solutions-constructs#384]
Even though aws-eventbridge-kinesisstreams and aws-events-rule-kinesisstreams constructs have a property with an optional list of cloudwatch alerts, this information is missing from README.md file.

### Reproduction Steps

* Refer aws-events-rule-kinesisstreams [Pattern Properties](https://github.com/awslabs/aws-solutions-constructs/tree/main/source/patterns/%40aws-solutions-constructs/aws-events-rule-kinesisstreams#pattern-properties) section of README.md file

* Refer aws-eventbridge-kinesisstreams [Pattern Properties](https://github.com/awslabs/aws-solutions-constructs/tree/main/source/patterns/%40aws-solutions-constructs/aws-eventbridge-kinesisstreams#pattern-properties) section of README.md file

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Thanks - we'll take care of this.
