### ISSUE TITLE
New L2 construct in aws-cloudfront module

### ISSUE THREAD

**Issue by robertd** [awslabs/aws-solutions-constructs#39]
Hello,

Is there a timeline when `aws-cloudfront-s3`, `aws-cloudfront-apigateway`, `aws-cloudfront-apigateway-lambda` would start using new aws-cloudfront L2 construct ([Distribution](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.Distribution.html))? Or perhaps, there will be new experimental constructs ones using the new Distribution construct side by side with current implementation.

![image](https://user-images.githubusercontent.com/31543/90077924-9a5f7480-dcc0-11ea-8701-628c65f0b662.png)

**Comment by hnishar** [comment]
robertd@ Thanks for bringing this up, we'll look into it and provide the update here.

**Comment by hnishar** [comment]
robertd@ We will wait for the [developer preview](https://github.com/aws/aws-cdk/milestone/5) release of the new CDK 'Distribution' L2 construct before updating the Solutions Constructs patterns.

**Comment by hnishar** [comment]
Updated all `aws-cloudfront-*` patterns to use the new L2 cloudfront construct `Distribution` in the latest release v1.68.0
