### ISSUE TITLE
Dynamo constructs don't offer provided table.

### ISSUE THREAD

**Issue by mbonig** [awslabs/aws-solutions-constructs#4]
When working with the LambdaToDynamoDB construct, I have the option of providing a Lambda function. This is how I can integrate it with an ApiGatewayToLambda construct. However, constructs like LambdaToDynamoDB and DynamoDBStreamToLambda don't allow me to provide an existing Table. Which means I can't use them together. I can wire:

ApiGatewayToLambda->LambdaToDynamoDB

but can't wire

LambdaToDynamoDB -> DynamoDBStreamToLambda 

or

LambdaToDynamoDB -> DynamoDBStreamToLambdaToElasticSearchAndKibana

as these constructs insist on creating a new table. 

### Use Case

I'd like to be able to chain together a number of constructs from this library. Right now I can't seem to do that.

### Proposed Solution

Continue the pattern seen with the lambda Function and the LambdaToDynamoDB construct, something like:
```
export interface DynamoDBStreamToLambdaProps {
  
   readonly deployTable: boolean;
   readonly existingTableObj?: dynamodb.Table,

}
```

### Other

I'm curious why the boolean needs to be provided? Could a truthy check on 'existingXObject' be enough?

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hnishar** [comment]
The latest release v1.47.0 takes care of this feature, btw, thanks for the PR for the same!
