### ISSUE TITLE
New Pattern: aws-events-rule-sns

### ISSUE THREAD

**Issue by aijunpeng** [awslabs/aws-solutions-constructs#42]
Build a new pattern to send notifications to an SNS topic when a cloudwatch event rule is triggered

### Use Case
Need this pattern to send notifications to an SNS topic when a cloudwatch event rule is triggered

### Proposed Solution
Build an aws-events-rule-sns pattern:
Create a CloudWatch Events Rule, SNS Topic and relevant roles/permissions
Set SNS topic as the target of the cw event rule
Enable server-side kms encryption for sns topic

**Comment by hnishar** [comment]
aijunpeng@ Adding it to the backlog

**Comment by gockle** [comment]
@hnishar I will work on creating this pattern and submit a PR for it.

**Comment by hnishar** [comment]
This has been pushed out in the latest release v1.62.0
