### ISSUE TITLE
Unable to exclude API Gateway cloudwatch configuration from stack

### ISSUE THREAD

**Issue by mdschnee** [awslabs/aws-solutions-constructs#445]
When overriding API Gateway properties on a solution construct that includes this type of resource ( I am using the aws-apigateway-sqs construct), the cloudWatchRole boolean property that can be passed on the RestApiProps object is not being evaluated to determine if APIGateway account and IAM role resources should be included in the template. Regardless of how the value is currently set, the ApiGateway::Account and corresponding role resource is always generated in the stack template. This is not ideal when working in "shared" AWS accounts where the ApiGateway Cloudwatch account settings are provisioned and maintained by a centralized "account owner" team.

### Reproduction Steps
Create a new stack using a construct that contains an API gateway. 
Pass in a RestApiProps object to the solutions construct that sets `{cloudWatchRole=false}`
Run cdk synth and verify that the template output contains an `AWS::ApiGateway::Account` resource that references an `AWS::IAM::Role` resource in the template setting the required permissions to write to Cloudwatch.

### Environment

  - **CDK CLI Version : 1.125.0 (build 67b4921)
  - **CDK Framework Version: aws-cdk@1.125.0
  - **AWS Solutions Constructs Version : aws-apigateway-sqs@1.125.0
  - **OS: MacOS BigSur 
  - **Language: Python 

### Other

It looks like this could potentially be resolved by adding [a condition here](https://github.com/awslabs/aws-solutions-constructs/blob/29ffd5a293f92639341a6fb4376fb6aad8cc902a/source/patterns/%40aws-solutions-constructs/core/lib/apigateway-helper.ts#L144) to core/lib/apigateway-helper.ts to check if override properties were passed to the construct. If so, check for the cloudWatchRole bool property and if false, bypass the configureCloudwatchRoleForApi method call. 

--- 

This is :bug: Bug Report

**Comment by Derschneemann** [comment]
I think the desired behavior would be for it to work in the same manner as if using the generic RestApi construct. So if you pass the cloudWatchRole property as True when using a RestApi construct, the template output will contain an IAM role resources that is references from an `AWS::ApiGateway::Account` resource, similar to what we get when using the solutions constructs. If you set this property to False though, then these two resources are not generated in the template output. 

At the moment, regardless of how this property is set when overriding the RestApiProps values on solutions construct, you will always get the role and ApiGateway::Account resources generated in the output.

**Comment by biffgaut** [comment]
Changes to be implemented-
* If user passes in cloudWatchRole prop as false, we will create no Role and assign no role to the API Gateway service. If there is an account wide role in use, it will be undisturbed.
* If user passes in a cloudWatchRole prop as true, or if the user does not specify a cloudWatchRole value, we will send false to the CDK so it does not create a role and we will create our own role that specifies account number, but not region nor log group (the same as we do now, but removing the region).
