### ISSUE TITLE
Enable passing an originPath for aws-cloudfront-s3 

### ISSUE THREAD

**Issue by emcfins** [awslabs/aws-solutions-constructs#451]
Today, when using the aws-cloudfront-s3 construct, it assumes the origin path for the S3 bucket will be '/'.
This feature will allow users to specify an [originPath](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront-origins.S3OriginProps.html#originpath) for the CloudFront distrobution.

### Use Case

This will enable users to have more flexibility in what is stored within the S3 bucket and provide the ability to use a single bucket for multiple paths.

### Proposed Solution

Add an optional parameter for `originPath`. 
If a value is provided, use that value. If not provided, retain the current behavior.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
Go ahead Erin. Start your PR with an update to the README.md file that shows how it will read after your changes (you will need to do this eventually anyway), this will ensure we're all on the same page before you start coding.

**Comment by biffgaut** [comment]
Addressed in https://github.com/awslabs/aws-solutions-constructs/issues/451.
