### ISSUE TITLE
Unable to install recent aws-solutions-constructs; appears to only have 0.0.1-security available

### ISSUE THREAD

**Issue by raginjason** [awslabs/aws-solutions-constructs#497]
When trying to install v1.124.0 of this project, npm spits out the following error:

> No matching version found for aws-solutions-constructs@1.124.0

It appears that 0.0.1-security is the only version available. Running `npm view aws-solutions-constructs versions` confirms this:
```
$ npm view aws-solutions-constructs versions
0.0.1-security
```

### Reproduction Steps

Running the following will error:

```
npm install aws-solutions-constructs@1.124.0
```

### Error Log

> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for aws-solutions-constructs@1.124.0.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.

### Environment

  - **CDK CLI Version      : 1.124.0
  - **CDK Framework Version: 1.124.0
  - **AWS Solutions Constructs Version     : 1.124.0
  - **OS                   : macOS Monterey Version 12.0.1
  - **Language             : Python

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Solutions Constructs are published individually, so checking the versions should be done for individual constructs:

`npm view @aws-solutions-constructs/aws-s3-lambda versions`

Similarly, they should be installed individually into projects while in the package.json folder:

`npm install @aws-solutions-constructs/aws-s3-lambda@1.124.0`

**Comment by raginjason** [comment]
Interesting. This contrasts with how CDK itself is managed. I wonder if that difference is intentional.

**Comment by biffgaut** [comment]
The CDK 1.0 `npm install -g aws-cdk` process installs the CLI and other things along with the library. After creating an app with `cdk init` several constructs are installed, but many still require individual installation in a project using `npm install @aws-cdk/construct-name` (I do not know the reasons behind the differentiation).

CDK 2.0 changes the model, and installing CDK in a project will install _all_ constructs. There will be a differentiation between Experimental and Stable constructs, Experimental constructs will be in a different library that requires explicit installation in a project. CDK 2.0 has Release Candidates available with a GA date as yet unannounced. Solutions Constructs will still be installed individually in the CDK 2.0 world. We have Release Candidates available as well and will got to General Availability with CDK 2.0.
