### ISSUE TITLE
New Pattern: aws-apigateway-kinesisstream

### ISSUE THREAD

**Issue by dscpinheiro** [awslabs/aws-solutions-constructs#51]
This new pattern is similar to the existing _aws-apigateway-sqs_, but the service integration is with Kinesis Data Streams.

### Use Case
API Gateway provides a layer of abstraction from the streaming storage (Kinesis Data Streams). This layer of abstraction enables custom authentication approaches and control quotas for specific data producers.

### Proposed Solution
The new pattern will use this documentation page as a reference: https://docs.aws.amazon.com/apigateway/latest/developerguide/integrating-api-with-aws-services-kinesis.html

### Other
* [x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by hnishar** [comment]
This has been pushed out in the latest release v1.62.0
