### ISSUE TITLE
BYO DynamoDB table to aws-apigateway-dynamodb

### ISSUE THREAD

**Issue by hayesry** [awslabs/aws-solutions-constructs#53]
Similar to how an existingLambdaObj? can be supplied for select patterns to bring-your-own Lambda function, I'm seeking the ability to bring-your-own DynamoDB table to this pattern.

### Use Case

This feature would be useful if the user already has a DynamoDB table in their account that they would like to retroactively wrap an API around using the pattern OR if they are using another Solutions Constructs pattern that deploys a table, and they would like to hook an API onto that table.

### Proposed Solution

Add an existingTableObj? pattern prop, similar to aws-dynamodb-stream-lambda or aws-lambda-dynamodb.

### Other

N/A

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hnishar** [comment]
This update was released in v1.78.0
