### ISSUE TITLE
Cognito UserPoolDomain must be globally unique

### ISSUE THREAD

**Issue by mobri2a** [awslabs/aws-solutions-constructs#54]
currently, cognito-helper sets up a Cognito::UserPoolDomain with the domain ID of the ElasticSearch domain (when used with aws-lambda-elasticsearch-kibana). While the Elasticsearch domain does not have to be globally unique, the Cognito domain **does**.

### Use Case

Using the aws-lambda-elasticsearch-kibana pattern, one must ensure that both the ES and Cognito UserPoolDomain are globally unique, otherwise must use addPropertyOverride on the UserPoolDomain to make it unique, such as by appending the AWS account Id

### Proposed Solution

Allow the user to provide Cognito parameters (similar to ES) at the Solution Construct. Use the ES domain with the account Id appended as a reasonable default.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hnishar** [comment]
This has been fixed in v1.64.0
