### ISSUE TITLE
feat(aws-s3-stepfunctions): Replace EventBridge enabled property override with prop

### ISSUE THREAD

**Issue by mickychetta** [awslabs/aws-solutions-constructs#565]
The S3 cfnBucket class has created new prop called [eventBridgeEnabled](https://github.com/aws/aws-cdk/issues/18076) in S3 bucket props. We will replace the override code line 

```cfnBucket.addPropertyOverride('NotificationConfiguration.EventBridgeConfiguration.EventBridgeEnabled', true);```

with the newly added prop to properly create new S3 buckets with EventBridge enabled. 

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
Clarify - this is to update the CDK. We've already implemented in our code using the escape hatch. To do this in the CDK will help them and simplify our code.

**Comment by mickychetta** [comment]
Issue: 
https://github.com/aws/aws-cdk/issues/18076

Related PRs:
https://github.com/aws/aws-cdk/pull/18150
https://github.com/aws/aws-cdk/pull/18614
