### ISSUE TITLE
BYO Kinesis Stream to aws-kinesisstreams-lambda

### ISSUE THREAD

**Issue by dscpinheiro** [awslabs/aws-solutions-constructs#58]
Similar to how an existingLambdaObj? can be supplied for select patterns to bring-your-own Lambda function, I'm seeking the ability to bring-your-own Kinesis Stream to this pattern.

### Use Case
This feature would be useful if the user already has a data stream table in their account that they would like to retroactively connect to a Lambda function.

### Proposed Solution
Add an existingStreamObj? pattern prop, similar to aws-apigateway-kinesisstreams.

Question: Would it also make sense to update the `eventSourceProps` property to be of type `KinesisEventSourceProps` (instead of `EventSourceMappingOptions`)? The other patterns for Lambda (such as `aws-dynamodb-stream-lambda` and `aws-s3-lambda`) are already using the types from `aws-lambda-event-sources`.

### Other
* [x]  👋 I may be able to implement this feature request
* [x]  ⚠️ This feature might incur a breaking change

This is a 🚀 Feature Request

**Comment by hnishar** [comment]
The update has been pushed out in v1.63.0
