### ISSUE TITLE
New Pattern: aws-cloudfront-apigateway-httpapi

### ISSUE THREAD

**Issue by morishin** [awslabs/aws-solutions-constructs#586]
Add new pattern `aws-cloudfront-apigateway-httpapi` which is almost the same as `aws-cloudfront-apigateway` but it uses HTTP API instead of REST API.

### Use Case

The existing `aws-cloudfront-apigateway` uses _REST API_ feature of API Gateway, however I would like to use _HTTP API_ feature instead.

### Proposed Solution

Almost the same as: https://github.com/awslabs/aws-solutions-constructs/blob/main/source/patterns/@aws-solutions-constructs/aws-cloudfront-apigateway/README.md

Only difference is using HTTP API instead of REST API of API Gateway.

### Other

I forked and edit `aws-cloudfront-apigateway` pattern to use HTTP API for private use.
I'm thinking of submitting a pull-request as a new pattern `aws-cloudfront-apigateway-httpapi`, what do you think?

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
Thanks for the input. HTTP APIs are something we're looking at perhaps doing this year. Before creating a construct, submit a README.md file patterned after the others. We wouldn't want you to do all the work then find out that it hadn't met our design guidelines and we couldn't publish it.
