### ISSUE TITLE
New Pattern: aws-events-rule-kinesisstream

### ISSUE THREAD

**Issue by aijunpeng** [awslabs/aws-solutions-constructs#59]
Build a new pattern to send data to kinesis stream when a cloudwatch event rule is triggered

### Use Case

Need this pattern to send data to kinesis stream when a cloudwatch event rule is triggered

### Proposed Solution

Build an aws-events-rule-kinesisstream pattern:
Create a CloudWatch Events Rule, kinesis data stream and relevant roles/permissions
Set kinesis data stream as the target of the cw event rule
Enable server-side kms encryption for kinesis data stream

### Other
I am implementing this feature request and will submit a PR when it is done.

**Comment by hnishar** [comment]
This pattern has been published in the latest release v1.70.0
