### ISSUE TITLE
Missing S3 secureTransport helper function

### ISSUE THREAD

**Issue by xeroxnir** [awslabs/aws-solutions-constructs#593]
The helper function applySecureBucketPolicy to implement enforce secureTransport was removed from the repository since [this](https://github.com/awslabs/aws-solutions-constructs/commit/fc4fab88a9cecef65a5dad84c1539daee7862887). 

Any reason why this was removed?

**Comment by biffgaut** [comment]
Thanks for the feedback - unfortunately the link you provided is link results in a GitHub 404 page. Can you fix the link or better guide us to the area of concern? Thanks.

**Comment by xeroxnir** [comment]
Updated, extra dot at the end.

**Comment by biffgaut** [comment]
That change was in response to [Issue 518](https://github.com/awslabs/aws-solutions-constructs/issues/518). We originally implemented the handling of the enforceSSL in our code and in so doing had introduced incorrect behavior. We relegated handling of this prop to the original the CDK code, making our `applySecureBucketPolicy()` obsolete as CDK has its own implementation  [here](https://github.com/aws/aws-cdk/blob/d325004fb9a8304e8ee8519de689be30cefdbd9c/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L1783). The CDK implementation also creates a less granular policy, which is nearly always better.

Unfortunately, we can only support the documented interfaces for the constructs themselves. While the nature of Typescript doesn't allow us to  hide our internal support routines, they are not supported for client use and can change at any time. If you were dependent upon this function I would suggest lifting the code from an old version to incorporate in your app (or copy the CDK implementation).

**Comment by xeroxnir** [comment]
So you would not recommend reusing AWS Solutions Constructs helper functions in other CDK projects? 

I see a lot of value for customers in reusing these functions to implement AWS Well Architected or security best practices such as in ([applySecureTopicPolicy](https://github.com/awslabs/aws-solutions-constructs/blob/main/source/patterns/%40aws-solutions-constructs/core/lib/sns-helper.ts), [applySecureQueuePolicy](https://github.com/awslabs/aws-solutions-constructs/blob/a01bceca53a9a8c5fccf93967c46f467fba85b4e/source/patterns/%40aws-solutions-constructs/), [buildWebacl](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/core/lib/waf-helper.ts)

**Comment by biffgaut** [comment]
I wouldn't make a recommendation for or against utilizing the helper functions within Solutions Constructs. My point is that if you call these functions from your AWS Solutions Constructs client, you must recognize that you are vulnerable to the functions changing or disappearing in future releases. If there are functions there with functionality that you find beneficial, you are welcome to call them with the understanding that they may change. To protect yourself from future changes, copying the code for the function into your codebase is another alternative.

**Comment by xeroxnir** [comment]
Will the helper functions be guaranteed to be in the future core modules is moved from "experimental" stability to "stable"?

**Comment by biffgaut** [comment]
No, the helper functions are not part of the published interface.
