### ISSUE TITLE
Pattern Request: aws-apigateway-iot

### ISSUE THREAD

**Issue by iamtb13** [awslabs/aws-solutions-constructs#61]
### Use Case
https -> mqtt proxy
Create a pattern that allows https to talk to an mqtt proxy

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by surukonda** [comment]
I'll be able to help on this request, you can assign it to me.

**Comment by hnishar** [comment]
Suggest change the pattern name to: aws-apigateway-iot, in line with other patterns in the library e.g. aws-apigateway-lambda, aws-apigateway-sqs and aws-apigateway-kinesisstreams

**Comment by hnishar** [comment]
This pattern is published in the latest release v1.66.0
