### ISSUE TITLE
New Pattern: aws-iot-lambda-ssm-parameter

### ISSUE THREAD

**Issue by iamtb13** [awslabs/aws-solutions-constructs#62]
For IOT devices to read from SSM parameter store

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by thomas-le-moullec** [comment]
I can help on this, you can assign to me.

**Comment by hnishar** [comment]
Suggest to break it up into two separate patterns, 1 - aws-lambda-ssm-parameter and 2 - aws-iot-lambda-ssm-parameter to increase re-usability. Similar to [aws-lambda-dynamodb](https://github.com/awslabs/aws-solutions-constructs/tree/master/source/patterns/%40aws-solutions-constructs/aws-lambda-dynamodb) and [aws-iot-lambda-dynamodb](https://github.com/awslabs/aws-solutions-constructs/tree/master/source/patterns/%40aws-solutions-constructs/aws-iot-lambda-dynamodb) Also, check if aws-iot-lambda can be re-used, e.g. [aws-iot-lambda](https://github.com/awslabs/aws-solutions-constructs/tree/master/source/patterns/%40aws-solutions-constructs/aws-iot-lambda) + aws-lambda-ssm-parameter = aws-iot-lambda-ssm-parameter

Also, for 1 - aws-lambda-ssm-parameter, provide the user an option to choose the permissions, e.g. read (default) or read-write, for example, check [here](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/aws-lambda-dynamodb/lib/index.ts#L53)

**Comment by thomas-le-moullec** [comment]
Noted, thanks for suggestion. So 1- lambda-ssm-parameter would be [issue-64](https://github.com/awslabs/aws-solutions-constructs/issues/64) and 2- a combination of issue-64 and [aws-iot-lambda](https://github.com/awslabs/aws-solutions-constructs/tree/master/source/patterns/%40aws-solutions-constructs/aws-iot-lambda). 

I will check the feasibility, in that case we would also need another issue for lambda-secretsmanager (similar to issue64)

**Comment by hnishar** [comment]
Created a new issue for [aws-lambda-secretsmanager](https://github.com/awslabs/aws-solutions-constructs/issues/76)

**Comment by biffgaut** [comment]
aws-lambda-ssmstringparameter was recently released, fulfilling this functionality.
