### ISSUE TITLE
New pattern:  aws-iot-lambda-secretsmanager

### ISSUE THREAD

**Issue by iamtb13** [awslabs/aws-solutions-constructs#63]
For IOT devices to read from secrets manager

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by thomas-le-moullec** [comment]
I can help on this, you can assign to me.

**Comment by hnishar** [comment]
Similar comments as https://github.com/awslabs/aws-solutions-constructs/issues/62 Suggest to break it up into 1 - aws-lambda-secretsmanager and 2 - aws-iot-lambda-secretsmanager

**Comment by thomas-le-moullec** [comment]
Noted, thanks

**Comment by biffgaut** [comment]
aws-lambda-secretsmanager was recently released, fulfilling this functionality.
