### ISSUE TITLE
New pattern: aws-lambda-ssm-parameter

### ISSUE THREAD

**Issue by iamtb13** [awslabs/aws-solutions-constructs#64]
Giving the user an option to choose the permissions, e.g. read (default) or read-write, from SSM parameter store

For example, check [here](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/aws-lambda-dynamodb/lib/index.ts#L53)

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by thomas-le-moullec** [comment]
I can help on this, thank you.

**Comment by purplebari** [comment]
correct name should be aws-lambda-ssmparameter  (compare to aws-kinesisstream-lambda, aws-apigateway-sqs, etc.)

**Comment by danielmatuki** [comment]
Hi @hnishar @biffgaut I am available to start working on this construct.
