### ISSUE TITLE
dynamic partitioning option with bufferingHints size

### ISSUE THREAD

**Issue by JayStevency** [awslabs/aws-solutions-constructs#648]
I encountered a buffer size issue while using the option to dynamically divide s3 by the time in the data. The buffer size was set to at least 64 megabytes, but an error occurred. Is there an option that I missed? I will refer to the settings of props below.

### Reproduction Steps

```typescript
const deliveryProps: KinesisFirehoseToS3Props = {
      kinesisFirehoseProps: {
        deliveryStreamName: `Iofarm${props.dataType}DeliveryStream`,
        deliveryStreamType: 'KinesisStreamAsSource',
        kinesisStreamSourceConfiguration: {
          kinesisStreamArn: sourceStream.streamArn,
          roleArn: firehoseRole.roleArn
        },
        extendedS3DestinationConfiguration: {
          bucketArn: dataLakeBucket.bucketArn,
          bufferingHints: {
            IntervalInSeconds : 60,
            SizeInMBs : 64
          },
          compressionFormat : 'GZIP', 
          dynamicPartitioningConfiguration: {
            enabled: true,
          },
          prefix : `${props.dataType.toLowerCase()}/year=!{partitionKeyFromLambda:year}/month=!{partitionKeyFromLambda:month}/day=!{partitionKeyFromLambda:day}/`,
          errorOutputPrefix: `${props.dataType.toLowerCase()}Error/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/!{firehose:error-output-type}`,
          roleArn: firehoseRole.roleArn,
          processingConfiguration : {
            enabled: true,
            processors : [
              {
                parameters: [
                  {
                    parameterName: 'LambdaArn',
                    parameterValue: transporterLambda.functionArn
                  }
                ],
                type: "Lambda"
              }
            ]
          }
        }
      },
      existingBucketObj: dataLakeBucket
    }
```

### Error Log

![snapshot](https://user-images.githubusercontent.com/13361980/162136771-edab2de9-5e42-4a31-b45e-761392cd47a1.png)

### Environment

  - **CDK CLI Version      :*1.148.0*
  - **CDK Framework Version:*1.148.0*
  - **AWS Solutions Constructs Version     :*1.148.0*
  - **OS                   :*mac os monterey 12.3.1 M1 chip*
  - **Language             :*typescript*

### Other

--- 

This is :bug: Bug Report

**Comment by JayStevency** [comment]
We have confirmed that the cdk code is forcibly fixed to 5 megabytes when it is built. The sizeInMBs value does not build on the bufferingHints option, is it related to other options?

```yaml
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 5
```

**Comment by biffgaut** [comment]
Wow, that's an impressive use case. It goes pretty deep into Kinesis Firehose - while I'm not very deep in that technology myself, I think I've found some stuff that might help. I'll let you be the judge...

From what I can see, CDK sets up extendedS3DestinationConfiguration itself [here](https://github.com/aws/aws-cdk/blob/f8babb8f0f88fec6216bcb5de95ac4ec57be39db/packages/%40aws-cdk/aws-kinesisfirehose-destinations/lib/s3-bucket.ts#L40). It populates the various attributes based on values passed in attributes of the destinations[] S3Bucket. You can see here that not ALL the attributes of extendedS3DestinationConfiguration are populated (e.g. dynamicPartitioningConfiguration). We'll come back to that later.

That code calls createBufferingHints, found [here](https://github.com/aws/aws-cdk/blob/f8babb8f0f88fec6216bcb5de95ac4ec57be39db/packages/%40aws-cdk/aws-kinesisfirehose-destinations/lib/private/helpers.ts#L81). If neither bufferingInterval nor bufferingSize work, then bufferingHints is set to undefined.

I was able to set up a delivery stream with a set Interval and Size with this code:

```
const bucket = new s3.Bucket(this, 'Bucket');

new KinesisFirehoseToS3(this, 'my-test', {
  kinesisFirehoseProps: {
    destinations: [new destinations.S3Bucket(bucket, {
      bufferingSize: cdk.Size.mebibytes(64),
      bufferingInterval: cdk.Duration.seconds(60)
    })],
  }
});

```

This created the following CloudFormation:

```
    "DeliveryStreamF6D5572D": {
      "Type": "AWS::KinesisFirehose::DeliveryStream",
      "Properties": {
        "DeliveryStreamType": "DirectPut",
        "ExtendedS3DestinationConfiguration": {
          "BucketARN": {
            "Fn::GetAtt": [
              "Bucket83908E77",
              "Arn"
            ]
          },
          "BufferingHints": {
            "IntervalInSeconds": 60,
            "SizeInMBs": 64
          },
```

What confuses me is that in your example the CDK is obviously grabbing the dynamicPartitioningConfiguration value from the extendedS3DestinationConfiguration you provide, but not the bufferingHints. I was unable to use your code to replicate the error as it depended upon other CDK resources and when I tried to do it on my own I got tripped up by dynamicPartitioning requirements I didn't understand. You might try using code like my example to set most of the extendedS3DestinationConfiguration values, and use the CDK escape hatch to "manually" add additional attributes.

Hope this helps.

**Comment by biffgaut** [comment]
1.149.0 is released and removes the problematic print statement.

**Comment by JayStevency** [comment]
I already have a firehose that transmits dynamic partitioning in another kinesis stream without using it.
To infer your words, would the buffering hints of other kinesis streams be a problem in the target bucket?

**Comment by biffgaut** [comment]
I believe I have replicated your problem here and discovered a simple solution.

To allow clients to provide partial props objects we abandon type safety by adding  '| any' to the argument types in constructor definitions. While this means you can change a single default prop without specifying every required prop, it also means type checking isn't checking your inputs.

That's what appears is happening here. The attributes of [BufferingHints](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-kinesisfirehose.CfnDeliveryStream.BufferingHintsProperty.html) are intervalInSeconds and sizeInMBs. Your code above hast those attributes in uppercase (IntervalInSeconds and SizeInMBs). I was able to launch this code:

```
new KinesisFirehoseToS3(this, 'my-test', {
  kinesisFirehoseProps:  {
    deliveryStreamName: 'my-stream',
    deliveryStreamType: 'DirectPut',
    extendedS3DestinationConfiguration: {
      roleArn: myRoleArn,
      bucketArn: bucket.bucketArn,
      bufferingHints: {
        intervalInSeconds: 60,
        sizeInMBs : 64
      },
      prefix : `mystream/year=!{partitionKeyFromLambda:year}/month=!{partitionKeyFromLambda:month}/day=!{partitionKeyFromLambda:day}/`,
      errorOutputPrefix: `mystreamError/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/!{firehose:error-output-type}`,
      compressionFormat : 'GZIP', 
      dynamicPartitioningConfiguration: {
        enabled: true,
      },
      processingConfiguration : {
        enabled: true,
        processors : [
          {
            parameters: [
              {
                parameterName: 'LambdaArn',
                parameterValue: anylambda.functionArn
              }
            ],
            type: "Lambda"
          }
        ]
      }
    },
  }
});
```

When I changed the attributes of bufferingHints to upper case I got the same error you are seeing. If you change your code to:

```
      bufferingHints: {
        intervalInSeconds: 60,
        sizeInMBs : 64
      },
```

I believe you will be able to launch your stack.

**Comment by JayStevency** [comment]
😱😱 OMG, I made this mistake because I didn't get a Type hint.
Thanks to you, I was able to find my stupid mistake. Thank you very much.

**Comment by JayStevency** [comment]
```typescript
new KinesisFirehoseToS3(this, `Iocrops${props.dataType}DatalakeStream`, {
      kinesisFirehoseProps: {
        deliveryStreamName: `Iofarm${props.dataType}DeliveryStream`,
        deliveryStreamType: 'KinesisStreamAsSource',
        kinesisStreamSourceConfiguration: {
          kinesisStreamArn: sourceStream.streamArn,
          roleArn: firehoseRole.roleArn
        },
        extendedS3DestinationConfiguration: {
          bucketArn: dataLakeBucket.bucketArn,
          compressionFormat : 'GZIP',
          dynamicPartitioningConfiguration: {
            enabled: true
          },
          bufferingHints: {
            intervalInSeconds: 60,
            sizeInMBs: 64
          },
          prefix : `${props.dataType.toLowerCase()}/year=!{partitionKeyFromLambda:year}/month=!{partitionKeyFromLambda:month}/day=!{partitionKeyFromLambda:day}/`,
          errorOutputPrefix: `errors/${props.dataType.toLowerCase()}/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/!{firehose:error-output-type}`,
          roleArn: firehoseRole.roleArn,
          processingConfiguration : {
            enabled: true,
            processors : [
              {
                parameters: [
                  {
                    parameterName: 'LambdaArn',
                    parameterValue: transporterLambda.functionArn
                  }
                ],
                type: "Lambda"
              }
            ]
          }
        }
      },
      existingBucketObj: dataLakeBucket
    });
```

I finally got the result I wanted.

```yaml
IocropsAlgorithmDatalakeStreamKinesisFirehose79C5811B:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: IofarmAlgorithmDeliveryStream
      DeliveryStreamType: KinesisStreamAsSource
      ExtendedS3DestinationConfiguration:
        BucketARN:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :s3:::iocrops-data-lake
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 64
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName:
            Ref: IocropsAlgorithmDatalakeStreamfirehoseloggroup09B9B376
          LogStreamName:
            Ref: IocropsAlgorithmDatalakeStreamfirehoseloggroupfirehoselogstream23BFDEC0
        CompressionFormat: GZIP
        DynamicPartitioningConfiguration:
          Enabled: true
```

**Comment by biffgaut** [comment]
Glad to hear it! Thanks for using Solutions Constructs.
