### ISSUE TITLE
curious about the CWAlerm threshold for kinesis.

### ISSUE THREAD

**Issue by watany-dev** [awslabs/aws-solutions-constructs#663]
https://github.com/awslabs/aws-solutions-constructs/blob/5124e47a6d3bf2cd4196148041b51cbc7b8aebe2/source/patterns/%40aws-solutions-constructs/core/lib/kinesis-streams-helper.ts#L66

Question about this place.
The threshold is 2592000, but isn't what this number represents 30 days to the second? I didn't understand it when I actually made it.
I believe the 12 hours in the comment refers to 43,200 seconds!

### Reproduction Steps

cdk deploy

### Error Log

no.

### Environment

  - **CDK CLI Version      :2.20**
  - **CDK Framework Version:2.20**
  - **AWS Solutions Constructs Version     :2.05**
  - **OS                   :Amazonlinux2**
  - **Language             :Typescript**

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
This certainly looks like an error. We'll discuss it as a team and look at addressing it. Thanks.

**Comment by biffgaut** [comment]
Fixed in PR #667, will be released in 1.153.0 and 2.6.0

**Comment by Benjscho** [comment]
Asking for clarity here, isn't the metric in Milliseconds, not seconds? (GetRecords.**IteratorAgeMilliseconds**)

Not sure how the original threshold number was arrived at, but as it stands it seems like the threshold should be increased by 10^3

**Comment by biffgaut** [comment]
It sure looks like you are correct - we'll look a little closer and update accordingly unless other info comes to light. Thanks.
