### ISSUE TITLE
ARNs use `aws` as partition

### ISSUE THREAD

**Issue by dscpinheiro** [awslabs/aws-solutions-constructs#67]
In some places of the Constructs library, ARNs are built using the string `aws` as the partition. For instance:

https://github.com/awslabs/aws-solutions-constructs/blob/50d3e9c52ffded63c0722c18f450da08cf2f77c5/source/patterns/%40aws-solutions-constructs/aws-kinesisfirehose-s3/lib/index.ts#L95-L100

https://github.com/awslabs/aws-solutions-constructs/blob/2740df769f4d20e8cdd6b6ec27a1e4115d4fa060/source/patterns/%40aws-solutions-constructs/core/lib/lambda-helper.ts#L66

https://github.com/awslabs/aws-solutions-constructs/blob/abddeed6ae0d60f2af5a89aee170696bb4677810/source/patterns/%40aws-solutions-constructs/core/lib/apigateway-helper.ts#L46

This can cause problems when deploying to AWS China or AWS GovCloud (US) regions.

### Environment
  - **CDK CLI Version      :** 1.63.0
  - **AWS Solutions Constructs Version     :** 1.63.0

### Other
Suggestion is to use the `PARTITION` property of the `Aws` class in the CDK:

```typescript
resources: [`arn:${cdk.Aws.PARTITION}:logs:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:log-group:/aws/lambda/*`]
```

--- 

This is :bug: Bug Report

**Comment by hnishar** [comment]
This has been fixed in v1.64.0
