### ISSUE TITLE
Partial Build instructions in CONTRIBUTING.md seems incomplete

### ISSUE THREAD

**Issue by mbonig** [awslabs/aws-solutions-constructs#7]
After following the CONTRIBUTING for the full build, I went on to the partial build.

In the `source/patterns/@aws-solutions-constructs/aws-dynamodb-stream-lambda` directory I see this error when running the `npm run build+lint+test`:

```
Error: Error: Unable to locate jsii assembly for "eslint". If this module is not jsii-enabled, it must also be declared under bundledDependencies.
```

Additionally, running `npm run test` fails from a missing jest dep.

### Reproduction Steps

Create a clean repo and follow the steps from the CONTRIBUTING for the full build and then partial build.

### Environment

  - **CDK CLI Version      :** 1.46.0
  - **CDK Framework Version:**  1.46.0
  - **AWS Solutions Constructs Version     :**  1.46.0
  - **OS                   :** Linux
  - **Language             :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by hnishar** [comment]
mbonig@ Can you try the following command from ../aws-solutions-constructs/source directory and see if that addresses both the issue?

.../aws-solutions-constructs/source$ export PATH=$(npm bin):$PATH

**Comment by mbonig** [comment]
I'm having a few issues running the command now. I keep getting errors about jsii and now eslint not being found:

```
sh: eslint: command not found
```

To get past these I'm installing them via npm into the global library:

`npm i -g jsii eslint tslint typescript jest`

Should these be part of the container? The list keeps going. I can't seem to get everything installed, it's now also complaining about cdk-integ-assert. Is there a step I missed for getting all of these things installed?

**Comment by hnishar** [comment]
Did the "Full Build" (steps below) work for you? At least till the point where it kicks off building the "core" module.. 

$ cd <root-of-aws-solutions-constructs-repo>
$ docker run --rm --net=host -it -v $PWD:$PWD -w $PWD jsii/superchain
docker$ cd deployment
docker$ ./build-patterns.sh

build-patterns.sh has steps to install all the dependencies (jsii, eslint, tsc, etc.) in aws-solutions-constructs/source/npm_modules/.. for "cdk-integ-assert", its built in its own directory (source/tools/cdk-integ-assert) and made accessible via "npm link"

Once the above steps complete successfully, you can then run the partial build steps.

**Comment by mbonig** [comment]
I thought I had but just started over from scratch and the full build errors out with this:

```
@aws-solutions-constructs/aws-lambda-dynamodb: /home/matt/projects/cdk-sandbox/aws-solutions-constructs/source/patterns/@aws-solutions-constructs/aws-lambda-dynamodb/cdk.out/asset.0c3255e93ffe7a906c7422e9f0e9cc4c7fd86ee996ee3bb302e2f134b38463c8/index.js
@aws-solutions-constructs/aws-lambda-dynamodb:   0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
@aws-solutions-constructs/aws-lambda-dynamodb: The file does not match your project config: cdk.out/asset.0c3255e93ffe7a906c7422e9f0e9cc4c7fd86ee996ee3bb302e2f134b38463c8/index.js.
@aws-solutions-constructs/aws-lambda-dynamodb: The file must be included in at least one of the projects provided
@aws-solutions-constructs/aws-lambda-dynamodb: ✖ 1 problem (1 error, 0 warnings)

```

I'm working off of commit `078015520d248d80a8e1697aa0a86b3eedea8c3e` with no local changes to that file

**Comment by hnishar** [comment]
Are you certain that 'build-patterns.sh' is excuting inside the docker container ? 

I just spin up a Cloud9 instance (Amazon Linux) and tested the "Full Build" steps successfully...

$ cd .../aws-solutions-constructs
$ docker run --rm --net=host -it -v $PWD:$PWD -w $PWD jsii/superchain  <-- Check if this drops you into a docker container shell 
docker$ cd deployment
docker$ ./build-patterns.sh

**Comment by mbonig** [comment]
Alright. I'm sure I was doing all of that but now I'm starting over from scratch with the latest (And no local changes). It runs for 20+ minutes and then fails here:

```
@aws-solutions-constructs/aws-cloudfront-s3: [jsii-pacmak] [WARN] Exception occurred, not cleaning up /tmp/npm-packR41Q2R
@aws-solutions-constructs/aws-cloudfront-s3: Error: Process exited with status 1
@aws-solutions-constructs/aws-cloudfront-s3: Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
@aws-solutions-constructs/aws-cloudfront-s3: Copyright (C) Microsoft Corporation. All rights reserved.
@aws-solutions-constructs/aws-cloudfront-s3:   Determining projects to restore...
@aws-solutions-constructs/aws-cloudfront-s3: /usr/share/dotnet/sdk/3.1.301/NuGet.targets(128,5): warning : Too many open files [/tmp/npm-packR41Q2R/JsiiBuild.sln]
@aws-solutions-constructs/aws-cloudfront-s3: /tmp/npm-packR41Q2R/Amazon.Constructs.AWS.CloudfrontS3/Amazon.Constructs.AWS.CloudfrontS3.csproj : error NU1101: Unable to find package Amazon.Constructs. No packages exist with this id in source(s): local-0, nuget.org [/tmp/npm-packR41Q2R/JsiiBuild.sln]
@aws-solutions-constructs/aws-cloudfront-s3:   Failed to restore /tmp/npm-packR41Q2R/Amazon.Constructs.AWS.CloudfrontS3/Amazon.Constructs.AWS.CloudfrontS3.csproj (in 2.1 sec).
@aws-solutions-constructs/aws-cloudfront-s3: Build FAILED.
@aws-solutions-constructs/aws-cloudfront-s3: /usr/share/dotnet/sdk/3.1.301/NuGet.targets(128,5): warning : Too many open files [/tmp/npm-packR41Q2R/JsiiBuild.sln]
@aws-solutions-constructs/aws-cloudfront-s3: /tmp/npm-packR41Q2R/Amazon.Constructs.AWS.CloudfrontS3/Amazon.Constructs.AWS.CloudfrontS3.csproj : error NU1101: Unable to find package Amazon.Constructs. No packages exist with this id in source(s): local-0, nuget.org [/tmp/npm-packR41Q2R/JsiiBuild.sln]
@aws-solutions-constructs/aws-cloudfront-s3:     1 Warning(s)
@aws-solutions-constructs/aws-cloudfront-s3:     1 Error(s)
@aws-solutions-constructs/aws-cloudfront-s3: Time Elapsed 00:00:04.03
@aws-solutions-constructs/aws-cloudfront-s3:     at ChildProcess.child.once (/Users/matthewbonig/projects/cdk-sandbox/aws-solutions-constructs/source/node_modules/jsii-pacmak/lib/util.js:57:31)
@aws-solutions-constructs/aws-cloudfront-s3:     at Object.onceWrapper (events.js:286:20)
@aws-solutions-constructs/aws-cloudfront-s3:     at ChildProcess.emit (events.js:198:13)
@aws-solutions-constructs/aws-cloudfront-s3:     at maybeClose (internal/child_process.js:982:16)
@aws-solutions-constructs/aws-cloudfront-s3:     at Socket.stream.socket.on (internal/child_process.js:389:11)
@aws-solutions-constructs/aws-cloudfront-s3:     at Socket.emit (events.js:198:13)
@aws-solutions-constructs/aws-cloudfront-s3:     at Pipe._handle.close (net.js:607:12)
@aws-solutions-constructs/aws-cloudfront-s3: error Command failed with exit code 1.
```

**Comment by hnishar** [comment]
That could be due to due to space limitation or something else, will look into refactoring the build script to remove the [jsii-pacmak] for local built/test, but at this point you're good to go with any local development and partial builds (from within the docker container)

**Comment by mbonig** [comment]
I'm still running into an issue with all those deps. Here's my history (on a fresh clone of the repo):

1  cd deployment/
1  ./build-patterns.sh 
1  cd ..
1  cd source/patterns/\@aws-solutions-constructs/aws-lambda-dynamodb/
1  npm run build+lint+test

and the results:

```
bash-4.2# npm run build+lint+test

> @aws-solutions-constructs/aws-lambda-dynamodb@1.47.0 build+lint+test /home/matt/projects/cdk-sandbox/aws-solutions-constructs/source/patterns/@aws-solutions-constructs/aws-lambda-dynamodb
> npm run jsii && npm run lint && npm test && npm run integ-assert


> @aws-solutions-constructs/aws-lambda-dynamodb@1.47.0 jsii /home/matt/projects/cdk-sandbox/aws-solutions-constructs/source/patterns/@aws-solutions-constructs/aws-lambda-dynamodb
> jsii

sh: jsii: command not found
```

**Comment by hnishar** [comment]
Sorry that you have to struggle with the build steps, the missing step is "export PATH=$(npm bin):$PATH" as shown below, will update the contributing guide for the next release..

1 cd deployment/
2 ./build-patterns.sh (this completed successfully this time)
3 cd ../source   <--- Note: Switch to source directory 
4 export PATH=$(npm bin):$PATH   <--- Additional step to source the dependencies from source/node_modules/.bin
5 cd source/patterns/@aws-solutions-constructs/aws-lambda-dynamodb/
6 npm run build+lint+test

**Comment by mbonig** [comment]
That seems to be working better now that I've got that path setup. Is that something you could add to the build-patterns.sh script to execute automatically?

**Comment by hnishar** [comment]
Yes, taking all the feedback from here to update the build-patterns.sh and CONTRIBUTING guide, thanks for your feedback!

**Comment by hnishar** [comment]
mbonig@ Thanks for all your feedback, the CONTRIBUTING guide and the build script has been updated in v1.48.0
