### ISSUE TITLE
Can't specify cognitoUserPoolClientProps on aws-cognito-apigateway-lambda

### ISSUE THREAD

**Issue by purplebari** [awslabs/aws-solutions-constructs#71]
cognitoUserPoolClientProps has a required property, userPool, that isn't available in the before construct is instantiated - so although cognitoUserPoolClientProps is made available in construct properties, it cannot be specified. One solution would be relax the type requirements of cognitoUserPoolClientProps by adding  | any to the type specification of the property.

```
    const api = new CognitoToApiGatewayToLambda(
      this,
      'example',
      {
        cognitoUserPoolClientProps: {
          userPool: // No idea what to put here, but must specify something
        },
        lambdaFunctionProps: {
          code: lambda.Code.fromAsset(`lambda`),
          runtime: lambda.Runtime.NODEJS_12_X,
          handler: "handler.handler",
        }
        }
      }
    );
```

**Comment by hnishar** [comment]
This has been fixed in v1.64.0
