### ISSUE TITLE
New pattern: aws-events-rule-kinesisfirehose-s3

### ISSUE THREAD

**Issue by aijunpeng** [awslabs/aws-solutions-constructs#72]
Build a new pattern to send cloudwatch event data to kinesis firehose then to s3 when a cloudwatch event rule is triggered

### Use Case
Need this pattern to send cloudwatch event data to kinesis firehose then to s3 when a cloudwatch event rule is triggered

### Proposed Solution
Build an aws-events-rule-kinesisfirehose-s3 pattern:
Create a CloudWatch Events Rule, kinesis firehose delivery stream, s3 bucket and relevant roles/permissions
Set kinesis firehose delivery stream as the target of the cw event rule
Set s3 as the target of the kinesis firehose delivery stream
Enable server-side kms encryption for kinesis firehose delivery stream

### Other

* [✅  ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hnishar** [comment]
aijunpeng@ Please make use of the existing `aws-kinesisfirehose-s3` pattern, for reference check out [`aws-iot-kinesisfirehose-s3`](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/aws-iot-kinesisfirehose-s3/lib/index.ts) which connects the IoT TopicRule with `aws-kinesisfirehose-s3`

**Comment by hnishar** [comment]
This pattern has been published in the latest release v1.70.0
