### ISSUE TITLE
Error while chaining of aws-cloudfront-s3 & aws-wafwebacl-cloudfront constructs

### ISSUE THREAD

**Issue by surukonda** [awslabs/aws-solutions-constructs#723]
Chaining aws-cloudfront-s3 and aws-wafwebacl-cloudfront with basic implementation results in error.

### Reproduction Steps

```javascript
import {  Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { CloudFrontToS3 } from '@aws-solutions-constructs/aws-cloudfront-s3';
import { WafwebaclToCloudFront } from '@aws-solutions-constructs/aws-wafwebacl-cloudfront';

export class WafToCloudfrontTest extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);
    const cloudfrontToS3 = new CloudFrontToS3(this, 'cloudfronttos3', {});
    new WafwebaclToCloudFront(this, `waftocloudfront`, {
      existingCloudFrontWebDistribution: cloudfrontToS3.cloudFrontWebDistribution
    });
  }
}
```

### Error Log

```
6:06:08 PM | CREATE_FAILED        | AWS::WAFv2::WebACL                              | waftocloudfrontwaf...rontWebACLE497B853
Resource handler returned message: "Error reason: The scope is not valid., field: SCOPE_VALUE, parameter: CLOUDFRONT (Service: Wafv2, Status Code: 400, R
equest ID: 856b0222-0987-483a-a528-f6d679bde905, Extended Request ID: null)" (RequestToken: 285f84e6-7dfd-e04e-4028-21385c1ccf1d, HandlerErrorCode: Inval
idRequest)
```

### Environment

  - **CDK CLI Version      :2.25.0**
  - **CDK Framework Version:2.25.0**
  - **AWS Solutions Constructs Version     :2.9.0**
  - **OS                   : MacOS Montery (12.4)**
  - **Language             : Typescript**

### Other

--- 

This is :bug: Bug Report

**Comment by mickychetta** [comment]
Hello, I was able to successfully deploy the code with these environment settings:

CDK CLI Version :2.26.0
CDK Framework Version:2.260
AWS Solutions Constructs Version :2.9.0
OS : MacOS Big Sur (11.6.5)
Language : Typescript

For CLOUDFRONT, you must create your `[WAFv2](https://docs.aws.amazon.com/waf/latest/APIReference/Welcome.html)` resources in the US East (N. Virginia) Region, `us-east-1`.

**Comment by surukonda** [comment]
Thanks @mickychetta , I was using `ap-south-1`, may be that is reason for failure. I'll check check it from my end.
