### ISSUE TITLE
[aws-kinesisfirehose-s3] Question on property type / Unable to use Kinesis data stream as a source

### ISSUE THREAD

**Issue by dscpinheiro** [awslabs/aws-solutions-constructs#73]
I have two questions about the `aws-kinesisfirehose-s3` pattern (please let me know if it makes more sense to split them into different issues):
1. Is there a reason why `kinesisFirehoseProps`'s type is `kinesisfirehose.CfnDeliveryStreamProps | any`? This is the same type definition as `aws-iot-kinesisfirehose-s3`, but not `aws-kinesisfirehose-s3-and-kinesisanalytics`.

https://github.com/awslabs/aws-solutions-constructs/blob/50d3e9c52ffded63c0722c18f450da08cf2f77c5/source/patterns/%40aws-solutions-constructs/aws-iot-kinesisfirehose-s3/lib/index.ts#L39

https://github.com/awslabs/aws-solutions-constructs/blob/50d3e9c52ffded63c0722c18f450da08cf2f77c5/source/patterns/%40aws-solutions-constructs/aws-kinesisfirehose-s3-and-kinesisanalytics/lib/index.ts#L33

Because of that, VSCode cannot show me the properties from `CfnDeliveryStreamProps`:

![Screen Shot 2020-09-21 at 12 37 19 PM](https://user-images.githubusercontent.com/3842788/93796083-d5db5000-fc29-11ea-9fed-a4cdb38a3894.png)

2. Kinesis Firehose supports [two types](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesisfirehose-deliverystream.html#cfn-kinesisfirehose-deliverystream-deliverystreamtype) (`DirectPut` and `KinesisStreamAsSource`). As of now, it isn't very straightforward to use `KinesisStreamAsSource`, as the configuration for it (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-kinesisstreamsourceconfiguration.html) requires the customer to pass the ARN of the role _that provides access to the source Kinesis data stream_ (which is not available until after the construct is created). Does it make sense to create a separate pattern (e.g. `aws-kinesisstreams-kinesisfirehose-s3`) or modify this one to handle both scenarios?

--- 

This is :bug: Bug Report

**Comment by hnishar** [comment]
dscpinheiro@, 

1.  `kinesisFirehoseProps`'s type is `kinesisfirehose.CfnDeliveryStreamProps | any` to allow for user to override the `extendedS3DestinationConfiguration` properties without requiring to specify the `bucketArn` which is created by the construct. For example, this [test case](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/aws-kinesisfirehose-s3/test/test.kinesisfirehose-s3.test.ts#L82) will not even compile if ` | any` is dropped. Probably the same should apply for `aws-kinesisfirehose-s3-and-kinesisanalytics` pattern as well.

2. Agree, it makes sense to create a new pattern `aws-kinesisstreams-kinesisfirehose-s3` but internally it should still make use of `aws-kinesisfirehose-s3` pattern similar to `aws-iot-kinesisfirehose-s3`

**Comment by dscpinheiro** [comment]
>     1. `kinesisFirehoseProps`'s type is `kinesisfirehose.CfnDeliveryStreamProps | any` to allow for user to override the `extendedS3DestinationConfiguration` properties without requiring to specify the `bucketArn` which is created by the construct. For example, this [test case](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/aws-kinesisfirehose-s3/test/test.kinesisfirehose-s3.test.ts#L82) will not even compile if ` | any` is dropped. Probably the same should apply for `aws-kinesisfirehose-s3-and-kinesisanalytics` pattern as well.

I get it, that makes sense. It's a bit unfortunate, but I can create the props separately to get intellisense.

```typescript
const props: CfnDeliveryStreamProps = { ... };
new KinesisFirehoseToS3(this, 'KdfToS3', { kinesisFirehoseProps: props });
```

Hopefully this will improve when there's a L2 construct for Firehose.

---

>     2. Agree, it makes sense to create a new pattern `aws-kinesisstreams-kinesisfirehose-s3` but internally it should still make use of `aws-kinesisfirehose-s3` pattern similar to `aws-iot-kinesisfirehose-s3`

I'll create a separate ticket for this new pattern.
