### ISSUE TITLE
New pattern: aws-kinesisstreams-kinesisfirehose-s3

### ISSUE THREAD

**Issue by dscpinheiro** [awslabs/aws-solutions-constructs#74]
Originally reported on #73 

Kinesis Firehose supports two types (DirectPut and KinesisStreamAsSource). As of now, it isn't very straightforward to use KinesisStreamAsSource in the existing `aws-kinesisfirehose-s3` pattern, since the configuration for it (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-kinesisstreamsourceconfiguration.html) requires the customer to pass the ARN of the role that provides access to the source Kinesis data stream (which is not available until after the construct is created).

Recommendation is to create a new pattern `aws-kinesisstreams-kinesisfirehose-s3`(internally it should still make use of `aws-kinesisfirehose-s3`, similar to `aws-iot-kinesisfirehose-s3`).

* [x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by hnishar** [comment]
Published the pattern in the latest release v1.68.0
