### ISSUE TITLE
New pattern: aws-apigateway-sagemakerendpoint

### ISSUE THREAD

**Issue by dscpinheiro** [awslabs/aws-solutions-constructs#75]
This new pattern is similar to the existing `aws-apigateway-sqs` pattern, but the service integration is with a SageMaker endpoint. The experience will be similar to the one described on this blog post: https://aws.amazon.com/blogs/machine-learning/creating-a-machine-learning-powered-rest-api-with-amazon-api-gateway-mapping-templates-and-amazon-sagemaker/

The main difference with this pattern is that only a `GET` method is made available (which will call the `invoke-endpoint` API). Also, since each ML use case is unique, the construct will require certain properties (such as resource path and request mapping template) to be provided.

### Use Case
API Gateway provides a layer of abstraction from the endpoint. This layer of abstraction enables custom authentication approaches and control quotas for specific consumers.

### Proposed Solution
| **Name**     | **Type**        |
|:-------------|:----------------|
|apiGatewayProps?|[`api.RestApiProps`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.RestApiProps.html)|
|resourcePath|`string`|
|endpointName|`string`|
|requestMappingTemplate|`string`|
|responseMappingTemplate?|`string`|

Example usage:
```typescript
new ApiGatewayToSagemakerEndpoint(this, 'ApiGwSagemaker', {
    apiGatewayProps: {},
    resourcePath: '/predicted-ratings/{user_id}',
    endpointName: 'some-name',
    requestMappingTemplate: 'some-template',
    responseMappingTemplate: 'some-template'
});
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hnishar** [comment]
Published the pattern in the latest release v1.68.0
