### ISSUE TITLE
New pattern: aws-lambda-secretsmanager

### ISSUE THREAD

**Issue by hnishar** [awslabs/aws-solutions-constructs#76]
Giving the user an option to choose the permissions, e.g. read (default) or read-write, from AWS Secrets Manager

For example, check [here](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/aws-lambda-dynamodb/lib/index.ts#L53)

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by thomas-le-moullec** [comment]
I can help on this, thank you.

**Comment by maria-jackson** [comment]
I'm super excited about this construct! 🥇 

In @hnishar's example, there is a nice addition of using the DDB_TABLE_NAME as an environment variable. Is it possible that the new construct can have this functionality and the ability to pass in the name of the environment variable? 

I can think of cases where a lambda would need access to multiple secrets. If you could pass the variable name, you could use this construct more than once for a single lambda. (Using the existing lambda from the first use of the construct.)

`this.lambdaFunction.addEnvironment('DDB_TABLE_NAME', this.dynamoTable.tableName);`

**Comment by ammoheim** [comment]
I can pick this up. Please assign to me.

**Comment by biffgaut** [comment]
@maria-jackson - Good idea. We just added that capability for other resources paired with Lambda functions, we will include it here.
