### ISSUE TITLE
python AWS EKS cluster setup tutorial is returning type errors

### ISSUE THREAD

**Issue by hzhang20902** [awslabs/aws-solutions-constructs#812]
I am following the [EKS full management tutorial](https://aws.amazon.com/getting-started/guides/deploy-webapp-eks/module-one/) as close as possible, granted their CDK version is 1.121.0 as of this writing, and I just installed CDK 2.42.1. 
With the removal of "core", the imports changed slightly, but everything else is exactly the same when I "cdk init app".

### Reproduction Steps

`    eks_cluster = eks.Cluster(
            self, id=f"{construct_id}-cluster", 
            cluster_name=f"{construct_id}-cluster", 
            vpc=vpc, 
            vpc_subnets=vpc.public_subnets,
            masters_role=iam_role, 
            default_capacity_instance=ec2.InstanceType.of(ec2.InstanceClass.BURSTABLE2, ec2.InstanceSize.MICRO), 
            version=eks.KubernetesVersion.V1_20,
        )
`

The vpc variable is defined as such:

`vpc = ec2.Vpc.from_lookup(self, id="VPC", is_default=True)`

After setting everything up, and running 'cdk deploy' on the cluster folder, I get this:

### Error Log

"TypeError: type of argument vpc_subnets must be one of (Sequence[Union[aws_cdk.aws_ec2.SubnetSelection, Dict[str, Any]]], NoneType); got list instead"

In the toot code they write 'vpc_subnets=vpc.public_subnets' under the eks.Cluster params, and that is apparently just returning a list. So I wrapped it in 'Sequence[vpc.public_subnets]' and now the new error is:

"TypeError: Parameters to generic types must be types. Got [<jsii._reference_map.InterfaceDynamicProxy object at 0x10bbdbd90>, <jsii._reference_map.InterfaceDy."

### Environment

  - **CDK CLI Version      : 2.42.1**
  - **CDK Framework Version: ??**
  - **AWS Solutions Constructs Version     : ??**
  - **OS                   : Catalina 10.15.14**
  - **Language             : Python**

### Other

I don't actually know Python very well, my experience is in ReactSpring architecture and JS/TS/Java, and I have dockerized apps with that architecture and deployed them through K8s kubectl manually. So while it makes sense conceptually going through this code, I'm not too specifically knowledgable on python syntax/architecture, so I'm sorry if this is just a really simple mistake.

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
This repo is AWS Solutions Constructs, a growing library of patterns to help create workloads quickly. I think you're in the wrong place, at this point we have no functionality with EKS at all. You might be able to get some assistance by:

1) Opening a ticket with AWS Support
2) Click on the feedback icon on the right side of the browser
3) Opening a issue on the [AWS CDK](https://github.com/aws/aws-cdk) repo

**Comment by hzhang20902** [comment]
> This repo is AWS Solutions Constructs, a growing library of patterns to help create workloads quickly. I think you're in the wrong place, at this point we have no functionality with EKS at all. You might be able to get some assistance by:
> 
> 1. Opening a ticket with AWS Support
> 2. Click on the feedback icon on the right side of the browser
> 3. Opening a issue on the [AWS CDK](https://github.com/aws/aws-cdk) repo

oh dang, sorry. I'm just really confused by all the different services and seemingly some are legacy and some are updated with CDK v2. Trying to make sense of it all.
So just to clarify, AWS Solutions Constructs, while being an ext of CDK, has nothing to do with Constructs from aws_cdk/core (or lib in v2)? is Constructs 10 to 11 even still part of lib?

**Comment by biffgaut** [comment]
Solutions Constructs is built on CDK - we're an extension of CDK, but we're a separate team and build on top of the same interfaces that are exposed to the entire world. I'm not sure what you mean by Constructs 10 to 11.
