### ISSUE TITLE
No POST endpoint for aws-apigateway-sqs

### ISSUE THREAD

**Issue by FBosler** [awslabs/aws-solutions-constructs#819]
## Description of the bug:
As per the [documentation](https://docs.aws.amazon.com/solutions/latest/constructs/aws-apigateway-sqs.html) there should be a POST endpoint for the API gateway. However, when deploying the stack, I only get a GET endpoint. Maybe I am just not getting something here.

<img width="537" alt="image" src="https://user-images.githubusercontent.com/14016698/194362416-f1972d97-868d-4896-851a-fe797b42aab5.png">

I might be off here, but I think adding the SQS proxy doesn't work anymore (it's also gone from the AWS Console Interface)

### Reproduction Steps

Go through the documentation [here](https://docs.aws.amazon.com/solutions/latest/constructs/aws-apigateway-sqs.html).

### Error Log
No Error

### Environment

  - **CDK CLI Version      : 2.45.0 (build af1fb7c)**
  - **CDK Framework Version: v2**
  - **AWS Solutions Constructs Version     : 2.25.0**
  - **OS                   : Monterey 12.6**
  - **Language             : Typescript**

This is :bug: Bug Report

**Comment by FBosler** [comment]
**Update:** Not really a bug, but just documentation that is somewhat misleading. To also get the POST-method it is necessary to set `allowCreateOperation` Prop to `true` (it is None by default)

**Comment by biffgaut** [comment]
Have you tried setting the authorizationType on RestApiProps.defaultMethodOptions?

```
            defaultMethodOptions: {
                authorizationType: api.AuthorizationType.NONE
            }
```

You can choose IAM, CUSTOM, COGNITO or NONE
(sorry for the delay in responding to this initially)
