### ISSUE TITLE
aws-apigateway-lambda based on an OpenAPI specification

### ISSUE THREAD

**Issue by drissamri** [awslabs/aws-solutions-constructs#840]
API Gateways are often described by using the OpenAPI/Swagger specification, it feels like make sense that having a construct that generates the API Gateway based on an API specification would make sense.

### Use Case

Perform contract-first development of APIs and generate the API Gateway based on the contract. 

### Proposed Solution

Pass in the openapi.yaml and one ore multiple Lambda functions. 
An example of a OpenAPI API Gateway based can be found here: https://github.com/drissamri/cdk-examples/blob/main/rest-api-public/typescript/cdk/lib/api-stack.ts

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
Thanks, we'll take a look.

**Comment by biffgaut** [comment]
We really like the feature, but it's not really what we do (connect CDK L2 constructs in a well architected way) - if this were to appear in our constructs the natural next step would be to add it to the L2 API Gateway CDK construct. Our advice would be to submit it as an added feature to the CDK API Gateway construct.

**Comment by drissamri** [comment]
I might misunderstand, but as there is already a L2 construct that is being used with [SpecRestApi](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.SpecRestApi.html) it seems like there is value in connecting this with all best practises included like you said?

**Comment by biffgaut** [comment]
OK, give us a bit to go back and check that out - thanks.

**Comment by drissamri** [comment]
It was indeed my assumption that it would be under a different pattern like `aws-apigateway-openapi-lambda` 
Most of the code could/would be the same as the current pattern besides the setup of the `RestApi` construct replaced with the `SpecRestApi`. 

I think in general this is seen as a best practise to have API contract first development, so this construct definitely seems to deserve its own spot to guide devs to a good setup.

**Comment by biffgaut** [comment]
We like this idea and are going to look into it early in 2023.

**Comment by mattiamatrix** [comment]
It would also be great to have `aws-openapigateway-kinesisstreams` reusing the same code. I opened #913

**Comment by mattiamatrix** [comment]
Hello, when do you expect to release https://github.com/awslabs/aws-solutions-constructs/pull/912?

**Comment by biffgaut** [comment]
We're very close, but have been temporarily sidetracked. Keep watch, when we get back to it we should finish it quickly.

**Comment by thoroc** [comment]
Is this not released? https://github.com/awslabs/aws-solutions-constructs/tree/main/source/patterns/%40aws-solutions-constructs/aws-apigateway-lambda

**Comment by biffgaut** [comment]
Yes, it has been released - we neglected to update/close this issue. Thanks.
