### ISSUE TITLE
feat(new construct): aws-fargate-kinesisstream

### ISSUE THREAD

**Issue by biffgaut** [awslabs/aws-solutions-constructs#843]
As we increase our coverage of Kinesis services, the ability to write to a Kinesis Data Stream from various types of compute enables larger architectures.

### Proposed Solution

The interfaces for Kinesis Data Streams and Fargate containers are defined. New Kinesis constructs on the way may alter the naming shown in this Issue.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by georgebearden** [comment]
Implemented in #877
