### ISSUE TITLE
ApiGatewayToDynamoDB: add support for integration response templates

### ISSUE THREAD

**Issue by fargito** [awslabs/aws-solutions-constructs#847]
Hello, I would like to add support for response templates in `ApiGatewayToDynamoDB` construct.

### Use Case

I am trying to use the `ApiGatewayToDynamoDB` construct, and I would like to receive a clean response as an output, instead of the raw DynamoDB response.

### Proposed Solution

I think the easiest solution would to add optional response templates in https://github.com/awslabs/aws-solutions-constructs/blob/7ace08ff2cd288e1c1a63d03e79789f659b38097/source/patterns/@aws-solutions-constructs/aws-apigateway-dynamodb/lib/index.ts:
- `createResponseTemplate`: optional `string`
- `readResponseTemplate`: optional `string`
- `deleteResponseTemplate`: optional `string`
- `updateResponseTemplate`: optional `string`

and pass them to `addProxyMethodToApiResource`.

It would also require to edit the `addProxyMethodToApiResource` in 
https://github.com/awslabs/aws-solutions-constructs/blob/7ace08ff2cd288e1c1a63d03e79789f659b38097/source/patterns/@aws-solutions-constructs/core/lib/apigateway-helper.ts.

WDYT?

---

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by georgebearden** [comment]
Hi @fargito - This is being implemented as part of #888

**Comment by georgebearden** [comment]
#888 is now merged and will be available in the next release. It includes both custom request and response templates.

**Comment by fargito** [comment]
Thanks a lot! I'll look into it
