### ISSUE TITLE
Make alarm creation optional

### ISSUE THREAD

**Issue by dscpinheiro** [awslabs/aws-solutions-constructs#85]
For a few services (`Kinesis Data Streams`, `Elasticsearch`, and `Step Functions`), Constructs automatically creates some CloudWatch alarms. However, even though they're available as properties, it's not possible to modify them:

```javascript
// Deploy best practices CW Alarms for Kinesis Stream
this.cloudwatchAlarms = defaults.buildKinesisStreamCWAlarms(this);
const someAlarm = this.cloudwatchAlarms[0];

// I can get the metric configuration, but that doesn't allow me to change anything (such as thresholds)
// This metricConfig object only contains metadata about the metric, such as which stat (avg, max, etc) was used
const metricConfig = someAlarm.metric.toMetricConfig();

// Other than adding actions, there's not a lot I can do on the alarm itself either
someAlarm.addAlarmAction();
```

### Use Case
Customers might have different requirements to the defaults used by Constructs (for example, they might want to be alerted when `IteratorAge` goes above 1 hour - instead of 12). They'd create this custom alarm on their CDK project, and would not want any duplication.

### Proposed Solution
In all constructs that add alarms, add an option customers can set to `false` to disable their creation:

```javascript
/**
 * Whether to create recommended CloudWatch alarms
 *
 * @default - Alarms are created
 */
readonly createCloudWatchAlarms?: boolean
```

---

This is a :rocket: Feature Request

**Comment by hnishar** [comment]
Pushed out in the latest release v1.67.0
