### ISSUE TITLE
Error when behavior overrides is performed on cloudfront distribution.

### ISSUE THREAD

**Issue by gattasrikanth** [awslabs/aws-solutions-constructs#86]
### Description:

When overriding the behaviors its removing the customOrigin since both belong to the same struct originConfigs

### Reproduction Steps
Run the below code
```
const apigateway_lambda_props = {
    deployLambda: true,
    lambdaFunctionProps: {
        code: lambda.Code.fromAsset('lambda/assets/api_lambda.zip'),
        runtime: lambda.Runtime.NODEJS_12_X,
        handler: 'index.handler',
        timeout: cdk.Duration.minutes(5),
    },
    apiGatewayProps: {
        restApiName: 'RestAPI',
        defaultMethodOptions: {
            authorizationType: api.AuthorizationType.NONE,
        },
        binaryMediaTypes: ["*/*"]
    },
    cloudFrontDistributionProps: {
        comment: 'CF For Gateway',
        originConfigs: [
            {
                behaviors: [
                    {
                        isDefaultBehavior: true,
                        pathPattern: '*',
                        maxTtl: cdk.Duration.hours(10),
                        minTtl: cdk.Duration.hours(5),
                        defaultTtl: cdk.Duration.hours(8)
                    },
                    {
                        isDefaultBehavior: false,
                        pathPattern: '/api/*',
                        maxTtl: cdk.Duration.seconds(0),
                        minTtl: cdk.Duration.seconds(0),
                        defaultTtl: cdk.Duration.seconds(0)
                    }]
            }
        ]
    }
}
const apiToLambda = new cfapigwlambda.CloudFrontToApiGatewayToLambda(this, 'cloudfront', 
                                     apigateway_lambda_props);
```

### Error Log
Run `cdk synth` or `cdk deploy`
```
 throw new Error('There must be at least one origin source - either an s3OriginSource, a customOriginSource');
     ^
Error: There must be at least one origin source - either an s3OriginSource, a customOriginSource
```

### Environment

  - **CDK CLI Version      :** 1.67.0 (build 2b4dd71)
  - **CDK Framework Version:**
  - **AWS Solutions Constructs Version     :** @aws-solutions-constructs/aws-cloudfront-apigateway-lambda 1.66.0
  - **OS                   :** Mac OS
  - **Language             :** Javascript

#### My Usecase:

- I am trying to setup a RestAPI, which ideally drives my website. If the request contains a path /api/* then lambda function will fetch DynamoDb tables and serves data, for all other requests lambda function simply reads the file from S3 bucket and send it back.
- I want to cache all requests except the ones that has /api/* (so that lambda function will always be triggered and serve latest data)
- So I tried to update the `behaviour` in `cloudFrontDistributionProps`

--- 

This is :bug: Bug Report

**Comment by hnishar** [comment]
The latest release v1.68.0 has a better way of solving the override Cloudfront Props using the newer L2 construct `Distribution`, for reference check [this](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/aws-cloudfront-apigateway-lambda/test/integ.override-behavior.ts) integration test case.
