### ISSUE TITLE
CF function runtime is dated

### ISSUE THREAD

**Issue by altho1** [awslabs/aws-solutions-constructs#872]
CDK rejects the CloudFront function because of its node.js version (is 14 should be 18)

Generated CFN:
```
  "AWS679f53fac002430cb0da5b7982bd22872D164C4C": {
   "Type": "AWS::Lambda::Function",
   "Properties": {
    "Code": {
     "S3Bucket": "cdk-aws-assets-zz-us-east-1",
     "S3Key": "yy.zip"
    },
    "Role": {
     "Fn::GetAtt": [
      "AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2",
      "Arn"
     ]
    },
    "Handler": "index.handler",
    "Runtime": "nodejs14.x",
    "Timeout": 120
   },
   "DependsOn": [
    "AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2"
   ],
   "Metadata": {
    "aws:cdk:path": "ca/AWS679f53fac002430cb0da5b7982bd2287/Resource",
    "aws:asset:path": "asset.e845402ce43b66fc6f20df4a239f20f8662eb6c7f920b94cf6542dd0e64ce0f7",
    "aws:asset:is-bundled": false,
    "aws:asset:property": "Code"
   }
  },
```

### Reproduction Steps
```
{
  "name": "cdk",
  "version": "0.1.0",
  "bin": {
    "cdk": "bin/main.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest --verbose",
    "cdk": "cdk",
    "cdk synth": "cdk synth --all",
    "cdk deploy": "cdk deploy --all"
  },
  "devDependencies": {
    "@types/jest": "^29.2.4",
    "@types/node": "^18.11.11",
    "@types/prettier": "^2.7.1",
    "jest": "^29.3.1",
    "ts-jest": "^29.0.3",
    "ts-node": "^10.9.1",
    "typescript": "~4.9.4"
  },
  "dependencies": {
    "@aws-solutions-constructs/aws-lambda-dynamodb": "^2.29.0",
    "@aws-solutions-constructs/aws-cloudfront-apigateway": "^2.29.0",
    "@aws-cdk/aws-lambda-python-alpha": "^2.54.0-alpha.0",
    "aws-cdk-lib": "^2.54.0",
    "cdk-nag": "^2.21.25",
    "constructs": "^10.1.183",
    "source-map-support": "^0.5.21"
  }
}
```

``` node
    const cf = new CloudFrontToApiGateway(this, 'caCF2API', {
      existingApiGatewayObj: apiGateway,
      cloudFrontDistributionProps: {
        minimumProtocolVersion: {
          securityPolicy: cloudfront.SecurityPolicyProtocol.TLS_V1_2_2021
        },
        priceClass: cloudfront.PriceClass.PRICE_CLASS_100,
        defaultBehavior: {
          origin: new origins.HttpOrigin(apiDomainName),
          allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
          originRequestPolicy: cfORP,
          cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
        },
      },
      cloudFrontLoggingBucketProps: {
        blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
        removalPolicy: RemovalPolicy.DESTROY,
      }
    });
```
### Error Log
``` 
[Error at /ca/AWS679f53fac002430cb0da5b7982bd2287/Resource] AwsSolutions-L1: The non-container Lambda function is not configured to use the latest runtime version. . Use the latest available runtime for the targeted language to avoid technical debt. Runtimes specific to a language or framework version are deprecated when the version reaches end of life. This rule only applies to non-container Lambda functions.
```

### Environment

  - **CDK CLI Version      :** 2.54.0 (build 9f41881)
  - **CDK Framework Version:** See above
  - **AWS Solutions Constructs Version     :** See above
  - **OS                   :** Ubuntu 22.04.1 LTS
  - **Language             :** js

### Other

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Thanks - we'll take a look.

**Comment by biffgaut** [comment]
Are you running cdk_nag? This error appears to be generated from that tool.

**Comment by altho1** [comment]
Yep - that is the tool detecting the error and stopping the synth 

 "cdk-nag": "^2.21.25",
 
 I am putting in a suppression in for now, but that is not really a solution

**Comment by biffgaut** [comment]
I'm not sure where that function originates - can you grab it from the CDK staging bucket and see the contents? I've launched a minimal CloudFrontToApiGateway with security headers turned on - that generates the CloudFront function, but I don't see any Lambda functions with Node14. I think it might be a custom resource generated by the CDK to support origins or CloudFront logging.

cdk_nag is not a part of the CDK and not supported by the CDK team. While looking through the CDK code as I explored this issue, I see that there are still several references to Node 14 in the CDK codebase - 

* [aws-amplify](https://github.com/aws/aws-cdk/blob/de46ca6dab1eac5bd60527e98f3c46ca2b90417a/packages/%40aws-cdk/aws-amplify/lib/branch.ts#L240)
* [aws-certificatemanager](https://github.com/aws/aws-cdk/blob/de46ca6dab1eac5bd60527e98f3c46ca2b90417a/packages/%40aws-cdk/aws-certificatemanager/lib/dns-validated-certificate.ts#L110)
* [aws-dynamodb](https://github.com/aws/aws-cdk/blob/de46ca6dab1eac5bd60527e98f3c46ca2b90417a/packages/%40aws-cdk/aws-dynamodb/lib/replica-provider.ts#L53)
* etc. (there are many more)

So while the CDK will supposedly address these before NodeJS 14 goes end of life in 4 months, conflict with cdk_nag will probably continue until then.

**Comment by altho1** [comment]
Thanx I will raise it with cdk_nag and ask them to warn until Node 14 is EOL.

The function was not the CF function that is correct (would be nice with construct Ids in the CFN) - it was an AwsCustomResource as you guessed, but the issue will remain until you are fully upgraded, or cdk_nag downgrades it to a warning.

``` node
      new AwsCustomResource(this, 'initDBResource', {
        onCreate: {
          service: 'DynamoDB',
          action: 'putItem',
```
