### ISSUE TITLE
Function name is not unique

### ISSUE THREAD

**Issue by volkanunsal** [awslabs/aws-solutions-constructs#878]
The id of the function should be unique in [this line](https://github.com/awslabs/aws-solutions-constructs/blob/88f3916c968472b7f1e1a6ce8ca7e19ccd520691/source/patterns/%40aws-solutions-constructs/core/lib/cloudfront-distribution-helper.ts#L51). Otherwise, we cannot use this helper more than once in the same stack.

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Thanks

The name is based upon the full location in the stack, when we run the following code it creates two CloudFront Functions in the stack:

```
export class Issue878Stack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new CloudFrontToS3(this, 'first-instance', {
      insertHttpSecurityHeaders: true
    });

    new CloudFrontToS3(this, 'second-instance', {
      insertHttpSecurityHeaders: true
    });
    
  }
}
```
![image](https://user-images.githubusercontent.com/78155736/208444357-f70774fd-d996-4498-8d92-2aebf56153cf.png)

Could you include a snippet of code that is not working?

**Comment by volkanunsal** [comment]
I used it from the helper, and that's the first error I encountered due to naming conflict. 

```ts
const [cfDistribution] = CloudFrontDistributionForS3(
      this,
      this.bucket,
      {
        domainNames: [],
        enableLogging: false,
      },
      false,
      originPath
    );
```

I've had to replicate most of the helper code in my class and add a namespace for each distribution to make the code compile. But I'm wondering if there is a better way. The helper functions don't seem to have a way to namespace the distros, or maybe I'm not seeing it....

**Comment by volkanunsal** [comment]
Here is a more complete snippet:

```ts
export class AppStack extends Stack {
  
  constructor(
    scope: Construct,
    id: string,
    public props: StackProps
  ) {
    super(scope, id, props);

    for (const item of stages) {
      const cfDistribution = this.createDistro(item);

    }
  }

  private createDistro(stage: string) {
    const originPath = `stages/${stage}/current`;
    const [cfDistribution] = CloudFrontDistributionForS3(
      this,
      this.bucket,
      {
        domainNames: [],
      },
      false,
      originPath,
    );
    return cfDistribution;
  }
}
```

**Comment by biffgaut** [comment]
We don't recommend using the non-documented helper functions, changing the internal implementation of a construct without changing the external behavior would not be considered a breaking change to the construct but could break your dependent code. Others who want to use the helper functions have had success copying them to their own project (which it sounds like you have already done).
