### ISSUE TITLE
Documentation for minimal version  of Iot To Lambda To Dynamo

### ISSUE THREAD

**Issue by Gamecock** [awslabs/aws-solutions-constructs#886]
### Reproduction Steps
N/A

### Error Log
N/A

### Environment
N/A

### Other
https://aws.amazon.com/blogs/aws/aws-solutions-constructs-a-library-of-architecture-patterns-for-the-aws-cdk/
shows how to link a dynamo table table 

I can add this to the example

`iotToLambdaToDynamo.lambda_function.add_environment("TABLE_NAME", iotToLambdaToDymamo.dynamo_table.table_name)

or can take a more opinionated approach and make that happen as part of the pattern, but I have not seen setting ENV variables in any other construct.  Open to suggestions.

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
This is actually a deficiency in the docs for that construct. aws-iot-lambda-dynamodb instantiates an aws-lambda-dynamodb construct internally - the docs for that construct confirm that an environment variable is set for the Lambda function: DDB_TABLE_NAME. It is a convention that when an environment variable is being set, we expose an optional property so clients can customize that name (e.g. - if a Lambda function is associated with 2 DDB tables), so in addition to updating the docs to show that an environment variable is getting set we'll also add the ability to customize the environment variable name to this interface similarly to what you see on aws-lambda-dynamodb.

**Comment by biffgaut** [comment]
This has been addressed in release 2.31.0
