### ISSUE TITLE
LambdaToElasticSearchAndKibana : deployment fails with default settings

### ISSUE THREAD

**Issue by krokoko** [awslabs/aws-solutions-constructs#908]
When using the construct with default parameters, issue happens during deployment:

```NumberOfAvailabilityZones should be either 2 or 3 (Service: AWSElasticsearch; Status Code: 400; Error Code: ValidationException;```

### Reproduction Steps

Testing the code from documentation:

```
from aws_solutions_constructs.aws_lambda_elasticsearch_kibana import LambdaToElasticSearchAndKibana

lambda_props = _lambda.FunctionProps(
    code=_lambda.Code.from_asset('functions/opensearchdatastream/src'),
    runtime=_lambda.Runtime.PYTHON_3_9,
    handler='lambda.handler'
    )

   LambdaToElasticSearchAndKibana(self, 'sample',
                            lambda_function_props=lambda_props,
                            domain_name='mysuperdomainname',
                            cognito_domain_name='mysupercognitoname'
                            )
```

### Error Log

NumberOfAvailabilityZones should be either 2 or 3 (Service: AWSElasticsearch; Status Code: 400; Error Code: ValidationException; Request ID: 9f8c3838-1186-46d0-bc44-81235ac7510d; Proxy: null)

### Environment

  - **CDK CLI Version      :*2.65.0 (build 5862f7a)*
  - **CDK Framework Version:**
  - **AWS Solutions Constructs Version     :*2.32.0*
  - **OS                   :*<MacOS*
  - **Language             :*Python*

### Other

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Thanks, we'll take a look.

**Comment by biffgaut** [comment]
What region are you using for deployment?

**Comment by krokoko** [comment]
Thanks ! Region is us-east-1

I disabled zone awareness and it deployed successfully 
```
propsesconfig = elasticsearch.CfnDomainProps(
      elasticsearch_cluster_config=elasticsearch.CfnDomain.ElasticsearchClusterConfigProperty( 
        zone_awareness_enabled=False
    ))
```

**Comment by biffgaut** [comment]
When we run that code we are successful in deploying the stack (although we need to change the cognito domain name to not include 'cognito'). So we need to figure out what's different - my first guess is that your account has more than 3 AZs assigned in us-east-1. 

Can you perform a cdk synth and post the results? (take care to remove any info you don't want on the web)

Can you try launching in us-east-2 to see if the behavior is the same?

Can you post the contents of app.py (delete any info like your account number first)

Thanks

**Comment by krokoko** [comment]
Sorry for the delayed response, but this was indeed the issue ! I was deploying in us-east-1. Thank you for the additional details !
