### ISSUE TITLE
Gold Image Pipelines ++ EC2 Blue-Green Deployment Pipelines

### ISSUE THREAD

**Issue by sholtomaud** [awslabs/aws-solutions-constructs#91]
The management of EC2 for zero downtime is a requirement for modern IaaC on AWS but hard to achieve with the CDK.  

### Use Case

A typical production environment requires two pipelines for the management of infrastructure. Golden Images pipelines for patching the OS and inclusion of components, and the deployment of EC2  instances for zero downtime with Blue-Green deployment methods.

### Proposed Solution

The reference implementation would demonstrate:

1. Golden Image maintenance for patching and basic required components with ImageBuilder 
2. Deployments of EC2s using the Golden Images achieving Zero-downtime through Blue-Green and similar methods
3. Appropriate IAM roles and policies for such a method. 

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by hnishar** [comment]
sholtomaud@ CDK has an issue to track the progress of L2 (higher-level) construct for [EC2 Image Builder](https://github.com/aws/aws-cdk/issues/8641) which I believe will help with your use case

**Comment by hnishar** [comment]
Closing the issue, feel free to re-open if you have further questions
