### ISSUE TITLE
Add and document expected structure and logic when lambda is involved

### ISSUE THREAD

**Issue by flochaz** [awslabs/aws-solutions-constructs#94]
For new comers in CDK willing to test solutions construct, it would be great to have more info and what needs to be setup in addition to the construct instantiation code.

### Use Case

When starting to use any construct involving lambda such as https://docs.aws.amazon.com/solutions/latest/constructs/aws-lambda-sqs.html we need, in addition to adding the documented code, 
1. create a `lambda` folder, 
1. create an `index.js` file in it, 
1. figure out how to write to a queue (https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/sqs-examples-send-receive-messages.html)
1. dig into to the construct code to figure out what environment variable will be set for the SQS queue ...

### Proposed Solution

Add documentation in addition to code snippet on:
1. folder structure 
1. Env variables names set for the lambda
1. Snippet of lambda code

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
We will add a comment explaining the assumption of file structure in the minimal code.

Sample implementations are on our backlog, but not on the roadmap at this point.

**Comment by biffgaut** [comment]
Released in 1.94.0
