### ISSUE TITLE
[aws-dynamodbstreams-lambda] Migration from CDK v1 fails due to "[function] already exists in stack" error

### ISSUE THREAD

**Issue by tmarcinkowski-logitech** [awslabs/aws-solutions-constructs#968]
I'm migrating from CDK1 to CDK2 while updating Solutions Constructs Library as well. `cdk diff` shows unexpected changes (function renames leading to their recreation) and the deployment fails ("function already exists in the stack").

### Reproduction Steps

**BEFORE** - CDK v1

```sh
$ npx cdk --version
1.181.1 (build 758abae)
```

package.json:

```json
{
  "devDependencies": {
    "aws-cdk": "1.181.1",
    "@aws-cdk/assert": "1.181.1",
    "@aws-cdk/assertions": "1.181.1",
    "@aws-cdk/aws-codepipeline": "1.181.1",
    "@aws-cdk/aws-codepipeline-actions": "1.181.1",
    "@aws-cdk/aws-route53-targets": "1.181.1",
    "@aws-cdk/aws-s3-deployment": "1.181.1",
    "@aws-cdk/core": "1.181.1",
    "@aws-cdk/custom-resources": "1.181.1",
    "@aws-cdk/pipelines": "1.181.1",
    "@aws-solutions-constructs/aws-cloudfront-s3": "1.181.1",
    "@aws-solutions-constructs/aws-cognito-apigateway-lambda": "1.181.1",
    "@aws-solutions-constructs/aws-dynamodbstreams-lambda": "1.181.1"
  }
}
```

- deployment using cdk v1 ran fine - the only changes in the diff were assets hashes
- any change to feature flags that are obsolete in cdk2 had no impact at this stage

**AFTER** - CDK v2

```sh
$ npx cdk --version
2.81.0 (build bd920f2)
```

package.json:

```json
{
  "devDependencies": {
    "aws-cdk-lib": "^2.76.0",
    "@aws-solutions-constructs/aws-cloudfront-s3": "2.39.0",
    "@aws-solutions-constructs/aws-cognito-apigateway-lambda": "2.39.0",
    "@aws-solutions-constructs/aws-dynamodbstreams-lambda": "2.39.0",
    "constructs": "^10.2.39"
  }
}
```

### Error Log

- `cdk diff` shows a lot of unexpected changes to logical IDs for some resources, like lambda functions and event source mappings
  - I can share non-obfuscated snippets in private
- `Resources` section shows many things (e.g. DDB stream handlers / lambda triggers) being destroyed and then recreated, which is probably not expected too

Deployment fails with:

```
MyProject: creating CloudFormation changeset...
4:07:04 PM | CREATE_FAILED        | AWS::Lambda::Function                           | sdsadsadasdasd...sadsadasd31C177C4
MyProjectMyFunction already exists in stack arn:aws:cloudformation:us-west-2:11111111111111:stack/MyProject/5fa97d90-58de-11ec-a125-0a856a2e201b
```

which relates to a DynamoDB stream handler function.

The failing function shows in `cdk diff` **only as something to create**, there is no "destroy" counterpart.

It is created by this specific pattern / solution construct:

```ts
new DynamoDBStreamsToLambda(
    this,
    'MyFunction',
    {
        existingTableInterface: myTable,
        lambdaFunctionProps: {
            functionName: `${props.stackName}MyFunction`,
            code: lambda.Code.fromAsset(path.join(__dirname, '..', '..', 'api', 'dist')),
            runtime: lambda.Runtime.NODEJS_14_X,
            handler: 'myFunction.handler',
            logRetention: RetentionDays.ONE_WEEK,
            environment: {
                // ...
            },
        },
    },
);
```

### Environment

_specified above_

### Other

I followed [instructions](https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html#migrating-v2-diff.title) on CDK migration however I have a gut feeling that this is something specific to Solutions Constructs.

Presumably, I could get around that by changing the function's name, but I'd like the whole migration to be as streamlined as possible.  
EDIT: changing the name still creates a new function but doesn't delete the old one, so there'll be leftovers.

~~Is this because currently the function runs on outdated Node.js runtime?~~  
EDIT: Changing Node.js runtime version to v16 didn't change anything either.

Is there any additional step I should take for my solutions constructs update?  

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Sorry for the delay responding here.

The differences in the synth code are not necessarily a problem, the output of CDK behind the scenes changes frequently between versions, even minor versions. For instance, at one point the CDK team changed a lot of their custom resources from Javascript to Python. As we run snapshot tests against our output, we see this all the time.

The error is obviously not appropriate. Does this fail when you create the stack? Or is this occurring when you are updating a stack originally launched with CDK V1 using CDK V2 code?

**Comment by tmarcinkowski-logitech** [comment]
This happens for a stack originally created with CDK v1 when trying to update it with v2 code.

I don't expect the same issue in a completely new stack, but haven't tried it. My goal is to update existing prod stack at the end of the day, thus recreating it from scratch is not an option.

**Comment by biffgaut** [comment]
I am unable to recreate the issue so far. I launched this V1 CDK stack:

```
import * as cdk from '@aws-cdk/core';
import * as lambda from '@aws-cdk/aws-lambda';
import { DynamoDBStreamsToLambda } from '@aws-solutions-constructs/aws-dynamodbstreams-lambda';
import { CognitoToApiGatewayToLambda } from '@aws-solutions-constructs/aws-cognito-apigateway-lambda';

export class DdbstreamsTestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new DynamoDBStreamsToLambda(this, 'test-dynamodbstreams-lambda', {
      lambdaFunctionProps: {
          code: lambda.Code.fromAsset(`lambda`),
          runtime: lambda.Runtime.NODEJS_14_X,
          handler: 'index.handler'
      },
    });

    new CognitoToApiGatewayToLambda(this, 'test-cognito-apigateway-lambda', {
      lambdaFunctionProps: {
        code: lambda.Code.fromAsset(`lambda`),
        runtime: lambda.Runtime.NODEJS_14_X,
        handler: 'other-index.handler'
      }
    });
  }
}
```
(CDK 1.181.0, all Solutions Constructs 1.181.0). Then I moved the code to CDK V2 app and updated the existing stack successfully:

```
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import  { DynamoDBStreamsToLambda } from '@aws-solutions-constructs/aws-dynamodbstreams-lambda';
import  { CognitoToApiGatewayToLambda } from '@aws-solutions-constructs/aws-cognito-apigateway-lambda';

export class DdbstreamsTestStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new DynamoDBStreamsToLambda(this, 'test-dynamodbstreams-lambda', {
      lambdaFunctionProps: {
          code: lambda.Code.fromAsset(`lambda`),
          runtime: lambda.Runtime.NODEJS_14_X,
          handler: 'index.handler'
      },
    });

    new CognitoToApiGatewayToLambda(this, 'test-cognito-apigateway-lambda', {
      lambdaFunctionProps: {
        code: lambda.Code.fromAsset(`lambda`),
        runtime: lambda.Runtime.NODEJS_14_X,
        handler: 'other-index.handler'
      }
    });

  }
}
```
(CDK 2.85.0, Solutions Constructs 2.41.0). Can you share any more info about your code that is deploying the constructs? (e.g. - are you sharing a lambda function between API Gateway and DynamoDB streams)

**Comment by biffgaut** [comment]
When you launch the CognitoToApigatewayToLambda construct, you don't use the same name for the function by any chance?

```
            functionName: `${props.stackName}MyFunction`,
```

In general, it's usually better not to provide a name for the actual resource - leave it up to CloudFormation. While we're trying to figure out what's going on, you might try a test where you drop the function name property.

**Comment by biffgaut** [comment]
I was able to reproduce the issue - I added function name props to my Lambda functions and got the behavior you describe.

So then I deployed with a function name with CDK V1, but removed the function name property before running a Stack Update generated by CDK V2. This worked, and the original (named) Lambda functions were removed.

**Comment by biffgaut** [comment]
We don't have it in our docs anywhere as it is a characteristic of CDK and CloudFormation. The CFN docs discuss the generated vs specific resource name behavior [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-name.html).
