### ISSUE TITLE
aws-lambda-sqs-lambda - FIFO Support

### ISSUE THREAD

**Issue by dextel2** [awslabs/aws-solutions-constructs#976]
### Discussed in https://github.com/awslabs/aws-solutions-constructs/discussions/974

<div type='discussions-op-text'>

<sup>Originally posted by **dextel2** June  7, 2023</sup>
I was wondering if we have support for FIFO File processing, say.

I have first lambda function which is trigged if an object is dropped in a S3 bucket, which further on goes to processing in the second lambda function and meanwhile I upload another object in the same S3 bucket but this time the second object is completed in process and then the first object is processed.

So I was wondering if there is any way to process file sequentially i.e. FIFO.
</div>

**Comment by biffgaut** [comment]
I don't think what you're asking for is possible - event handling for objects dropped in an S3 bucket are not FIFO. Beyond that, if two different Lambda functions are processing 2 different objects there will always be a risk the wrong one finishes first. Setting Lambda Concurrency to 1 will avoid one Lambda execution passing another, then you might find some help in this discussion on this topic - https://github.com/awslabs/aws-solutions-constructs/discussions/974#discussioncomment-6136540
