### ISSUE TITLE
CloudFront-to-S3 need to change restrict access to an Amazon S3 bucket from Legacy access identities (OAI) to CloudFront origin access control (OAC)

### ISSUE THREAD

**Issue by YikaiHu** [awslabs/aws-solutions-constructs#979]
CloudFront-to-S3 package need to change restrict access to an Amazon S3 bucket from Legacy access identities (OAI) to CloudFront origin access control (OAC).

Current behaviour:

<img width="917" alt="image" src="https://github.com/awslabs/aws-solutions-constructs/assets/34271744/4230c2e6-4ad7-4af8-a471-626246075068">

### Use Case

- Use AWS CloudFront best practice.
- Prevent the CloudFront-to-S3 solution construct from failing due to CloudFront offline OAI function

### Proposed Solution

Change the default permission configuration in cloudfront-to-s3 package.

### Other

Here is the official blog about this CloudFront origin access control (OAC) 
https://repost.aws/knowledge-center/cloudfront-access-to-amazon-s3

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
Thanks - this is definitely on our list, but we will need a custom resource to implement so it won't be trivial.
