### ISSUE TITLE
Change in S3 -> breaks CloudfrontToS3

### ISSUE THREAD

**Issue by Tryanium** [awslabs/aws-solutions-constructs#980]
Trying to use the cloudfrontToS3 example in python and it's not working, due to some changes in S3. Is it a change to do in the package or am I missing something? I can create the S3 bucket for the storage but not for the logging.

```error
Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership; Request ID: KM88MB7N37J2JB0K; S3 Ext
ended Request ID: YHJmvuHnuJbxBSjNUTMDXPL8RT4ZdhVJ6M13Xv5sZvzk5gpuj/Db97I9Tu31iAz22HTrXixbTOA=; Proxy: null)
```

### Reproduction Steps

Use the package, and try this simple example 

```python
myCloudFrontToS3 = CloudFrontToS3(
            self, 'myTest', insert_http_security_headers=False)
```

### Error Log

I see this error 

```error
Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership; Request ID: KM88MB7N37J2JB0K; S3 Ext
ended Request ID: YHJmvuHnuJbxBSjNUTMDXPL8RT4ZdhVJ6M13Xv5sZvzk5gpuj/Db97I9Tu31iAz22HTrXixbTOA=; Proxy: null)
```

### Environment

  - **CDK CLI Version      :** 2.84.0
  - **CDK Framework Version:**
  - **AWS Solutions Constructs Version     :** 2.8.0
  - **OS                   :** Macos
  - **Language             :** ENG

### Other

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
There was a change in the S3 service that broke constructs in the Spring - upgrading to the latest version of Solutions Constructs should fix your issue.

**Comment by Tryanium** [comment]
Thx for your quick answer, I'm using the (2.8.0), is it not the latest version?

**Comment by biffgaut** [comment]
No, we're up to 2.41.0 at this point :-)

**Comment by Tryanium** [comment]
Thanks, will try it now!
